### ISSUE TITLE
Problems with custom column types when using joins.

### ISSUE THREAD

**Issue by Zverijo** [JetBrains/Exposed#101]
In my project I have custom column type for working with PostgreSQL Enums. It works perfectly, with the only exception: there is a problem when I try to use it with joins. 

My class for operation with pg enums:
```kotlin
import org.jetbrains.exposed.sql.ColumnType
import java.sql.PreparedStatement
import java.sql.Types
import org.jetbrains.exposed.sql.Table


class EnumColumnType<T : Enum<T>>(val type: String, val enumClass: Class<T>) : ColumnType() {

    private val err = { value: Any -> error("$value is not valid for enum ${enumClass.name}") }

    val enumByName: (String) -> T? = { name: String -> enumClass.enumConstants!!.find { it.name == name } }

    override fun sqlType(): String = type

    override fun setParameter(stmt: PreparedStatement, index: Int, value: Any?) {
        stmt.setObject(index, value, Types.OTHER)
    }

    @Suppress("UNCHECKED_CAST")
    override fun valueFromDB(value: Any): Any {
        val f: Enum<T>? = when (value) {
            is Enum<*> -> value as Enum<T>
            is String -> enumByName(value) ?: err(value)
            else -> err(value)
        }
        return f as Any
    }

    override fun notNullValueToDB(value: Any): Any = vToStr(value)

    override fun nonNullValueToString(value: Any): String = vToStr(value)

    private fun vToStr(value: Any): String = when (value) {
        is Enum<*> -> value.name
        is Int -> enumClass.enumConstants!![value].name
        is String -> value
        else -> error("$value is not valid for enum ${enumClass.name}")
    }

}


```

Example of usage

```kotlin

enum class ProcessType { sport, champ, event }

object ProcessTable : Table("process") {
    //Other columns
    val type =  registerColumn("process_type",  EnumColumnType("process_type", ProcessType::class.java))
}
```

And if we try:

```kotlin
//This will works perfectly
transaction { 
    ProcessTable.join(EventTable, JoinType.INNER, onColumn = EventTable.id, otherColumn = ProcessTable.idExt, additionalConstraint = {(ProcessTable.active eq false)})
            .select{ProcessTable.type eq ProcessType.event }
            .forEach{ it }
}

//And here will be exception
transaction { 
    ProcessTable.join(EventTable, JoinType.INNER, onColumn = EventTable.id, otherColumn = ProcessTable.idExt, additionalConstraint = {(ProcessTable.active eq false) and (ProcessTable.type eq ProcessType.event )})
            .selectAll()
            .forEach{ it }
}
```

```
INFO Exposed - Transaction attempt #0: ERROR: operator does not exist: process_type = event
  Hint: No operator matches the given name and argument type(s). You might need to add explicit type casts.
  Position: 400. Statement: HikariProxyPreparedStatement@1473771722 wrapping SELECT process.id, process.live, process.process_type, process.id_ext, process.id_parent, process.data, process.pos, process.active, process.active_time, event.id, event.champ_id, event.name, event."start", event.br_id, event.team1_id, event.team2_id, event.video, event.img, event.fts FROM process INNER JOIN event ON event.id = process.id_ext and  (process.active = false and process.process_type = event)
org.postgresql.util.PSQLException: ERROR: operator does not exist: process_type = event
  Hint: No operator matches the given name and argument type(s). You might need to add explicit type casts.
  Position: 400
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2412)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2125)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:297)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:428)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:354)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:169)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:117)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
	at org.jetbrains.exposed.sql.Query.executeInternal(Query.kt:91)
	at org.jetbrains.exposed.sql.Query.executeInternal(Query.kt:78)
	at org.jetbrains.exposed.sql.statements.Statement.executeIn$exposed_main(Statement.kt:52)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:105)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:99)
	at org.jetbrains.exposed.sql.Query.iterator(Query.kt:231)
	at Line9$1.invoke(line9.kts:19)
	at Line9$1.invoke(line9.kts:13)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction(ThreadLocalTransactionManager.kt:70)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:58)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:49)

```

For some reason when you try to use this custom ColumnType in joins it works differently than in select.

If I made a mistake in the inheritance from ColumnType class, please specify what it is.

**Comment by Tapac** [comment]
Looks like a bug.
BTW, do you look at enumeration and enumerationByName() functions?

**Comment by Zverijo** [comment]
Yes, I know about these functions, they work well, but in this project we have to use an pg enums (there is few projects, which already work with the same database and use the postgres enumerations).

**Comment by Tapac** [comment]
I'm not sure, but looks like you have to use special syntax or cast function if you want to use PG enums:
 http://www.gotoquiz.com/web-coding/programming/java-programming/convert-between-java-enums-and-postgresql-enums/  
In your example there is confusion between Event table name and event enum value.

Problem here is that Exposed doesn't use jdbc parameters in join part of query, so it just calls nonNullValueToDb function which return `process.process_type = event` instead of `process.process_type = ?`.
Try to change it to `event::process_type`.

**Comment by Zverijo** [comment]
Okay, I understand my mistake, thank you. 
It works now, but, I think you meant "nonNullValueToString" in the comment above?

So, this issue can be closed.

**Comment by Tapac** [comment]
Yes, definitely "nonNullValueToString". Glad that it helps you.
