### ISSUE TITLE
Can't read text column, if it exceeds 255 chars.

### ISSUE THREAD

**Issue by neetkee** [JetBrains/Exposed#1029]
Starting with **0.26.2** it's impossible to read text column, if its length exceeds 255 symbols. However, it's possible to write such value.

DB: Postgresql

Example data:
```sql
create table test
(
    id      uuid default gen_random_uuid() not null primary key,
    content text                           not null
);
```
```kotlin
object TestTable: UUIDTable(name = "test") {
    val content = text("content")
}

class TestEntity(id: EntityID<UUID>): UUIDEntity(id) {
    companion object: UUIDEntityClass<TestEntity>(TestTable)
    var content by TestTable.content
}
```
```kotlin
@Test
fun `check exposed text column`() {
    val content = "a".repeat(256)
    transaction {
        TestEntity.new {
            this.content = content
        }
    }
    transaction {
        TestEntity.find { TestTable.content.eq(content) }.first()
    }
}
```

```
Value 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa' can't be stored to database column because exceeds length (255)
java.lang.IllegalArgumentException: Value 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa' can't be stored to database column because exceeds length (255)
	at org.jetbrains.exposed.sql.VarCharColumnType.notNullValueToDB(ColumnType.kt:541)
	at org.jetbrains.exposed.sql.IColumnType$DefaultImpls.valueToDB(ColumnType.kt:37)
	at org.jetbrains.exposed.sql.ColumnType.valueToDB(ColumnType.kt:71)
	at org.jetbrains.exposed.sql.statements.api.PreparedStatementApi$DefaultImpls.fillParameters(PreparedStatementApi.kt:13)
	at org.jetbrains.exposed.sql.statements.jdbc.JdbcPreparedStatementImpl.fillParameters(JdbcPreparedStatementImpl.kt:9)
	at org.jetbrains.exposed.sql.statements.Statement.executeIn$exposed_core(Statement.kt:53)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:129)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:115)
	at org.jetbrains.exposed.sql.Query.iterator(Query.kt:214)
	at org.jetbrains.exposed.sql.IterableExKt$mapLazy$1.iterator(IterableEx.kt:129)
	at kotlin.collections.CollectionsKt___CollectionsKt.first(_Collections.kt:198)
```

**Comment by TheReprator** [comment]
is it sorted because i am facing the same issue on 0.27.1,
https://stackoverflow.com/questions/64196526/postgres-update-failed-when-comparing-a-string-whose-length-is-greater-than-255
