### ISSUE TITLE
SchemaUtils.dropDatabase() cannot be used on Postgres?

### ISSUE THREAD

**Issue by FatalCatharsis** [JetBrains/Exposed#1039]
When I run:
```
val root = Database.connect(connectionStr + "/${config.admin.db}", driver, config.admin.username, config.admin.password)

SchemaUtils.dropDatabase(config.target.db)
SchemaUtils.createDatabase(config.target.db)
```
results in this:
```
Exception in thread "main" java.lang.IllegalStateException: No transaction in context.
	at org.jetbrains.exposed.sql.transactions.TransactionManager$Companion.current(TransactionApi.kt:92)
	at org.jetbrains.exposed.sql.SchemaUtils.dropDatabase(SchemaUtils.kt:206)
	at org.jetbrains.exposed.sql.SchemaUtils.dropDatabase$default(SchemaUtils.kt:205)
	at github.fatalcatharsis.MainKt.main(Main.kt:41)
	at github.fatalcatharsis.MainKt.main(Main.kt)
```
However, when I run this:
```
val root = Database.connect(connectionStr + "/${config.admin.db}", driver, config.admin.username, config.admin.password)

transaction(root) {
    SchemaUtils.dropDatabase(config.target.db)
    SchemaUtils.createDatabase(config.target.db)
}
```
results in this:
```
Caused by: org.postgresql.util.PSQLException: ERROR: DROP DATABASE cannot run inside a transaction block
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2477)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2190)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:300)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:428)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:354)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:169)
	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:136)
	at org.jetbrains.exposed.sql.statements.jdbc.JdbcPreparedStatementImpl.executeUpdate(JdbcPreparedStatementImpl.kt:23)
	at org.jetbrains.exposed.sql.Transaction$exec$2.executeInternal(Transaction.kt:93)
	at org.jetbrains.exposed.sql.statements.Statement.executeIn$exposed_core(Statement.kt:61)
	... 19 more
```
Is this a bug or am I missing something here?

**Comment by cquemin** [comment]
I have exactly the same issue but I am only using `SchemaUtils.createDatabase(DATABASE_NAME)`. 
How can we create or drop database on POSTGRE. I am using `org.postgresql:postgresql:42.2.2`

**Comment by brunopessanha** [comment]
Same issue here, any updates on this issue?

**Comment by nallwhy** [comment]
MySQL is not the only database.

**Comment by nallwhy** [comment]
I found the solution from `exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/ddl/CreateDatabaseTest.kt`.

```kotlin
transaction {
    connection.autoCommit = true
    SchemaUtils.createDatabase(config.target.db)
    connection.autoCommit = false
}
```
