### ISSUE TITLE
Requests to Postgres with a lot of parameters are failing with: "Tried to send an out-of-range integer as a 2-byte value"  

### ISSUE THREAD

**Issue by kdoker** [JetBrains/Exposed#1083]
I use PostgreSQL 42.2.9, Exposed 0.17.7 and Kotlin 1.4.10
I'm trying to insert a lot of data with `batchInsert` like this:
```
    object TestTable : Table() {
        val name = varchar("name", 100).primaryKey().index()
    }

    TestTable.batchInsert(generateSequence { UUID.randomUUID().toString() }.take(50_000).toList()) {
        this[TestTable.name] = it
    }
```
And get an error because prepared statement contains too many parameters:
```
java.io.IOException: Tried to send an out-of-range integer as a 2-byte value: 50000
	at org.postgresql.core.PGStream.sendInteger2(PGStream.java:266)
	at org.postgresql.core.v3.QueryExecutorImpl.sendParse(QueryExecutorImpl.java:1500)
	at org.postgresql.core.v3.QueryExecutorImpl.sendOneQuery(QueryExecutorImpl.java:1823)
	at org.postgresql.core.v3.QueryExecutorImpl.sendQuery(QueryExecutorImpl.java:1386)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:302)
```
The same thing works with MySql.
The solution is to split large requests, but it would've been great if Exposed done it under the hood.

**Comment by Tapac** [comment]
Could you kindly update to Exposed 0.28.1 and check will it fail or not?
