### ISSUE TITLE
Can't add a new batch because columns don't have default values

### ISSUE THREAD

**Issue by SchweinchenFuntik** [JetBrains/Exposed#1090]
**h2Version**: 1.4.199
**exposedVersion**: 0.28.1
**JDK**: 15

**Code:**
```kotlin
import org.jetbrains.exposed.dao.id.IntIdTable

object Persons : IntIdTable() {
    val firstName = varchar("first_name", 255)
    val lastName = varchar("last_name", 255)
    val familyName = varchar("family_name", 255)
}

import org.jetbrains.exposed.dao.IntEntity
import org.jetbrains.exposed.dao.IntEntityClass
import org.jetbrains.exposed.dao.id.EntityID

class Person(id: EntityID<Int>) : IntEntity(id) {
    companion object : IntEntityClass<Person>(Persons)

    var firstName by Persons.familyName
    var lastName by Persons.lastName
    var familyName by Persons.familyName
}

import database.Person
import database.Persons
import org.jetbrains.exposed.sql.Database
import org.jetbrains.exposed.sql.SchemaUtils
import org.jetbrains.exposed.sql.StdOutSqlLogger
import org.jetbrains.exposed.sql.addLogger
import org.jetbrains.exposed.sql.transactions.transaction

fun main() {
    val db = Database.connect("jdbc:h2:mem:regular;DB_CLOSE_DELAY=-1;")
    val p = transaction(db) {
        SchemaUtils.create(Persons)
        Person.new {
            firstName = "FirstNameDev"
            lastName = "LastNameDev"
            familyName = "FamilyNameDev"
        }
    }
}
```
**gradle:**
```gradle
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
    kotlin("jvm") version "1.4.10"
    application
    id("org.openjfx.javafxplugin") version "0.0.9"
}

group = "group"
version = "1.0-SNAPSHOT"

val appName = "appName"
val javafxVersion: String by rootProject.extra
val h2Version: String by rootProject.extra
val exposedVersion: String by rootProject.extra
val kotlinxCoroutines: String by rootProject.extra

repositories {
    mavenCentral()
    jcenter()
    // other
}

javafx {
    version = javafxVersion
    modules("javafx.controls", "javafx.fxml", "javafx.media", "javafx.swing", "javafx.web")
}

application {
    mainClassName = "MainKt"
}

dependencies {
    implementation("org.jetbrains.kotlinx", "kotlinx-coroutines-javafx", kotlinxCoroutines)

    implementation("com.h2database", "h2", h2Version)
    implementation("org.jetbrains.exposed", "exposed-core", exposedVersion)
    implementation("org.jetbrains.exposed", "exposed-jdbc", exposedVersion)
    implementation("org.jetbrains.exposed", "exposed-java-time", exposedVersion)
    implementation("org.jetbrains.exposed", "exposed-dao", exposedVersion)

    implementation("ch.qos.logback", "logback-classic" , "1.2.3")

    testImplementation(kotlin("test-junit5"))
}

tasks.withType<KotlinCompile> {
    kotlinOptions.jvmTarget = "11"
}

java {
    sourceCompatibility = JavaVersion.VERSION_11
    targetCompatibility = JavaVersion.VERSION_11
}

```

**Console:**
```
22:21:32.580 [main] DEBUG Exposed - SELECT VALUE FROM INFORMATION_SCHEMA.SETTINGS WHERE NAME = 'MODE'
22:21:32.605 [main] DEBUG Exposed - CREATE TABLE IF NOT EXISTS PERSONS (ID INT AUTO_INCREMENT PRIMARY KEY, FIRST_NAME VARCHAR(255) NOT NULL, LAST_NAME VARCHAR(255) NOT NULL, FAMILY_NAME VARCHAR(255) NOT NULL)
Exception in thread "main" org.jetbrains.exposed.sql.statements.BatchDataInconsistentException: Can't add a new batch because columns: PERSONS.FIRST_NAME don't have default values. DB defaults don't support in batch inserts
	at org.jetbrains.exposed.sql.statements.BatchInsertStatement.validateLastBatch$exposed_core(BatchInsertStatement.kt:57)
	at org.jetbrains.exposed.sql.QueriesKt$batchInsert$2.invoke(Queries.kt:110)
	at org.jetbrains.exposed.sql.QueriesKt.batchInsert(Queries.kt:134)
	at org.jetbrains.exposed.sql.QueriesKt.batchInsert$default(Queries.kt:92)
	at org.jetbrains.exposed.dao.EntityCache.flushInserts$exposed_dao(EntityCache.kt:112)
	at org.jetbrains.exposed.dao.EntityCache.flush(EntityCache.kt:80)
	at org.jetbrains.exposed.dao.EntityCache.flush(EntityCache.kt:49)
	at org.jetbrains.exposed.dao.EntityCacheKt.flushCache(EntityCache.kt:154)
	at org.jetbrains.exposed.dao.EntityLifecycleInterceptor.beforeCommit(EntityLifecycleInterceptor.kt:40)
	at org.jetbrains.exposed.sql.Transaction.commit(Transaction.kt:63)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$inTopLevelTransaction$1.invoke(ThreadLocalTransactionManager.kt:171)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$inTopLevelTransaction$2.invoke(ThreadLocalTransactionManager.kt:211)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:219)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction(ThreadLocalTransactionManager.kt:210)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$transaction$1.invoke(ThreadLocalTransactionManager.kt:148)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:219)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:120)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:118)
	at komfort.MainKt.main(main.kt:26)
	at komfort.MainKt.main(main.kt)

Execution failed for task ':run'.
> Process 'command '/home/funtik/.sdkman/candidates/java/15.0.1.fx-librca/bin/java'' finished with non-zero exit value 1
```

**Comment by Tapac** [comment]
You map firstName to wrong column: `var firstName by Persons.familyName` should be `var firstName by Persons.firstName`

**Comment by SchweinchenFuntik** [comment]
Well, initially the columns were set correctly. Oh, my carelessness. thanks
