### ISSUE TITLE
Release 0.28.1 doesnt recognize MariaDB driver name correctly

### ISSUE THREAD

**Issue by fuyutsuki** [JetBrains/Exposed#1092]
This exception is raised when trying to get the database dialect:

```bash
java.lang.IllegalStateException: Unsupported driver MariaDB connector/J detected
        at org.jetbrains.exposed.sql.statements.jdbc.JdbcDatabaseMetadataImpl$databaseDialectName$2.invoke(JdbcDatabaseMetadataImpl.kt:31) ~[?:?]
        at org.jetbrains.exposed.sql.statements.jdbc.JdbcDatabaseMetadataImpl$databaseDialectName$2.invoke(JdbcDatabaseMetadataImpl.kt:13) ~[?:?]
        at org.jetbrains.exposed.sql.statements.jdbc.JdbcDatabaseMetadataImpl$lazyMetadata$1.invoke(JdbcDatabaseMetadataImpl.kt:210) ~[?:?]
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74) ~[?:?]
        at org.jetbrains.exposed.sql.statements.jdbc.JdbcDatabaseMetadataImpl.getDatabaseDialectName(JdbcDatabaseMetadataImpl.kt) ~[?:?]
        at org.jetbrains.exposed.sql.statements.jdbc.JdbcDatabaseMetadataImpl.getDatabaseName(JdbcDatabaseMetadataImpl.kt:36) ~[?:?]
        at org.jetbrains.exposed.sql.statements.jdbc.JdbcDatabaseMetadataImpl.columns(JdbcDatabaseMetadataImpl.kt:128) ~[?:?]
        at org.jetbrains.exposed.sql.vendors.VendorDialect$tableColumns$1.invoke(Default.kt:662) ~[?:?]
        at org.jetbrains.exposed.sql.vendors.VendorDialect$tableColumns$1.invoke(Default.kt:598) ~[?:?]
        at org.jetbrains.exposed.sql.statements.jdbc.JdbcConnectionImpl.metadata(JdbcConnectionImpl.kt:51) ~[?:?]
        at org.jetbrains.exposed.sql.vendors.VendorDialect.tableColumns(Default.kt:662) ~[?:?]
        at org.jetbrains.exposed.sql.SchemaUtils.addMissingColumnsStatements(SchemaUtils.kt:117) ~[?:?]
        at org.jetbrains.exposed.sql.SchemaUtils.createMissingTablesAndColumns(SchemaUtils.kt:240) ~[?:?]
        at org.jetbrains.exposed.sql.SchemaUtils.createMissingTablesAndColumns$default(SchemaUtils.kt:228) ~[?:?]
        at fake.Main$onLoad$1.invoke(Main.kt:17) ~[?:?]
        at fake.Main$onLoad$1.invoke(Main.kt:8) ~[?:?]
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$inTopLevelTransaction$1.invoke(ThreadLocalTransactionManager.kt:170) ~[?:?]
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$inTopLevelTransaction$2.invoke(ThreadLocalTransactionManager.kt:211) ~[?:?]
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:219) ~[?:?]
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction(ThreadLocalTransactionManager.kt:210) ~[?:?]
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$transaction$1.invoke(ThreadLocalTransactionManager.kt:148) ~[?:?]
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:219) ~[?:?]
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:120) ~[?:?]
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:118) ~[?:?]
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction$default(ThreadLocalTransactionManager.kt:117) ~[?:?]
```

Tested with `org.mariadb.jdbc:mariadb-java-client:2.1.2`.

**Comment by fuyutsuki** [comment]
Oops, the driver is too old...
