### ISSUE TITLE
IllegalStateException: Use Between with DateTime, H2 DB

### ISSUE THREAD

**Issue by hfhbd** [JetBrains/Exposed#1096]
Hey,
I want to execute this SQL (H2) query 
```SQL 
select * from Foos where current_date between Foos.validFrom and Foos.validUntil
```
by using
```kotlin
Foo.find {
    CurrentDateTime().between(Foos.validFrom, Foos.validUntil)
}
```
with these DAO/Definition.
```kotlin
object Foos: IntIdTable() {
    val validFrom = datetime("validFrom")
    val validUntil = datetime("validUntil")
}

class Foo(id: EntityID<Int>) : IntEntity(id) {
    companion object : IntEntityClass<Foo>(Foos)

    var validFrom by Foos.validFrom
    var validUntil by Foos.validUntil
}
```
This results into a `IllegalStateException`: `Unexpected value: Foos.validFrom of org.jetbrains.exposed.sql.Column`.

Sample Project: https://github.com/hfhbd/ExposedBetweenBug

# Stacktrace

```
Unexpected value: Foos.validFrom of org.jetbrains.exposed.sql.Column
java.lang.IllegalStateException: Unexpected value: Foos.validFrom of org.jetbrains.exposed.sql.Column
	at org.jetbrains.exposed.sql.java-time.JavaLocalDateTimeColumnType.nonNullValueToString(JavaDateColumnType.kt:89)
	at org.jetbrains.exposed.sql.IColumnType$DefaultImpls.valueToString(ColumnType.kt:53)
	at org.jetbrains.exposed.sql.ColumnType.valueToString(ColumnType.kt:71)
	at org.jetbrains.exposed.sql.QueryBuilder$registerArguments$1.invoke(Expression.kt:72)
	at org.jetbrains.exposed.sql.QueryBuilder.registerArguments(Expression.kt:75)
	at org.jetbrains.exposed.sql.QueryBuilder.registerArgument(Expression.kt:66)
	at org.jetbrains.exposed.sql.QueryParameter$toQueryBuilder$1.invoke(Op.kt:496)
	at org.jetbrains.exposed.sql.QueryParameter$toQueryBuilder$1.invoke(Op.kt:490)
	at org.jetbrains.exposed.sql.QueryBuilder.invoke(Expression.kt:18)
	at org.jetbrains.exposed.sql.QueryParameter.toQueryBuilder(Op.kt:496)
	at org.jetbrains.exposed.sql.QueryBuilder.append(Expression.kt:43)
	at org.jetbrains.exposed.sql.ExpressionKt.append(Expression.kt:96)
	at org.jetbrains.exposed.sql.Between$toQueryBuilder$1.invoke(Op.kt:178)
	at org.jetbrains.exposed.sql.Between$toQueryBuilder$1.invoke(Op.kt:170)
	at org.jetbrains.exposed.sql.QueryBuilder.invoke(Expression.kt:18)
	at org.jetbrains.exposed.sql.Between.toQueryBuilder(Op.kt:178)
	at org.jetbrains.exposed.sql.QueryBuilder.append(Expression.kt:43)
	at org.jetbrains.exposed.sql.QueryBuilder.unaryPlus(Expression.kt:53)
	at org.jetbrains.exposed.sql.Query$prepareSQL$1.invoke(Query.kt:107)
	at org.jetbrains.exposed.sql.Query$prepareSQL$1.invoke(Query.kt:15)
	at org.jetbrains.exposed.sql.QueryBuilder.invoke(Expression.kt:18)
	at org.jetbrains.exposed.sql.Query.prepareSQL(Query.kt:90)
	at org.jetbrains.exposed.sql.Query.arguments(Query.kt:83)
	at org.jetbrains.exposed.sql.Query.arguments(Query.kt:15)
	at org.jetbrains.exposed.sql.statements.Statement.executeIn$exposed_core(Statement.kt:32)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:129)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:115)
	at org.jetbrains.exposed.sql.Query.iterator(Query.kt:218)
	at org.jetbrains.exposed.sql.IterableExKt$mapLazy$1.iterator(IterableEx.kt:129)
	at kotlin.collections.CollectionsKt___CollectionsKt.toCollection(_Collections.kt:1243)
	at kotlin.collections.CollectionsKt___CollectionsKt.toMutableList(_Collections.kt:1276)
	at kotlin.collections.CollectionsKt___CollectionsKt.toList(_Collections.kt:1267)
	at BetweenTest$testBetween$1.invoke(BetweenTest.kt:25)
	at BetweenTest$testBetween$1.invoke(BetweenTest.kt:9)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$inTopLevelTransaction$1.invoke(ThreadLocalTransactionManager.kt:170)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$inTopLevelTransaction$2.invoke(ThreadLocalTransactionManager.kt:211)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:219)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction(ThreadLocalTransactionManager.kt:210)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$transaction$1.invoke(ThreadLocalTransactionManager.kt:148)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:219)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:120)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:118)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction$default(ThreadLocalTransactionManager.kt:117)
	at BetweenTest.testBetween(BetweenTest.kt:13)
```
# Versions #
exposed("core") with 0.28.1
exposed("dao") with 0.28.1
exposed("jdbc") with 0.28.1
exposed("java-time") with 0.28.1
Kotlin: 1.4.10
H2: 1.4.200
JDK: 14

**Comment by bog-walk** [comment]
@hfhbd The exception is being thrown because the extension function `between()` accepts only `LocalDateTime` values when called on `CurrentDateTime`. If you need to provide `Column<LocalDateTime>` instead as arguments, you can use the class `Between`, which accepts any `Expression<*>`:
```kt
Foo.find { 
    Between(CurrentDateTime, Foos.validFrom, Foos.validUntil) 
}
```
This is actually what `between()` does internally, by wrapping `LocalDateTime` values.

**Comment by bog-walk** [comment]
Please reopen this issue if the problem requires more answers.
