### ISSUE TITLE
Connection Leak with HikariCP + DAO updates

### ISSUE THREAD

**Issue by MrPowerGamerBR** [JetBrains/Exposed#1105]
If a DAO updates and a "could not serialize access due to concurrent update" happens, a connection is leaked.

This only happens when using `TRANSACTION_REPEATABLE_READ` because we want to force the exception to happen.

```kotlin
fun main() {
    val hikariConfig = HikariConfig()
    hikariConfig.jdbcUrl = "jdbc:postgresql://127.0.0.1:5432/teste"
    hikariConfig.username = "postgres"
    hikariConfig.password = "postgres"
    hikariConfig.maximumPoolSize = 8
    // Exposed does not use auto commit
    hikariConfig.isAutoCommit = false
    hikariConfig.transactionIsolation = "TRANSACTION_REPEATABLE_READ"

    hikariConfig.leakDetectionThreshold = 7500

    val ds = HikariDataSource(hikariConfig)
    val database = Database.connect(ds)

    TransactionManager.manager.defaultIsolationLevel = Connection.TRANSACTION_REPEATABLE_READ

    transaction {
        SchemaUtils.createMissingTablesAndColumns(
                TestProfiles
        )
    }

    val profile = transaction {
        TestProfile.findById(1L) ?: TestProfile.new(1L) {
            xp = 0L
        }
    }


    thread {
        runBlocking {
            newSuspendedTransaction {
                profile.xp += 5
            }
            println("Plus 5 XP: Done")
        }
    }

    thread {
        runBlocking {
            newSuspendedTransaction {
                profile.xp += 15
            }
            println("Plus 15 XP: Done")
        }
    }

    thread {
        while(true) {
            Thread.sleep(Long.MAX_VALUE)
        }
    }
}

object TestProfiles : LongIdTable() {
    val xp = long("xp").index()
}

class TestProfile(id: EntityID<Long>) : Entity<Long>(id) {
    companion object : EntityClass<Long, TestProfile>(TestProfiles) {
        private val logger = KotlinLogging.logger {}
    }

    var xp by TestProfiles.xp
}
```

Output:
```
Exception in thread "Thread-2" org.jetbrains.exposed.exceptions.ExposedSQLException: org.postgresql.util.PSQLException: ERROR: could not serialize access due to concurrent update
SQL: [UPDATE TestProfiles SET xp=? WHERE id = ?]
	at org.jetbrains.exposed.sql.statements.Statement.executeIn$exposed_core(Statement.kt:63)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:129)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:115)
	at org.jetbrains.exposed.sql.statements.Statement.execute(Statement.kt:29)
	at org.jetbrains.exposed.dao.EntityBatchUpdate.execute(EntityBatchUpdate.kt:33)
	at org.jetbrains.exposed.dao.EntityCache.updateEntities(EntityCache.kt:63)
	at org.jetbrains.exposed.dao.EntityCache.flush(EntityCache.kt:84)
	at org.jetbrains.exposed.dao.EntityCache.flush(EntityCache.kt:49)
	at org.jetbrains.exposed.dao.EntityCacheKt.flushCache(EntityCache.kt:154)
	at org.jetbrains.exposed.dao.EntityLifecycleInterceptor.beforeCommit(EntityLifecycleInterceptor.kt:40)
	at org.jetbrains.exposed.sql.Transaction.commit(Transaction.kt:63)
	at org.jetbrains.exposed.sql.transactions.experimental.SuspendedKt.commitInAsync(Suspended.kt:74)
	at org.jetbrains.exposed.sql.transactions.experimental.SuspendedKt.access$commitInAsync(Suspended.kt:1)
	at org.jetbrains.exposed.sql.transactions.experimental.SuspendedKt$suspendedTransactionAsyncInternal$1.invokeSuspend(Suspended.kt:131)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:84)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at com.mrpowergamerbr.loritta.TestCodeKt$main$2.invoke(TestCode.kt:50)
	at com.mrpowergamerbr.loritta.TestCodeKt$main$2.invoke(TestCode.kt)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
Caused by: org.postgresql.util.PSQLException: ERROR: could not serialize access due to concurrent update
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2553)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2285)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:323)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:473)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:393)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:164)
	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:130)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
	at org.jetbrains.exposed.sql.statements.jdbc.JdbcPreparedStatementImpl.executeUpdate(JdbcPreparedStatementImpl.kt:23)
	at org.jetbrains.exposed.sql.statements.BatchUpdateStatement.executeInternal(BatchUpdateStatement.kt:41)
	at org.jetbrains.exposed.sql.statements.BatchUpdateStatement.executeInternal(BatchUpdateStatement.kt:12)
	at org.jetbrains.exposed.sql.statements.Statement.executeIn$exposed_core(Statement.kt:61)
	... 24 more
Caused by: org.postgresql.util.PSQLException: ERROR: could not serialize access due to concurrent update

21:53:38.450 [HikariPool-1 housekeeper] WARN com.zaxxer.hikari.pool.ProxyLeakTask - Connection leak detection triggered for org.postgresql.jdbc.PgConnection@74bbfba3 on thread Thread-2 @coroutine#3, stack trace follows
java.lang.Exception: Apparent connection leak detected
	at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:100)
	at org.jetbrains.exposed.sql.Database$Companion$connect$3.invoke(Database.kt:121)
	at org.jetbrains.exposed.sql.Database$Companion$connect$3.invoke(Database.kt:58)
	at org.jetbrains.exposed.sql.Database$Companion$doConnect$3.invoke(Database.kt:112)
	at org.jetbrains.exposed.sql.Database$Companion$doConnect$3.invoke(Database.kt:58)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManager$ThreadLocalTransaction$connectionLazy$1.invoke(ThreadLocalTransactionManager.kt:54)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManager$ThreadLocalTransaction$connectionLazy$1.invoke(ThreadLocalTransactionManager.kt:46)
	at kotlin.UnsafeLazyImpl.getValue(Lazy.kt:81)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManager$ThreadLocalTransaction.getConnection(ThreadLocalTransactionManager.kt:60)
	at org.jetbrains.exposed.sql.Transaction.getConnection(Transaction.kt)
	at org.jetbrains.exposed.sql.statements.Statement.prepared(Statement.kt:25)
	at org.jetbrains.exposed.sql.statements.Statement.executeIn$exposed_core(Statement.kt:48)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:129)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:115)
	at org.jetbrains.exposed.sql.Query.iterator(Query.kt:218)
	at org.jetbrains.exposed.sql.IterableExKt$mapLazy$1.iterator(IterableEx.kt:129)
	at kotlin.collections.CollectionsKt___CollectionsKt.firstOrNull(_Collections.kt:237)
	at org.jetbrains.exposed.dao.EntityClass.findById(EntityClass.kt:42)
	at org.jetbrains.exposed.dao.EntityClass.get(EntityClass.kt:20)
	at org.jetbrains.exposed.dao.EntityClass.invalidateEntityInCache$exposed_dao(EntityClass.kt:65)
	at org.jetbrains.exposed.dao.Entity.setValue(Entity.kt:111)
	at com.mrpowergamerbr.loritta.TestProfile.setXp(TestCode.kt)
	at com.mrpowergamerbr.loritta.TestCodeKt$main$2$1$1.invokeSuspend(TestCode.kt:52)
	at com.mrpowergamerbr.loritta.TestCodeKt$main$2$1$1.invoke(TestCode.kt)
	at org.jetbrains.exposed.sql.transactions.experimental.SuspendedKt$suspendedTransactionAsyncInternal$1.invokeSuspend(Suspended.kt:126)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:84)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at com.mrpowergamerbr.loritta.TestCodeKt$main$2.invoke(TestCode.kt:50)
	at com.mrpowergamerbr.loritta.TestCodeKt$main$2.invoke(TestCode.kt)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
21:53:59.983 [HikariPool-1 housekeeper] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Pool stats (total=8, active=1, idle=7, waiting=0)
```

And after that we can see from HikariCP's logs that the connection is never closed:
```
21:56:07.497 [HikariPool-1 housekeeper] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Pool stats (total=8, active=1, idle=7, waiting=0)
21:56:07.497 [HikariPool-1 housekeeper] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Fill pool skipped, pool is at sufficient level.
21:56:37.498 [HikariPool-1 housekeeper] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Pool stats (total=8, active=1, idle=7, waiting=0)
21:56:37.498 [HikariPool-1 housekeeper] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Fill pool skipped, pool is at sufficient level.
```

This does *not* happen with DSL updates
```kotlin
    thread {
        runBlocking {
            newSuspendedTransaction {
                TestProfiles.update({ TestProfiles.id eq 1L }) {
                    with(SqlExpressionBuilder) {
                        it.update(xp, xp + 5)
                    }
                }
            }

            println("Plus 5 XP: Done")
        }
    }

    thread {
        runBlocking {
            newSuspendedTransaction {
                TestProfiles.update({ TestProfiles.id eq 1L }) {
                    with(SqlExpressionBuilder) {
                        it.update(xp, xp + 15)
                    }
                }
            }
            println("Plus 15 XP: Done")
        }
    }
```

```
Exception in thread "Thread-2" org.jetbrains.exposed.exceptions.ExposedSQLException: org.postgresql.util.PSQLException: ERROR: could not serialize access due to concurrent update
SQL: [Failed on expanding args for UPDATE: org.jetbrains.exposed.sql.statements.UpdateStatement@7bda90c2]
	at org.jetbrains.exposed.sql.statements.Statement.executeIn$exposed_core(Statement.kt:63)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:129)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:115)
	at org.jetbrains.exposed.sql.statements.Statement.execute(Statement.kt:29)
	at org.jetbrains.exposed.sql.QueriesKt.update(Queries.kt:179)
	at org.jetbrains.exposed.sql.QueriesKt.update$default(Queries.kt:176)
	at com.mrpowergamerbr.loritta.TestCodeKt$main$2$1$1.invokeSuspend(TestCode.kt:54)
	at com.mrpowergamerbr.loritta.TestCodeKt$main$2$1$1.invoke(TestCode.kt)
	at org.jetbrains.exposed.sql.transactions.experimental.SuspendedKt$suspendedTransactionAsyncInternal$1.invokeSuspend(Suspended.kt:126)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:84)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at com.mrpowergamerbr.loritta.TestCodeKt$main$2.invoke(TestCode.kt:52)
	at com.mrpowergamerbr.loritta.TestCodeKt$main$2.invoke(TestCode.kt)
	at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
Caused by: org.postgresql.util.PSQLException: ERROR: could not serialize access due to concurrent update
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2553)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2285)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:323)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:473)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:393)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:164)
	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:130)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
	at org.jetbrains.exposed.sql.statements.jdbc.JdbcPreparedStatementImpl.executeUpdate(JdbcPreparedStatementImpl.kt:23)
	at org.jetbrains.exposed.sql.statements.UpdateStatement.executeInternal(UpdateStatement.kt:13)
	at org.jetbrains.exposed.sql.statements.UpdateStatement.executeInternal(UpdateStatement.kt:7)
	at org.jetbrains.exposed.sql.statements.Statement.executeIn$exposed_core(Statement.kt:61)
	... 19 more
Caused by: org.postgresql.util.PSQLException: ERROR: could not serialize access due to concurrent update

21:58:53.385 [HikariPool-1 housekeeper] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Pool stats (total=8, active=0, idle=8, waiting=0)
21:58:53.385 [HikariPool-1 housekeeper] DEBUG com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Fill pool skipped, pool is at sufficient level.
```

Using Exposed 0.28.1, hope this issue is fixed soon:tm: because this is affecting some of my production applications 😭

**Comment by MrPowerGamerBR** [comment]
Worth nothing: This seems to only happen with *suspended transactions*, normal transactions are unaffected.

**Comment by Tapac** [comment]
Should be fixed in master. Hope to release it next week,.
