### ISSUE TITLE
When using Literal with and operator between, results in org.postgresql.util.PSQLException

### ISSUE THREAD

**Issue by SchweinchenFuntik** [JetBrains/Exposed#1110]
<b>versions:</b>
- kotlin: 1.4.20
- exposed: 28.1
- Postgresql: 12.5-3
- JDBC Driver: org.postgresql:postgresql:42.2.16

<b>code: </b>
```kotlin
object LocationsTree : LongIdTable("location_tree") {
    val leftKey = long("left_key")
    val rightKey = long("right_key")
    val level = integer("level")
}


class LocationTree(id: EntityID<Long>) : LongEntity(id) {
    companion object : LongEntityClass<LocationTree>(LocationsTree)

    val leftKey by LocationsTree.leftKey
    val rightKey by LocationsTree.rightKey
    val level by LocationsTree.level

    fun parent(): LocationTree? {
        val op = Op.build { LocationsTree.id neq id.value }
            .and { LocationsTree.level eq (level - 1) }
            .and { longLiteral(id.value).between(LocationsTree.leftKey, LocationsTree.rightKey) }

        return LocationTree.find(op).firstOrNull()
    }
}

transaction {
    addLogger(StdOutSqlLogger)
    LocationTree[locationNodeId]
        .also(::println)
        .parent() // error
        ?.let(::println) 
}
```

<b>exception:</b>
```kotlin
org.postgresql.util.PSQLException: Can't infer the SQL type to use for an instance of org.jetbrains.exposed.sql.Column. Use setObject() with an explicit Types value to specify the type to use.
	at org.postgresql.jdbc.PgPreparedStatement.setObject(PgPreparedStatement.java:1006)
	at org.jetbrains.exposed.sql.statements.jdbc.JdbcPreparedStatementImpl.set(JdbcPreparedStatementImpl.kt:26)
	at org.jetbrains.exposed.sql.IColumnType$DefaultImpls.setParameter(ColumnType.kt:64)
	at org.jetbrains.exposed.sql.ColumnType.setParameter(ColumnType.kt:71)
        at org.jetbrains.exposed.sql.statements.api.PreparedStatementApi$DefaultImpls.fillParameters(PreparedStatementApi.kt:13)
	at org.jetbrains.exposed.sql.statements.jdbc.JdbcPreparedStatementImpl.fillParameters(JdbcPreparedStatementImpl.kt:9)
	at org.jetbrains.exposed.sql.statements.Statement.executeIn$exposed_core(Statement.kt:53)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:129)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:115)
	at org.jetbrains.exposed.sql.Query.iterator(Query.kt:218)
	at org.jetbrains.exposed.sql.IterableExKt$mapLazy$1.iterator(IterableEx.kt:129)
	at kotlin.collections.CollectionsKt___CollectionsKt.firstOrNull(_Collections.kt:237)
        // my 
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$inTopLevelTransaction$1.invoke(ThreadLocalTransactionManager.kt:170)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$inTopLevelTransaction$2.invoke(ThreadLocalTransactionManager.kt:211)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:219)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction(ThreadLocalTransactionManager.kt:210)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$transaction$1.invoke(ThreadLocalTransactionManager.kt:148)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:219)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:120)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:118)
        // call query
```

**Comment by SchweinchenFuntik** [comment]
work
```kotlin
fun parent(): LocationTree? {
    val op = Op.build { LocationsTree.id neq id.value }
        .and { LocationsTree.level eq (level - 1) }
        .and { Between(longParam(id.value), LocationsTree.leftKey, LocationsTree.rightKey) }

    return LocationTree.find(op).firstOrNull()
}
```

**Comment by bog-walk** [comment]
If I understand the entity set up correctly and reproduce the problem, this alternative also allows type inference without throwing an exception since `between()` is being provided with 2 `Long` arguments instead of 2 `Column<Long>`:
```kt
val op = Op.build { LocationsTree.id neq id }
    .and { LocationsTree.level eq (level - 1) }
    .and { LocationsTree.id.between(leftKey, rightKey) }
```

Please reopen this issue if the problem returns.
