### ISSUE TITLE
IllegalStateException: Property klass should be initialized before get.

### ISSUE THREAD

**Issue by ToxicMushroom** [JetBrains/Exposed#1154]
So I'm trying to find an entry with the query below but before getting the result I get an exception that has me confused.
In the current state, the query should return null as the table is empty, I tried recreating the database, changing fields around. changing the query etc.

This leads me to believe it is either am Exposed issue or I'm missing something.

Code
```kotlin
            try {
                val removeEntry = transaction {
                    RoleRemove.find {
                        RoleRemoves.userId
                            .eq(user.idLong)
                            .and(RoleRemoves.guildId eq guild.idLong)
                            .and(RoleRemoves.entityId eq guild.idLong)
                            .and(RoleRemoves.voteType eq Type.GUILD)
                    }.firstOrNull() // Line 107
                }
                if (removeEntry == null) {
                    transaction {// insert
                        RoleRemoves.insert {
                            it[this.id] = EntityID(SnowflakeUtil.generateId(), RoleRemoves)
                            it[this.guildId] = EntityID(guild.idLong, Guilds)
                            it[this.userId] = EntityID(user.idLong, Users)
                            it[this.entityId] = guild.idLong
                            it[this.voteType] = Type.GUILD
                            it[this.timestamp] = localtime
                        }
                    }
                } else { // update
                    transaction {
                        removeEntry.timestamp = localtime
                    }
                }
            } catch (t: Throwable) {
                t.printStackTrace()
            }
```

RoleRemove model
```kotlin
class RoleRemove(id: EntityID<Long>) : LongEntity(id) {
    companion object : LongEntityClass<RoleRemove>(RoleRemoves)

    val user by User referencedOn RoleRemoves.userId
    val guild by Guild referencedOn RoleRemoves.guildId

    var userId by RoleRemoves.userId
    var guildId by RoleRemoves.guildId

    val roleId = guild.voteRole

    // botId or guildId
    var entityId by RoleRemoves.entityId

    // guild or bot
    var voteType by RoleRemoves.voteType

    var timestamp by RoleRemoves.timestamp

}

object RoleRemoves : IdTable<Long>("role_remove") {
    override val id = long("id").entityId()

    val userId = reference("user_id", Users)
    val guildId = reference("guild_id", Guilds)
    val entityId = long("entity_id")
    val voteType = enumeration("vote_type", Type::class)
    val timestamp = datetime("timestamp")

    override val primaryKey = PrimaryKey(id)

    init {
        index("IDX_TIMESTAMP", false, timestamp)
        index("IDX_USER_VOTE", false, userId, guildId, entityId, voteType)
    }
}
```

Exception
```
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
	at kotlin.reflect.jvm.internal.calls.CallerImpl$Constructor.call(CallerImpl.kt:41)
	at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:108)
	at org.jetbrains.exposed.dao.EntityClass.createInstance(EntityClass.kt:202)
	at org.jetbrains.exposed.dao.EntityClass.wrap(EntityClass.kt:206)
	at org.jetbrains.exposed.dao.EntityClass.wrapRow(EntityClass.kt:113)
	at org.jetbrains.exposed.dao.EntityClass$wrapRows$1.invoke(EntityClass.kt:100)
	at org.jetbrains.exposed.dao.EntityClass$wrapRows$1.invoke(EntityClass.kt:16)
	at org.jetbrains.exposed.sql.IterableExKt$mapLazy$1$iterator$1.next(IterableEx.kt:131)
	at kotlin.collections.CollectionsKt___CollectionsKt.firstOrNull(_Collections.kt:240)
	at dev.xavin.manager.GuildRewardsManager$applyServerReward$removeEntry$1.invoke(GuildRewardsManager.kt:107)
	at dev.xavin.manager.GuildRewardsManager$applyServerReward$removeEntry$1.invoke(GuildRewardsManager.kt:27)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$inTopLevelTransaction$1.invoke(ThreadLocalTransactionManager.kt:170)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$inTopLevelTransaction$2.invoke(ThreadLocalTransactionManager.kt:211)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:219)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction(ThreadLocalTransactionManager.kt:210)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$transaction$1.invoke(ThreadLocalTransactionManager.kt:148)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:219)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:120)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:118)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction$default(ThreadLocalTransactionManager.kt:117)
	at dev.xavin.manager.GuildRewardsManager.applyServerReward(GuildRewardsManager.kt:100)
	at dev.xavin.manager.GuildRewardsManager.serverRewardLog$suspendImpl(GuildRewardsManager.kt:72)
	at dev.xavin.manager.GuildRewardsManager$serverRewardLog$1.invokeSuspend(GuildRewardsManager.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedContinuation.resumeWith(DispatchedContinuation.kt:188)
	at kotlin.coroutines.SafeContinuation.resumeWith(SafeContinuationJvm.kt:42)
	at dev.xavin.util.JDAUtilKt$awaitOrNull$4$1.accept(JDAUtil.kt:277)
	at net.dv8tion.jda.api.requests.Request.lambda$onSuccess$0(Request.java:95)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1425)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Caused by: java.lang.IllegalStateException: Property klass should be initialized before get.
	at kotlin.properties.NotNullVar.getValue(Delegates.kt:62)
	at org.jetbrains.exposed.dao.Entity.getKlass(Entity.kt)
	at org.jetbrains.exposed.dao.Entity.getReadValues(Entity.kt:24)
	at org.jetbrains.exposed.dao.Entity.lookup(Entity.kt:107)
	at org.jetbrains.exposed.dao.Entity.getValue(Entity.kt:88)
	at org.jetbrains.exposed.dao.Entity.getValue(Entity.kt:58)
	at dev.xavin.model.database.RoleRemove.getGuild(RoleRemove.kt)
	at dev.xavin.model.database.RoleRemove.<init>(RoleRemove.kt:20)
	... 39 more```

**Comment by jnfeinstein** [comment]
I believe the error comes from this line: `val roleId = guild.voteRole` since you have `at dev.xavin.model.database.RoleRemove.getGuild(RoleRemove.kt)` in your trace.  You probably want `val roleId: VoteRole get() = guild.voteRole`.  This is triggering an exception because you are trying to load the association before the initializer, which includes a bunch of Exposed internal machinery, has completed.

**Comment by ToxicMushroom** [comment]
Thanks @jnfeinstein, that was the issue <3

**Comment by pkucharek** [comment]
Hi, I think it is worth to mention for future readers looking for solution to problem `IllegalStateException: Property klass should be initialized before get`, that sometimes the cause is incorrect mapping `ResultRow`.
With such query:
```kotlin
val query: Query = Groups
    .innerJoin(Users)
    .innerJoin(Members)
    .slice(Groups.columns)
    .selectAll()
    .withDistinct()
```

This:
```kotlin
val groups: List<Group> = query.map { rs ->
    val group = Group(rs[Groups.id])
    group.name = rs[Groups.name]
    group.owner = User(rs[Groups.owner])
    group.description = rs[Groups.description]
    group
}
```

Should be replaced to this:
```kotlin
val groups: List<Group> = query.map { rs ->
    Group.wrapRow(rs)
}
```

[Source](https://www.youtube.com/watch?v=O4u80a2Qh_k), chapter **From SQL DSL to DAO entities**.
