### ISSUE TITLE
How to run tests?

### ISSUE THREAD

**Issue by nallwhy** [JetBrains/Exposed#1158]
When I run `gradle test` or `gradle exposed-tests:test`, error belows are occurred.

```
org.testcontainers.containers.ContainerLaunchException: Container startup failed
        at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:330)
        at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:311)
        at org.jetbrains.exposed.sql.tests.DatabaseTestsBaseKt$mySQLProcess$2.invoke(DatabaseTestsBase.kt:100)
        at org.jetbrains.exposed.sql.tests.DatabaseTestsBaseKt$mySQLProcess$2.invoke(DatabaseTestsBase.kt)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at org.jetbrains.exposed.sql.tests.DatabaseTestsBaseKt.getMySQLProcess(DatabaseTestsBase.kt)
        at org.jetbrains.exposed.sql.tests.DatabaseTestsBaseKt.access$getMySQLProcess$p(DatabaseTestsBase.kt:1)
        at org.jetbrains.exposed.sql.tests.TestDB$8.invoke(DatabaseTestsBase.kt:35)
        at org.jetbrains.exposed.sql.tests.TestDB$8.invoke(DatabaseTestsBase.kt:20)
        at org.jetbrains.exposed.sql.tests.DatabaseTestsBase.withDb(DatabaseTestsBase.kt:118)
        at org.jetbrains.exposed.sql.tests.DatabaseTestsBase.withTables(DatabaseTestsBase.kt:148)
        at org.jetbrains.exposed.sql.tests.DatabaseTestsBase.withTables(DatabaseTestsBase.kt:177)
        at org.jetbrains.exposed.DefaultsTest.testDefaultsWithExplicit01(DefaultsTest.kt:51)

        Caused by:
        org.testcontainers.containers.ContainerFetchException: Can't get Docker image: RemoteDockerImage(imageName=mysql:5, imagePullPolicy=DefaultPullPolicy())
            at org.testcontainers.containers.GenericContainer.getDockerImageName(GenericContainer.java:1279)
            at org.testcontainers.containers.GenericContainer.logger(GenericContainer.java:613)
            at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:320)
            ... 12 more

            Caused by:
            com.github.dockerjava.api.exception.NotFoundException: {"message":"No such image: testcontainersofficial/ryuk:0.3.0"}
                at com.github.dockerjava.okhttp.OkHttpInvocationBuilder.execute(OkHttpInvocationBuilder.java:287)
                at com.github.dockerjava.okhttp.OkHttpInvocationBuilder.execute(OkHttpInvocationBuilder.java:271)
                at com.github.dockerjava.okhttp.OkHttpInvocationBuilder.post(OkHttpInvocationBuilder.java:129)
                at com.github.dockerjava.core.exec.CreateContainerCmdExec.execute(CreateContainerCmdExec.java:33)
                at com.github.dockerjava.core.exec.CreateContainerCmdExec.execute(CreateContainerCmdExec.java:13)
                at com.github.dockerjava.core.exec.AbstrSyncDockerCmdExec.exec(AbstrSyncDockerCmdExec.java:21)
                at com.github.dockerjava.core.command.AbstrDockerCmd.exec(AbstrDockerCmd.java:35)
                at com.github.dockerjava.core.command.CreateContainerCmdImpl.exec(CreateContainerCmdImpl.java:595)
                at org.testcontainers.utility.ResourceReaper.start(ResourceReaper.java:94)
                at org.testcontainers.DockerClientFactory.client(DockerClientFactory.java:168)
                at org.testcontainers.LazyDockerClient.getDockerClient(LazyDockerClient.java:14)
                at org.testcontainers.LazyDockerClient.listImagesCmd(LazyDockerClient.java:12)
                at org.testcontainers.images.LocalImagesCache.maybeInitCache(LocalImagesCache.java:68)
                at org.testcontainers.images.LocalImagesCache.get(LocalImagesCache.java:32)
                at org.testcontainers.images.AbstractImagePullPolicy.shouldPull(AbstractImagePullPolicy.java:18)
                at org.testcontainers.images.RemoteDockerImage.resolve(RemoteDockerImage.java:59)
                at org.testcontainers.images.RemoteDockerImage.resolve(RemoteDockerImage.java:26)
                at org.testcontainers.utility.LazyFuture.getResolvedValue(LazyFuture.java:20)
                at org.testcontainers.utility.LazyFuture.get(LazyFuture.java:27)
                at org.testcontainers.containers.GenericContainer.getDockerImageName(GenericContainer.java:1277)
                ... 14 more
```

I already pulled all docker images that are contained in `buildScript/docker/docker-compose-*.yml`.

**Comment by Tapac** [comment]
Any other exception or `Cause by` of that exception?

**Comment by nallwhy** [comment]
> Any other exception or `Cause by` of that exception?

Oh, sorry. I've added more error messages.

**Comment by Tapac** [comment]
I guess [that issue](https://github.com/testcontainers/testcontainers-java/issues/3574) can have some clues.

**Comment by nallwhy** [comment]
Thanks. Upgrading `org.testcontainers.*` to  `1.15.1` works.
