### ISSUE TITLE
PostgreSQL. Cannot build OP with string more than 255 characters

### ISSUE THREAD

**Issue by good-news-everyone** [JetBrains/Exposed#1181]
Kotlin version: `1.4.30`
Exposed version: `0.29.1`

Description: In my database I got table with column with type `text`. When I try to insert quite long text, it works fine. But when I try to compare this column to quite long text (more than 255 characters), I get following Exception:

```
Value 'stlnpazqforpqcifmbbdoixrlsxmaqtblzfmbiecwjuevprccshwfbrfoibmedxqzatobgfnzksrvkadyuuxjlnlqecfirrrbhvjniluitdquecponkiukweglcyycwqcyoauvvmaphhphdbvhoczissrdofaniberkllgvwokbyhygxzehoykjsioruwzyhwvloyqazbyodsfdcomtdqiilzuvkzfdreqkgemdxqqcxjpkgsqqnkhwlpuchpatexhetucqaiwjlggnkhwvpueprtcmcneqlvhbrazrxkhcrmqizuageyozwgicroqbyzthbabnauwaqlctffqqymkusccxasljafyjhgoxtbsjrumfrmwehmcmmdkhhqiycnecnoupyhcnfzpxgyfvoizrlefowzajcccmfiziafuygmvhtyrxwyuqbtezezhrttwfmicwqktxejjjircsgwaovqlsywieydweqghrxzldjikbcrwstoikkjpramkgptkhrmvpfyeyqbgnglphaxqeraqcehouvhncqrxohwsyswcpcaaecoziqojlypzjrzzytmtagkbwkfzyzfdttvsgabmyyofxnazkcloasriukkscyiannzcpuxsabhfxytiashidswxwxxaabnvslmaiefshzjenjphkvehmhawckfbzdtokpoimprmrxclasmbilisrfanabakdvvfekgvzausspjvnqtofdqgqnnaelpfndwhlcatdpkjpbalgkmxwnsbqomkkbqkuydyrlfsuxwtrbieemwullppqselyimnsjwsatbgifaakrnsfrlpjuriqcklqkfyhznmlyqdxhvgzjoytiggkeosyjpcydqamrxtcmoqsggpgdlplyoielurrbiqgkclyhdfxzvvnzyfbsibwzubkehsyxbrfvdutrwzjifzjfuttfdzwrrpwnnvpmfwvsnyrwuhpqgtzudvansfioecqcdxrogtwuyjjhavvlhtdnoibhbvn' can't be stored to database column because exceeds length (255)
	at org.jetbrains.exposed.sql.VarCharColumnType.notNullValueToDB(ColumnType.kt:541)
	at org.jetbrains.exposed.sql.IColumnType$DefaultImpls.valueToDB(ColumnType.kt:37)
	at org.jetbrains.exposed.sql.ColumnType.valueToDB(ColumnType.kt:71)
	at org.jetbrains.exposed.sql.statements.api.PreparedStatementApi$DefaultImpls.fillParameters(PreparedStatementApi.kt:13)
	at org.jetbrains.exposed.sql.statements.jdbc.JdbcPreparedStatementImpl.fillParameters(JdbcPreparedStatementImpl.kt:9)
	at org.jetbrains.exposed.sql.statements.Statement.executeIn$exposed_core(Statement.kt:53)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:129)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:115)
	at org.jetbrains.exposed.sql.Query.empty(Query.kt:266)
	at org.jetbrains.exposed.sql.IterableExKt$mapLazy$1.empty(IterableEx.kt:124)
...
```

Code, that executing is:
```
transaction { 
    MyDao.find { MyTable.textColumn.lowerCase().eq(someLongString) }.empty().not()
}
```

I manage to find a workaround - cast this long strings to text explicitly with simple class:
```
class CastToTextFunction(val text: String) : Function<String>(TextColumnType()) {
    override fun toQueryBuilder(queryBuilder: QueryBuilder) {
        queryBuilder {
            registerArgument(TextColumnType(), text)
            append("::TEXT")
        }
    }
}

....

// now working
transaction { 
    MyDao.find { MyTable.textColumn.eq(CastToTextFunction(someLongString)) }.empty().not()
}
```
Looks like that requirement in org.jetbrains.exposed.sql.VarCharColumnType.notNullValueToDB not neccesary in this case

**Comment by Tapac** [comment]
Is `MyTable.textColumn` of `text` or `varchar` type?

**Comment by good-news-everyone** [comment]
> Is `MyTable.textColumn` of `text` or `varchar` type?
Yes, it is `text` type
I think it is happining because of `lowerCase()` function - it returns `LowerCase` object, that extends `Function<T>(VarCharColumnType())`
```
class LowerCase<T : String?>(
    /** Returns the expression to convert. */
    val expr: Expression<T>
) : Function<T>(VarCharColumnType()) {
    override fun toQueryBuilder(queryBuilder: QueryBuilder): Unit = queryBuilder { append("LOWER(", expr, ")") }
}
```
