### ISSUE TITLE
Cannot get the examples to work

### ISSUE THREAD

**Issue by kaphula** [JetBrains/Exposed#1195]
Hello,

I am getting exceptions when I try to run the Exposed examples. I followed the getting started instructions for setting up my Gradle project. I have also set up a local postgresql database on my computer and the database service is up and running (Arch Linux). I really have no clue what is up with the runtime errors. I also had to include the slf4 dependencies manually, which were not listed in the official examples, to get rid of another runtime exception that occurs without them.

gradle.properties:
```
kotlin.code.style=official
exposedVersion=0.29.1
```

build.gradle.kts:
```
plugins {
    java
    kotlin("jvm") version "1.4.31"
}

group = "org.example"
version = "1.0-SNAPSHOT"

val exposedVersion: String by project
repositories {
    mavenCentral()
    jcenter()
}

dependencies {
    implementation("org.jetbrains.exposed:exposed-core:$exposedVersion")
    implementation("org.jetbrains.exposed:exposed-dao:$exposedVersion")
    implementation("org.jetbrains.exposed:exposed-jdbc:$exposedVersion")

    compile("org.slf4j:slf4j-api:1.7.25")
    compile("org.slf4j:slf4j-simple:1.7.25")

    //Gradle
    compile("org.postgresql:postgresql:42.2.2")

    implementation(kotlin("stdlib"))
    testCompile("junit", "junit", "4.12")
}

```
Example code:
```
import org.jetbrains.exposed.sql.*
import org.jetbrains.exposed.sql.transactions.transaction

object Users : Table() {
    val id = varchar("id", 10) // Column<String>
    val name = varchar("name", length = 50) // Column<String>
    val cityId = (integer("city_id") references Cities.id).nullable() // Column<Int?>

    override val primaryKey = PrimaryKey(id, name = "PK_User_ID") // name is optional here
}

object Cities : Table() {
    val id = integer("id").autoIncrement() // Column<Int>
    val name = varchar("name", 50) // Column<String>

    override val primaryKey = PrimaryKey(id, name = "PK_Cities_ID")
}

fun main(args: Array<String>) {
    val db = Database.connect("jdbc:postgresql://localhost:5432/postgres", driver = "org.postgresql.Driver",
        user = "postgres", password = "mypassword")

    transaction {
        addLogger(StdOutSqlLogger)

        SchemaUtils.create(Cities, Users)
    }
}


```
The exception:
```
Exception in thread "main" java.lang.ExceptionInInitializerError
	at SQLKt$main$1.invoke(SQL.kt:26)
	at SQLKt$main$1.invoke(SQL.kt)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$inTopLevelTransaction$1.invoke(ThreadLocalTransactionManager.kt:170)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$inTopLevelTransaction$2.invoke(ThreadLocalTransactionManager.kt:191)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:199)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction(ThreadLocalTransactionManager.kt:190)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$transaction$1.invoke(ThreadLocalTransactionManager.kt:148)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:199)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:120)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:118)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction$default(ThreadLocalTransactionManager.kt:117)
	at SQLKt.main(SQL.kt:23)
Caused by: java.lang.NullPointerException: javaClass.`package` must not be null
	at org.jetbrains.exposed.sql.Table.<init>(Table.kt:314)
	at org.jetbrains.exposed.sql.Table.<init>(Table.kt:311)
	at Cities.<init>(SQL.kt:12)
	at Cities.<clinit>(SQL.kt:12)
	... 12 more

Process finished with exit code 1
```

**Comment by Tapac** [comment]
Please try to move your code into file under some package.

**Comment by kaphula** [comment]
I made a repository that shows the current project structure [here](https://github.com/kaphula/ExposedSampleProject2). I added the package "school" as you suggested but I still get the same error. If you care to take a look, do you spot something wrong with this project configuration? 

If similar simple example projects where Exposed is configured with Gradle exist, I'd gladly take a look at them.

**Comment by Tapac** [comment]
Fixed in master. Definition of tables in files without a package supported.
