### ISSUE TITLE
SQLite count() cause `No transaction in context`

### ISSUE THREAD

**Issue by gtf35** [JetBrains/Exposed#1210]
SQLite count() cause `No transaction in context`

<details>
  <summary>My code</summary>

  ```
import com.zaxxer.hikari.HikariConfig
import com.zaxxer.hikari.HikariDataSource
import org.jetbrains.exposed.sql.*
import org.jetbrains.exposed.sql.Database
import org.jetbrains.exposed.sql.transactions.TransactionManager
import org.jetbrains.exposed.sql.transactions.transaction
import top.nekoproject.common.logger
import top.nekoproject.database.UsersTable
import java.io.File
import java.sql.Connection

object Database {
    private val dbPath: String

    init {
        val dbFile = File("/data/db/database.db")
        if (!dbFile.exists()) dbFile.parentFile.mkdirs()
        dbPath = dbFile.canonicalPath
        logger.debug { "SQLite database file is at $dbPath" }
    }

    private fun loadDB() {
        val config = HikariConfig().apply {
            jdbcUrl         = "jdbc:sqlite:$dbPath"
            driverClassName = "org.sqlite.JDBC"
            maximumPoolSize = 10
        }
        val dataSource = HikariDataSource(config)
        Database.connect(dataSource)
        TransactionManager.manager.defaultIsolationLevel = Connection.TRANSACTION_SERIALIZABLE
    }

    fun initDB() {
        loadDB()

        transaction {
            addLogger(StdOutSqlLogger)

            SchemaUtils.create(UsersTable)
        }
    }

    // call this will cause error
    fun isEmailAlreadyRegister(email: String): Boolean {
        return UsersTable.select {
            UsersTable.email like email
        }.count() != 0L
    }

}

```

Table:

```
import org.jetbrains.exposed.sql.Table

object UsersTable : Table()  {
    val id = integer("id").autoIncrement()
    val nick = varchar("nick", 10)
    // email can't same, so add uniqueIndex()
    val email = varchar("email", 50).uniqueIndex()
    val pwdHash = varchar("pwd_hash", 32)

    override val primaryKey = PrimaryKey(id)
}
```

Error:

```
java.lang.IllegalStateException: No transaction in context.
	at org.jetbrains.exposed.sql.transactions.TransactionManager$Companion.current(TransactionApi.kt:108)
	at org.jetbrains.exposed.sql.AbstractQuery.getTransaction(AbstractQuery.kt:9)
	at org.jetbrains.exposed.sql.Query.count(Query.kt:177)
	at top.nekoproject.database.Database.isEmailAlreadyRegister(Database.kt:51)
	at top.nekoproject.register.RegisterRoutesKt$registerRouting$2.invokeSuspend(RegisterRoutes.kt:34)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:188)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:144)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:15)
	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:90)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.ktor.server.netty.EventLoopGroupProxy$Companion$create$factory$1$1.run(NettyApplicationEngine.kt:227)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:832)
```

</details>

Thanks a lot :)

**Comment by gtf35** [comment]
It is my wrong, I should operate the database in `transaction` code block :

```
    fun isEmailAlreadyRegister(email: String): Boolean {
        return transaction {
            UsersTable.select {
                UsersTable.email like email
            }.count() != 0L
        }
    }
    ```
