### ISSUE TITLE
IllegalArgumentException: "id not in record set" for IdTable

### ISSUE THREAD

**Issue by paulschuetz** [JetBrains/Exposed#1217]
Hello together :smiley: 
I have the following table and dao definitions:

```
object Offboardings : IdTable<Int>("offboardings") {
    val offboardingId = integer("offboardingId").uniqueIndex()
    val offboardingDate = date("offboardingDate")
    // UUID consisting of 36 characters
    val employeeId = varchar("employeeId", 36)
    val assigneeId = varchar("assigneeId", 36)

    override val primaryKey = PrimaryKey(offboardingId)
    override val id: Column<EntityID<Int>> = offboardingId.entityId()
    init {
        uniqueIndex(employeeId, offboardingDate)
    }
}

class OffboardingDao(id: EntityID<Int>) : Entity<Int>(id) {
    companion object : EntityClass<Int, OffboardingDao>(Offboardings)

    var offboardingId by Offboardings.offboardingId
    var offboardingDate by Offboardings.offboardingDate
    var employeeId by Offboardings.employeeId
    var assigneeId by Offboardings.assigneeId
}
```

Where the `offboardingId` column is the primary key which I intend to set manually, rather than being automatically incremented by the database, which is why I avoid `IntIdTable`. The table gets created perfectely fine, see image below.

```
                       Table "public.offboardings"
     Column      |         Type          | Collation | Nullable | Default 
-----------------+-----------------------+-----------+----------+---------
 offboardingDate | date                  |           | not null | 
 employeeId      | character varying(36) |           | not null | 
 assigneeId      | character varying(36) |           | not null | 
 offboardingId   | integer               |           | not null | 
Indexes:
    "pk_offboardings" PRIMARY KEY, btree ("offboardingId")
    "offboardings_employeeid_offboardingdate_unique" UNIQUE CONSTRAINT, btree ("employeeId", "offboardingDate")
    "offboardings_offboardingid_unique" UNIQUE CONSTRAINT, btree ("offboardingId")

```

But unfortunately when I try to create a new instance with the DAO interface, the following exception occurs.

```
transaction {
  OffboardingDao.new {
                      offboardingId = 1
                      employeeId = UUID.randomUUID().toString()
                      assigneeId = UUID.randomUUID().toString()
                      offboardingDate = LocalDate.now()
                  }
}
```
Stacktrace: 
```
Caused by: java.lang.IllegalStateException: de.jarvis.config.Offboardings.offboardingId is not in record set
	at org.jetbrains.exposed.sql.ResultRow.set(ResultRow.kt:35)
	at org.jetbrains.exposed.dao.Entity.storeWrittenValues(Entity.kt:195)
	at org.jetbrains.exposed.dao.EntityCache.flushInserts$exposed_dao(EntityCache.kt:136)
	at org.jetbrains.exposed.dao.EntityCache.flush(EntityCache.kt:80)
	at org.jetbrains.exposed.dao.EntityCache.flush(EntityCache.kt:49)
	at org.jetbrains.exposed.dao.EntityCacheKt.flushCache(EntityCache.kt:162)
	at org.jetbrains.exposed.dao.EntityLifecycleInterceptor.beforeCommit(EntityLifecycleInterceptor.kt:40)
	at org.jetbrains.exposed.sql.Transaction.commit(Transaction.kt:63)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$inTopLevelTransaction$1.invoke(ThreadLocalTransactionManager.kt:171)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$inTopLevelTransaction$2.invoke(ThreadLocalTransactionManager.kt:191)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:199)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction(ThreadLocalTransactionManager.kt:190)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$transaction$1.invoke(ThreadLocalTransactionManager.kt:148)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:199)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:120)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:118)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction$default(ThreadLocalTransactionManager.kt:117)
	at de.jarvis.config.DataSourceConfig.initDatabase(DataSourceConfig.kt:56)
```

There seems to be something wrong with the wiring of the DAO, as the DSL API works perfectely fine.

```
// this works
Offboardings.insert {
                    it[employeeId] = UUID.randomUUID().toString()
                    it[offboardingDate] = LocalDate.now()
                    it[assigneeId] = UUID.randomUUID().toString()
                    it[offboardingId] = 1
                }
```

I am running the latest version of Exposed which currently is 0.30.2. I also have to mention that the documentation is really not very helpful in this case. I hope you can support me with this issue! Thanks :smiley:

**Comment by Tapac** [comment]
@paulschuetz , can you please verify your code with the latest (0.35.1) release as an issue with similar exception was fixed not so long time ago.
