### ISSUE TITLE
Unsupporter Driver SQLite JDBC detected

### ISSUE THREAD

**Issue by uinnn** [JetBrains/Exposed#1218]
`java.lang.IllegalStateException: Unsupported driver SQLiteJDBC detected
        at org.jetbrains.exposed.sql.statements.jdbc.JdbcDatabaseMetadataImpl$databaseDialectName$2.invoke(JdbcDatabaseMetadataImpl.kt:33) ~[?:?]
        at org.jetbrains.exposed.sql.statements.jdbc.JdbcDatabaseMetadataImpl$databaseDialectName$2.invoke(JdbcDatabaseMetadataImpl.kt:13) ~[?:?]
        at org.jetbrains.exposed.sql.statements.jdbc.JdbcDatabaseMetadataImpl$lazyMetadata$1.invoke(JdbcDatabaseMetadataImpl.kt:214) ~[?:?]
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74) ~[?:?]
        at org.jetbrains.exposed.sql.statements.jdbc.JdbcDatabaseMetadataImpl.getDatabaseDialectName(JdbcDatabaseMetadataImpl.kt) ~[?:?]
        at org.jetbrains.exposed.sql.Database$vendor$2$1.invoke(Database.kt:34) ~[?:?]
        at org.jetbrains.exposed.sql.Database$vendor$2$1.invoke(Database.kt:15) ~[?:?]
        at org.jetbrains.exposed.sql.statements.jdbc.JdbcConnectionImpl.metadata(JdbcConnectionImpl.kt:51) ~[?:?]
        at org.jetbrains.exposed.sql.Database.metadata$exposed_core(Database.kt:29) ~[?:?]
        at org.jetbrains.exposed.sql.Database$vendor$2.invoke(Database.kt:34) ~[?:?]
        at org.jetbrains.exposed.sql.Database$vendor$2.invoke(Database.kt:15) ~[?:?]
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74) ~[?:?]
        at org.jetbrains.exposed.sql.Database.getVendor(Database.kt) ~[?:?]
        at org.jetbrains.exposed.sql.Database$dialect$2.invoke(Database.kt:38) ~[?:?]
        at org.jetbrains.exposed.sql.Database$dialect$2.invoke(Database.kt:15) ~[?:?]
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74) ~[?:?]
        at org.jetbrains.exposed.sql.Database.getDialect(Database.kt) ~[?:?]
        at org.jetbrains.exposed.sql.vendors.DefaultKt.getCurrentDialect(Default.kt:758) ~[?:?]
        at org.jetbrains.exposed.sql.QueriesKt.exists(Queries.kt:190) ~[?:?]
        at org.jetbrains.exposed.sql.SchemaUtils.createStatements(SchemaUtils.kt:78) ~[?:?]
        at org.jetbrains.exposed.sql.SchemaUtils.create(SchemaUtils.kt:181) ~[?:?]
        at org.jetbrains.exposed.sql.SchemaUtils.create$default(SchemaUtils.kt:179) ~[?:?]`
        
I see in others issues related to this thats cause this error message: "Unsupported driver SQLite JDBC detected" with JDBC separated, but in my case is not.

I tested with kotlin expose versions: `0.31.1, 0.30.1, 0.29.1, 0.25,1`, none worked
tested too with `org.xerial:sqlite-jdbc:3.30.1`

**Comment by Tapac** [comment]
You can try to update to the more recent sqlite-jdbc driver like: `3.32.3.2`, but it's strange as 3.30.1 have "SQLite JDBC" driver name.
Do you have a custom `sqlite-jdbc.properties` file with `SQLiteJDBC` name override?

**Comment by uinnn** [comment]
I think the problem is about a library that already implements sqlite, but outdated, I tested it without the library and it worked perfectly. I will close this issue
