### ISSUE TITLE
key is not initialized yet

### ISSUE THREAD

**Issue by Gutyerrez** [JetBrains/Exposed#1246]
Code:

```
faction = FactionDAO.new(
            UUID.nameUUIDFromBytes("Faction:${createFactionDTO.name}".toByteArray())
        ) {
            this.name = createFactionDTO.name
            this.tag = createFactionDTO.tag
        }.toFaction()

toFaction = fun toFaction() = Faction(
        this.id,
        this.name,
        this.tag,
        this.warWins,
        this.base,
        this.outPosting,
        this.createdAt,
        this.updatedAt
    )

```

Table structure:

![image](https://user-images.githubusercontent.com/36475012/119370580-cf571980-bc8b-11eb-8403-4835ec011fff.png)

Throws:

```
[21:26:59 WARN]: java.lang.IllegalStateException: net.hyren.factions.faction.storage.table.FactionsTable.war_wins is not initialized yet
[21:26:59 WARN]:        at org.jetbrains.exposed.sql.ResultRow.rawToColumnValue(ResultRow.kt:52)
[21:26:59 WARN]:        at org.jetbrains.exposed.sql.ResultRow.access$rawToColumnValue(ResultRow.kt:7)
[21:26:59 WARN]:        at org.jetbrains.exposed.sql.ResultRow$get$$inlined$let$lambda$1.invoke(ResultRow.kt:31)
[21:26:59 WARN]:        at org.jetbrains.exposed.sql.vendors.DefaultKt.withDialect(Default.kt:752)
[21:26:59 WARN]:        at org.jetbrains.exposed.sql.ResultRow.get(ResultRow.kt:30)
[21:26:59 WARN]:        at org.jetbrains.exposed.dao.Entity.lookup(Entity.kt:107)
[21:26:59 WARN]:        at org.jetbrains.exposed.dao.Entity.getValue(Entity.kt:88)
[21:26:59 WARN]:        at net.hyren.factions.faction.storage.dao.FactionDAO.getWarWins(FactionDAO.kt:21)
[21:26:59 WARN]:        at net.hyren.factions.faction.storage.dao.FactionDAO.toFaction(FactionDAO.kt:31)
[21:26:59 WARN]:        at net.hyren.factions.faction.storage.repositories.implementations.PostgreSQLFactionsRepository$create$1.invoke(PostgreSQLFactionsRepository.kt:54)
[21:26:59 WARN]:        at net.hyren.factions.faction.storage.repositories.implementations.PostgreSQLFactionsRepository$create$1.invoke(PostgreSQLFactionsRepository.kt:48)
[21:26:59 WARN]:        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$inTopLevelTransaction$1.invoke(ThreadLocalTransactionManager.kt:173)
[21:26:59 WARN]:        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$inTopLevelTransaction$2.invoke(ThreadLocalTransactionManager.kt:194)
[21:26:59 WARN]:        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:202)
[21:26:59 WARN]:        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction(ThreadLocalTransactionManager.kt:193)
[21:26:59 WARN]:        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$transaction$1.invoke(ThreadLocalTransactionManager.kt:151)
[21:26:59 WARN]:        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:202)
[21:26:59 WARN]:        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:123)
[21:26:59 WARN]:        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:121)
[21:26:59 WARN]:        at net.hyren.factions.faction.storage.repositories.implementations.PostgreSQLFactionsRepository.create(PostgreSQLFactionsRepository.kt:46)
[21:26:59 WARN]:        at net.hyren.factions.commands.subcommands.FactionCreateCommand.onCommand(FactionCreateCommand.kt:94)
[21:26:59 WARN]:        at net.hyren.factions.commands.subcommands.FactionCreateCommand.onCommand(FactionCreateCommand.kt:26)
[21:26:59 WARN]:        at net.hyren.core.shared.commands.Commandable$DefaultImpls.executeRaw(Commandable.kt:128)
[21:26:59 WARN]:        at net.hyren.core.spigot.command.CustomCommand.executeRaw(CustomCommand.kt:14)
[21:26:59 WARN]:        at net.hyren.core.spigot.command.CustomCommand.executeRaw(CustomCommand.kt:14)
[21:26:59 WARN]:        at net.hyren.core.shared.commands.Commandable$DefaultImpls.executeRaw(Commandable.kt:141)
[21:26:59 WARN]:        at net.hyren.core.spigot.command.CustomCommand.executeRaw(CustomCommand.kt:14)
[21:26:59 WARN]:        at net.hyren.core.spigot.command.CustomCommand.executeRaw(CustomCommand.kt:14)
[21:26:59 WARN]:        at net.hyren.core.spigot.command.CustomCommand.execute(CustomCommand.kt:41)
[21:26:59 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:138)
[21:26:59 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:707)
[21:26:59 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1215)
[21:26:59 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1018)
[21:26:59 WARN]:        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45)
[21:26:59 WARN]:        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1)
[21:26:59 WARN]:        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13)
[21:26:59 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[21:26:59 WARN]:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[21:26:59 WARN]:        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44)
[21:26:59 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:872)
[21:26:59 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378)
[21:26:59 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:808)
[21:26:59 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:704)
[21:26:59 WARN]:        at java.lang.Thread.run(Thread.java:748)
```

**Comment by renaudmathieu** [comment]
I have a similar issue. How did you solve it?
