### ISSUE TITLE
Unclosed ResultSet in NonAutoIncEntities.testNotAutoIncTable

### ISSUE THREAD

**Issue by vlsi** [JetBrains/Exposed#1279]
CI link: https://teamcity.jetbrains.com/viewLog.html?buildId=3518387&buildTypeId=Exposed_PullRequests&tab=buildLog&_focus=3498

```
  at org.jetbrains.exposed.sql.statements.jdbc.JdbcPreparedStatementImpl.executeQuery(JdbcPreparedStatementImpl.kt:24)
  at org.jetbrains.exposed.sql.Query.executeInternal(Query.kt:83)
  at org.jetbrains.exposed.sql.Query.executeInternal(Query.kt:13)
  at org.jetbrains.exposed.sql.statements.Statement.executeIn$exposed_core(Statement.kt:60)
  at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:135)
  at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:121)
  at org.jetbrains.exposed.sql.AbstractQuery.iterator(AbstractQuery.kt:65)
  at org.jetbrains.exposed.sql.IterableExKt$mapLazy$1.iterator(IterableEx.kt:129)
  at org.jetbrains.exposed.sql.tests.shared.entities.NonAutoIncEntities$testNotAutoIncTable$1.invoke(NonAutoIncEntities.kt:106)
  at org.jetbrains.exposed.sql.tests.shared.entities.NonAutoIncEntities$testNotAutoIncTable$1.invoke(NonAutoIncEntities.kt:60)
  at org.jetbrains.exposed.sql.tests.DatabaseTestsBase$withTables$1$1.invoke(DatabaseTestsBase.kt:179)
  at org.jetbrains.exposed.sql.tests.DatabaseTestsBase$withTables$1$1.invoke(DatabaseTestsBase.kt:176)
  at org.jetbrains.exposed.sql.tests.DatabaseTestsBase$withDb$2.invoke(DatabaseTestsBase.kt:158)
  at org.jetbrains.exposed.sql.tests.DatabaseTestsBase$withDb$2.invoke(DatabaseTestsBase.kt:157)
  at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction$run(ThreadLocalTransactionManager.kt:173)
  at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.access$inTopLevelTransaction$run(ThreadLocalTransactionManager.kt:1)
  at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$inTopLevelTransaction$1.invoke(ThreadLocalTransactionManager.kt:194)
  at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:202)
  at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction(ThreadLocalTransactionManager.kt:193)
  at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$transaction$1.invoke(ThreadLocalTransactionManager.kt:151)
  at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:202)
  at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:123)
  at org.jetbrains.exposed.sql.tests.DatabaseTestsBase.withDb(DatabaseTestsBase.kt:157)
  at org.jetbrains.exposed.sql.tests.DatabaseTestsBase.withTables(DatabaseTestsBase.kt:176)
  at org.jetbrains.exposed.sql.tests.DatabaseTestsBase.withTables(DatabaseTestsBase.kt:205)
  at org.jetbrains.exposed.sql.tests.shared.entities.NonAutoIncEntities.testNotAutoIncTable(NonAutoIncEntities.kt:60)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:498)
  at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
  at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
  at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
  at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
  at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
  at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
  at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
  at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
  at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
  at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
  at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
  at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
  at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
```

**Comment by Tapac** [comment]
The problem is in `NotAutoEntity.all().any` which doesn't iterate until the end and "drops" the iterator in the middle of data. 
It's sad but I don't know any way how to handle such cases without loading the whole result set into memory.

**Comment by Tapac** [comment]
Tracking unclosed result sets added. All opened result sets will be closed on commit/rollback.
