### ISSUE TITLE
Exception when trying to add a column with a default value

### ISSUE THREAD

**Issue by msrd0** [JetBrains/Exposed#128]
After I added a new column like this

```kotlin
val test = char("test").default('X')
```

I received the following exception:

```
Caused by: org.postgresql.util.PSQLException: ERROR: column "x" does not exist
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2476)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2189)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:300)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:428)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:354)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:169)
	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:136)
	at org.jetbrains.exposed.sql.Transaction$exec$2.executeInternal(Transaction.kt:91)
	at org.jetbrains.exposed.sql.statements.Statement.executeIn$exposed_main(Statement.kt:57)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:108)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:102)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:87)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:81)
	at org.jetbrains.exposed.sql.SchemaUtils$createMissingTablesAndColumns$$inlined$with$lambda$1.invoke(SchemaUtils.kt:128)
	at org.jetbrains.exposed.sql.SchemaUtils$createMissingTablesAndColumns$$inlined$with$lambda$1.invoke(SchemaUtils.kt:9)
	at org.jetbrains.exposed.sql.SchemaUtils.withDataBaseLock(SchemaUtils.kt:152)
	... 9 more
```

Although the sql to stdout logger is active, I didn't found the sql statement that caused the error. So I started playing around and found the issue: You are trying to insert the column like this:

```sql
ALTER  TABLE foo ADD COLUMN test CHAR DEFAULT X;
```

This will fail of course because the default value for the column `test` should come from the column `x` which doesn't exist. Please enquote the value to get the desired sql statement:

```sql
ALTER TABLE foo ADD COLUMN test CHAR DEFAULT 'X';
```

**Comment by msrd0** [comment]
Adding to the above behaviour, when I create the column myself, my application crashes on startup because of a syntax error near `MODIFY`. Removing the default value fixes this syntax error but is not what I want. So it looks like you are trying to update the default value although it is already correct and that this query has a syntax error. Unfortunately Exposed didn't tell me the faulty sql statement.
