### ISSUE TITLE
Transaction closed when launching coroutine inside transaction

### ISSUE THREAD

**Issue by aott31** [JetBrains/Exposed#1292]
An error is thrown when trying to commit the transaction with following code:

```
fun main() {
    runBlocking {
        val databaseService = DatabaseService()
        databaseService.start()
        while (true) {
            databaseService.transaction {
                println("Start transaction")
                MyTable.insert { it[MyTable.name] = "toto" }
                println("Start effect")
                either<Nothing, Unit> {
                    somethingWithEffect().bind()
                }
                println("End effect")
                println("End transaction")
            }
        }
    }
}

suspend fun somethingWithEffect(): Either<Nothing, Unit>  = Either.Right(arrow.fx.coroutines.sleep(1.nanoseconds))
```

Error is:

```Connecting to database with exposed.
Connected to database.
Start transaction
Start effect
End effect
End transaction
Start transaction
Start effect
End effect
End transaction
Start transaction
Start effect
End effect
End transaction
Exception in thread "main" java.lang.IllegalStateException: Can't init value outside the transaction
	at org.jetbrains.exposed.sql.transactions.TransactionStore.getValue(TransactionScope.kt:21)
	at org.jetbrains.exposed.dao.EntityCacheKt.getEntityCache(EntityCache.kt:9)
	at org.jetbrains.exposed.dao.EntityCacheKt.flushCache(EntityCache.kt:164)
	at org.jetbrains.exposed.dao.EntityLifecycleInterceptor.beforeCommit(EntityLifecycleInterceptor.kt:68)
	at org.jetbrains.exposed.sql.Transaction.commit(Transaction.kt:63)
	at org.jetbrains.exposed.sql.transactions.experimental.SuspendedKt$suspendedTransactionAsyncInternal$1.invokeSuspend(Suspended.kt:117)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at arrow.core.SuspendMonadContinuation.resumeWith(SuspendingMonadContinuation.kt:61)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlin.coroutines.SafeContinuation.resumeWith(SafeContinuationJvm.kt:41)
	at arrow.fx.coroutines.BuildersKt$$special$$inlined$onceOnly$arrow_fx_coroutines$1.invoke(Platform.kt:318)
	at arrow.fx.coroutines.BuildersKt$$special$$inlined$onceOnly$arrow_fx_coroutines$1.invoke(Platform.kt:20)
	at arrow.fx.coroutines.TimerKt$sleep$2$cancelRef$1.run(timer.kt:44)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

As you can see, it doesn't happen every time, sometime the transaction ends well. 

either comes from Arrow library and is launching a coroutine and I think ending the either coroutine is causing the transaction to end.

You can find full code here : https://drive.google.com/file/d/1vQKsuw94sbxxg8AaegNyU5VlUmIYpQVe/view?usp=sharing

It was working well on version 0.28.1 and breaks when upgrading to 0.32.1

**Comment by aott31** [comment]
Any news about this ? Any idea where the problem comes from or if we can use a workaround ?

**Comment by Tapac** [comment]
@aott31, I've checked your code, and looks like there is maybe a problem with Arrows `sleep` (deprecated in a newer version) which resets and doesn't restore the current thread in a suspended block. 

Can you please check how it works with a `delay` or please share a new sample up-to-date arrow.

**Comment by aott31** [comment]
Hi, it seems to work with the upgrade of arrow. Thank you for the tip!
