### ISSUE TITLE
Dao example does not work on MariaDB or MySQL - KotlinNullPointerException on org.jetbrains.exposed.dao.EntityCache.flushInserts$exposed_main

### ISSUE THREAD

**Issue by v79** [JetBrains/Exposed#132]
Using the example Cities DAO code, I replaced the connection string  with a MariaDB connection, which should be equivalent to MySQL, using the org.mariadb.jdbc.Driver.

```kotlin
println("========== DAO Example with MariaDB ========")
Database.connect("jdbc:mysql://127.0.0.1:3306/Employees?user=root&password=password", driver = "org.mariadb.jdbc.Driver")
```
The tables are created, but the data isn't inserted and there is a NPE while flushing the inserts.

The exception is:

```========== DAO Example with MariaDB ========
Exception in thread "main" kotlin.KotlinNullPointerException
	at org.jetbrains.exposed.dao.EntityCache.flushInserts$exposed_main(Entity.kt:411)
	at org.jetbrains.exposed.dao.EntityID.getValue(Entity.kt:18)
	at org.jetbrains.exposed.dao.Entity.setValue(Entity.kt:194)
	at uk.co.liamjdavison.kotlinsparkroutes.User.setCity(DaoTest.kt)
	at uk.co.liamjdavison.kotlinsparkroutes.DaoTestKt$main$1$1.invoke(DaoTest.kt:55)
	at uk.co.liamjdavison.kotlinsparkroutes.DaoTestKt$main$1$1.invoke(DaoTest.kt)
	at org.jetbrains.exposed.dao.EntityClass.new(Entity.kt:609)
	at org.jetbrains.exposed.dao.EntityClass.new(Entity.kt:599)
	at uk.co.liamjdavison.kotlinsparkroutes.DaoTestKt$main$1.invoke(DaoTest.kt:53)
	at uk.co.liamjdavison.kotlinsparkroutes.DaoTestKt$main$1.invoke(DaoTest.kt)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction(ThreadLocalTransactionManager.kt:70)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:58)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:49)
	at uk.co.liamjdavison.kotlinsparkroutes.DaoTestKt.main(DaoTest.kt:40)
```

The DSL example works fine with MariaDB.

**Comment by v79** [comment]
The Dao example does not work on MySQL either, with the same error as above.

Windows 10 64-Bit. MySQL version 5.7.19. MariaDB version 10.2.7-MariaDB.

I did get it to work with PostgreSQL 9.6.3 on Windows.

My test code is available [in my github exposed branch](https://github.com/v79/kotlin-spark-routes/blob/exposed/src/main/kotlin/uk/co/liamjdavison/kotlinsparkroutes/DaoTest.kt).

**Comment by Tapac** [comment]
Could you try to use latest MariaDB jdbc driver? As I see from build,gradle you run 1.1.7 which was released at April 2014.

**Comment by v79** [comment]
I upgraded to driver version 2.0.3.

I had to change the connection approach `( Database.connect(url = "jdbc:mysql://127.0.0.1:3306/kotlinsparkroutes", user = "user", password = "password", driver = "org.mariadb.jdbc.Driver")` instead of `Database.connect("jdbc:mysql://127.0.0.1:3306/Employees?user=user&password=password", driver = "org.mariadb.jdbc.Driver")`.

Finally, it worked with MariaDB. Thank you.
