### ISSUE TITLE
Exception in thread "main" java.lang.NoClassDefFoundError: kotlin/reflect/full/KClasses

### ISSUE THREAD

**Issue by junhwong** [JetBrains/Exposed#133]
DSL:
```kt
object Keyword : Table(name = "keywords") {
    val id = long("id").autoIncrement().primaryKey()
    val words = varchar("words", length = 200)
    val pos = varchar("pos", length = 45)
}
```

insert error:
```
Exception in thread "main" java.lang.NoClassDefFoundError: kotlin/reflect/full/KClasses
	at org.jetbrains.exposed.sql.Table.clone(Table.kt:197)
	at org.jetbrains.exposed.sql.Table.cloneWithAutoInc(Table.kt:235)
	at org.jetbrains.exposed.sql.Table.autoIncrement(Table.kt:239)
	at org.jetbrains.exposed.sql.Table.autoIncrement$default(Table.kt:239)
	at dao.Keyword.<init>(Keyword.kt:12)
	at dao.Keyword.<clinit>(Keyword.kt:11)
	at dao.KeywordKt$test$1.invoke(Keyword.kt:24)
	at dao.KeywordKt$test$1.invoke(Keyword.kt)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction(ThreadLocalTransactionManager.kt:70)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:58)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:49)
	at dao.KeywordKt.test(Keyword.kt:21)
	at MainKt.main(main.kt:8)
Caused by: java.lang.ClassNotFoundException: kotlin.reflect.full.KClasses
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 13 more
```

create error:
```
Exception in thread "main" java.sql.SQLException: Table name pattern can not be NULL or empty.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:545)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:513)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:505)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:479)
	at com.mysql.cj.jdbc.DatabaseMetaData.getTables(DatabaseMetaData.java:3836)
	at org.jetbrains.exposed.sql.vendors.VendorDialect.allTablesNames(Default.kt:138)
	at org.jetbrains.exposed.sql.vendors.VendorDialect.getAllTablesNames(Default.kt:121)
	at org.jetbrains.exposed.sql.vendors.VendorDialect.tableExists(Default.kt:148)
	at org.jetbrains.exposed.sql.QueriesKt.exists(Queries.kt:85)
	at org.jetbrains.exposed.sql.SchemaUtils.createStatements(SchemaUtils.kt:19)
	at org.jetbrains.exposed.sql.SchemaUtils.create(SchemaUtils.kt:100)
	at dao.KeywordKt$test$1.invoke(Keyword.kt:23)
	at dao.KeywordKt$test$1.invoke(Keyword.kt)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction(ThreadLocalTransactionManager.kt:70)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:58)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:49)
	at dao.KeywordKt.test(Keyword.kt:21)
	at MainKt.main(main.kt:8)

```

**Comment by Tapac** [comment]
@junhwong, Try to rebuild project and re-run code. Which version of IDE + kotlin plugin and Exposed do you use?

**Comment by junhwong** [comment]
@Tapac  I tried. but still so. 
kotlin :1.1.3-2
Exposed :0.8.2
java : 8
ide: idea 2017
gradle 4.0

**Comment by junhwong** [comment]
and  i removed: 
```kt
val id = long("id").autoIncrement().primaryKey() 
```

run insert is successful。

**Comment by Tapac** [comment]
Could you provide full example to reproduce that issue?

**Comment by junhwong** [comment]
Exception in thread "main" java.lang.NoClassDefFoundError: kotlin/reflect/full/KClasses
is solved, but  Exception in thread "main" java.sql.SQLException: Table name pattern can not be NULL or empty error is still.

test full code:
```kt
object Keyword : Table(name = "keywords") {
    val id = long("id").autoIncrement().primaryKey()
    val words = varchar("words", length = 200)
    val pos = varchar("pos", length = 45)
}

fun test(){

    //
    var x = Database.connect("jdbc:mysql://127.0.0.1/...", driver = "com.mysql.cj.jdbc.Driver", user = "...", password = "...")
    transaction {
        logger.addLogger(StdOutSqlLogger)
        //create(Keyword)
        Keyword.insert {
            it[words] = "hello1"
            it[pos] = "v"
        }
    }
}
```

**Comment by KotlinFTW** [comment]
I get this too.  Same versions on everything.  Tried several exposed versions before giving up and going back to 0.5.0, which works.

**Comment by Tapac** [comment]
@KotlinFTW , which version of kotlin plugin do you use? How you run your code - from gradle or from IDE ?

**Comment by tenwit** [comment]
The same exception was reported in projects dependent on SpringBoot. It was worked around by adding a dependency on kotlin-reflect.
https://github.com/spring-projects/spring-boot/issues/9984#issuecomment-321194903

**Comment by Tapac** [comment]
@tenwit , Exposed already has such dependency: 
```
    dependencies {
        compile "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
        compile "org.jetbrains.kotlin:kotlin-reflect:$kotlin_version"
        ...
    }
```

**Comment by Tapac** [comment]
@junhwong , in mysql jdbc driver v6.0+ changed default value for "nullNamePatternMatchesAll" and which used in `getTables()`. I've fixed it in Exposed, so you should not get this after update to next release (0.8.6).
