### ISSUE TITLE
Eager loading Parent-Child Reference 

### ISSUE THREAD

**Issue by zypus** [JetBrains/Exposed#1363]
It currently does not seem to be possible to eagerly load a Parent-Child relationship. 

For example having the following setup from the wiki [DAO#parent-child-reference](https://github.com/JetBrains/Exposed/wiki/DAO#parent-child-reference):

```kotlin
object NodeTable : IntIdTable() {
    val name = varchar("name", 50)
}
object NodeToNodes : Table() {
    val parent = reference("parent_node_id", NodeTable)
    val child = reference("child_user_id", NodeTable)
}
class Node(id: EntityID<Int>) : IntEntity(id) {
    companion object : IntEntityClass<Node>(NodeTable)
    var name by NodeTable.name
    var parents by Node.via(NodeToNodes.child, NodeToNodes.parent)
    var children by Node.via(NodeToNodes.parent, NodeToNodes.child)
}
```

The following does not work:

```kotlin
transaction {
   val nodesWithEagerlyLoadedChildren = Node.all().with(Node::children).toList()
   nodesWithEagerlyLoadedChildren.children
}
```

because the following code in [EntityClass.kt#L401](https://github.com/JetBrains/Exposed/blob/8c71562f1f3fded1a7cc45404f582f107e5a4453/exposed-dao/src/main/kotlin/org/jetbrains/exposed/dao/EntityClass.kt#L401) expects the referee to only occur once, but in the Parent-Child scenario the same referee appears of cause twice:

```kotlin
// EntityClass.kt

398    fun warmUpLinkedReferences(references: List<EntityID<*>>, linkTable: Table, forUpdate: Boolean? = null): List<T> {
399       if (references.isEmpty()) return emptyList()
400       val distinctRefIds = references.distinct()
401        val sourceRefColumn = linkTable.columns.singleOrNull { it.referee == references.first().table.id } as? Column<EntityID<*>>
402            ?: error("Can't detect source reference column")
```

Is this supposed to work, or are Parent-Child references excluded by design?

---

Error and stacktrace from above:
```
java.lang.IllegalStateException: Can't detect source reference column
	at org.jetbrains.exposed.dao.EntityClass.warmUpLinkedReferences(EntityClass.kt:402)
	at org.jetbrains.exposed.dao.EntityClass.warmUpLinkedReferences$default(EntityClass.kt:398)
	at org.jetbrains.exposed.dao.ReferencesKt.preloadRelations(References.kt:180)
	at org.jetbrains.exposed.dao.ReferencesKt.preloadRelations$default(References.kt:126)
	at org.jetbrains.exposed.dao.ReferencesKt.with(References.kt:226)
	       ... remaining unrelated frames omitted
```

---

Kotlin: 1.5.31
Exposed: 0.35.2

**Comment by gkiss01** [comment]
Up!
Was there any solution?
