### ISSUE TITLE
Exposed Proguard Problem

### ISSUE THREAD

**Issue by goksunonal** [JetBrains/Exposed#1377]
Hi, I am using IntEntityClass and EntityId in my database class and getting this error while using proguard.

```
Caused by: java.lang.NullPointerException: null
	at org.jetbrains.exposed.dao.EntityClass.<init>(EntityClass.kt:18)
	at org.jetbrains.exposed.dao.IntEntityClass.<init>(IntEntity.kt:8)
	at org.jetbrains.exposed.dao.IntEntityClass.<init>(IntEntity.kt:8)
	at myPath.MyClass$Companion.<init>(SourceFile:50)
	at myPath.MyClass$Companion.<init>(SourceFile)
	at myPath.MyClass.<clinit>(SourceFile:52)
```

Tried these rules too but didn't seem to solve:

```
-keepclassmembers class myPath.MyClass{
    public static ** Companion;
}

-keep class myPath.MyClass$Companion { *; }
-keep class org.jetbrains.** { *; }
-keep interface org.jetbrains.** { *; }
-keep enum org.jetbrains.** { *; }
```

class context ->

```
internal object MyClasses: IntIdTable(Constant.MyCLASS) {
    val name = varchar("name", length = 50).uniqueIndex()
}

class MyClass(id: EntityID<Int>) : IntEntity(id) {
    companion object : IntEntityClass<MyClass>(MyClasses)

    var name by MyClasses.name
}
```

I am not sure if issue is totally related to 'Exposed' but i would like to hear opinions.

**Comment by stengvac** [comment]
Did you tried to remove `internal`?

**Comment by RationalityFrontline** [comment]
No proguard rules are needed. Just pass your DAO class to your EntityClass's constructor:
```kotlin
class MyClass(id: EntityID<Int>) : IntEntity(id) {
    companion object : IntEntityClass<MyClass>(MyClasses, MyClass::class.java)

    var name by MyClasses.name
}
```

**Comment by goksunonal** [comment]
Tried both ways, didn't work. I am suspecting usage of companion object.

**Comment by RationalityFrontline** [comment]
@goksunonal It's wired, my solution should work. The NullPointerException was thrown from here:
![image](https://user-images.githubusercontent.com/69410606/140269596-10b10e2e-c406-4ac9-a07a-f5764fc80f1c.png)
So passing in the `entityType`  should solve the problem.

**Comment by goksunonal** [comment]
@RationalityFrontline 'Null Pointer' problem is happening less often after your recommendation. There is another problem which starting to happen more which may give us more idea:

```
java.lang.NoClassDefFoundError: Could not initialize class myPath.MyClass
	at myPath.MyClass.I.a(SourceFile:82)
	at myPath.MyClass.I.invoke(SourceFile:81)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$transaction$1.invoke(ThreadLocalTransactionManager.kt:131)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:202)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:123)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:121)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction$default(ThreadLocalTransactionManager.kt:120)
	at myPath.MyClass.F.a(SourceFile:81)
	at myPath.MyClass.F.a(SourceFile:62)
	at myPath.MyClass.H.a(SourceFile:97)
	at myPath.MyClass.H.invoke(SourceFile:95)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$inTopLevelTransaction$1.invoke(ThreadLocalTransactionManager.kt:173)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$inTopLevelTransaction$2.invoke(ThreadLocalTransactionManager.kt:194)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:202)
```

Related function:

```
    private fun findBySystemName(id: Int): String {
        return transaction {
            MyClass.findById(id).toString()
        }
    }
```

![image](https://user-images.githubusercontent.com/32015340/140274361-ed6563d0-6061-424d-8247-7e9fda6a4c7e.png)

**Comment by Tapac** [comment]
Did you relocate packages with Proguard?

**Comment by goksunonal** [comment]
Yep,

problem is definitely with 
` companion object : IntEntityClass<MyClass>(MyClasses)`
that part. No error occurs when i remove it.
