### ISSUE TITLE
Providing a String ID to `DaoEntity.new(EntityId)` makes Exposed "forget" about the last field passed to the new call

### ISSUE THREAD

**Issue by MrPowerGamerBR** [JetBrains/Exposed#1379]
```kotlin
fun main() {
    connectToDatabase(
        HikariDataSource(
            createPostgreSQLHikari("127.0.0.1", "testtable", "postgres", "postgres")
        )
    )

    transaction {
        SchemaUtils.createMissingTablesAndColumns(
            Table1,
            Table2
        )
    }

    transaction {
        val obj1 = Obj1.new {
            a = "hello world!"
        }

        Obj2.new("test") {
            a = "bye world!"
            ref = obj1
        }
    }
}

abstract class TextEntity(id: EntityID<String>) : Entity<String>(id)

abstract class TextEntityClass<out E : TextEntity>(table: IdTable<String>, entityType: Class<E>? = null) : EntityClass<String, E>(table, entityType)

open class TextIdTable(name: String = "", columnName: String = "id") : IdTable<String>(name) {
    final override val id: Column<EntityID<String>> = text(columnName).entityId()
    final override val primaryKey = PrimaryKey(id)
}

class Obj1(id: EntityID<Long>) : LongEntity(id) {
    companion object : LongEntityClass<Obj1>(Table1)
    var a by Table1.a
}

class Obj2(id: EntityID<String>) : TextEntity(id) {
    companion object : TextEntityClass<Obj2>(Table2)
    var a by Table2.a
    var ref by Obj1 referencedOn Table2.ref
}

object Table2 : TextIdTable() {
    val a = text("a")
    val ref = reference("ref", Table1)
}

object Table1 : LongIdTable() {
    val a = text("a")
}

private fun connectToDatabase(dataSource: HikariDataSource): Database =
    Database.connect(
        HikariDataSource(dataSource),
        databaseConfig = DatabaseConfig {
            defaultRepetitionAttempts = DEFAULT_REPETITION_ATTEMPTS
            defaultIsolationLevel = IsolationLevel.TRANSACTION_REPEATABLE_READ.levelId // Change our default isolation level
        }
    )


fun createPostgreSQLHikari(address: String, databaseName: String, username: String, password: String): HikariConfig {
    val hikariConfig = createHikariConfig()
    hikariConfig.jdbcUrl = "jdbc:postgresql://$address/$databaseName"

    hikariConfig.username = username
    hikariConfig.password = password

    return hikariConfig
}

private fun createHikariConfig(): HikariConfig {
    val hikariConfig = HikariConfig()

    hikariConfig.driverClassName = "org.postgresql.Driver"

    // Exposed uses autoCommit = false, so we need to set this to false to avoid HikariCP resetting the connection to
    // autoCommit = true when the transaction goes back to the pool, because resetting this has a "big performance impact"
    // https://stackoverflow.com/a/41206003/7271796
    hikariConfig.isAutoCommit = false

    // Useful to check if a connection is not returning to the pool, will be shown in the log as "Apparent connection leak detected"
    hikariConfig.leakDetectionThreshold = 30L * 1000
    hikariConfig.transactionIsolation = IsolationLevel.TRANSACTION_REPEATABLE_READ.name // We use repeatable read to avoid dirty and non-repeatable reads! Very useful and safe!!

    return hikariConfig
}
```

```
Exception in thread "main" org.jetbrains.exposed.exceptions.ExposedSQLException: java.sql.BatchUpdateException: Batch entry 0 INSERT INTO table2 ("a", id) VALUES ('bye world!', 'test')
RETURNING * was aborted: ERROR: null value in column "ref" violates not-null constraint
  Detalhe: Failing row contains (test, bye world!, null).  Call getNextException to see other errors in the batch.
SQL: [INSERT INTO Table2 ("a", id) VALUES (?, ?)]
	at org.jetbrains.exposed.sql.statements.Statement.executeIn$exposed_core(Statement.kt:62)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:144)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:130)
	at org.jetbrains.exposed.sql.statements.Statement.execute(Statement.kt:28)
	at org.jetbrains.exposed.sql.QueriesKt.executeBatch(Queries.kt:179)
	at org.jetbrains.exposed.sql.QueriesKt.batchInsert(Queries.kt:108)
	at org.jetbrains.exposed.sql.QueriesKt.batchInsert(Queries.kt:94)
	at org.jetbrains.exposed.sql.QueriesKt.batchInsert$default(Queries.kt:89)
	at org.jetbrains.exposed.dao.EntityCache$flushInserts$1$ids$1.invoke(EntityCache.kt:165)
	at org.jetbrains.exposed.dao.EntityCache$flushInserts$1$ids$1.invoke(EntityCache.kt:164)
	at org.jetbrains.exposed.dao.EntityLifecycleInterceptorKt.executeAsPartOfEntityLifecycle(EntityLifecycleInterceptor.kt:18)
	at org.jetbrains.exposed.dao.EntityCache.flushInserts$exposed_dao(EntityCache.kt:164)
	at org.jetbrains.exposed.dao.EntityCache.flush(EntityCache.kt:121)
	at org.jetbrains.exposed.dao.EntityCache.flush(EntityCache.kt:90)
	at org.jetbrains.exposed.dao.EntityCacheKt.flushCache(EntityCache.kt:223)
	at org.jetbrains.exposed.dao.EntityLifecycleInterceptor.beforeExecution(EntityLifecycleInterceptor.kt:45)
	at org.jetbrains.exposed.sql.statements.Statement.executeIn$exposed_core(Statement.kt:35)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:144)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:130)
	at org.jetbrains.exposed.sql.statements.Statement.execute(Statement.kt:28)
	at org.jetbrains.exposed.sql.QueriesKt.executeBatch(Queries.kt:179)
	at org.jetbrains.exposed.sql.QueriesKt.batchInsert(Queries.kt:108)
	at org.jetbrains.exposed.sql.QueriesKt.batchInsert(Queries.kt:94)
	at org.jetbrains.exposed.sql.QueriesKt.batchInsert$default(Queries.kt:89)
	at org.jetbrains.exposed.dao.EntityCache$flushInserts$1$ids$1.invoke(EntityCache.kt:165)
	at org.jetbrains.exposed.dao.EntityCache$flushInserts$1$ids$1.invoke(EntityCache.kt:164)
	at org.jetbrains.exposed.dao.EntityLifecycleInterceptorKt.executeAsPartOfEntityLifecycle(EntityLifecycleInterceptor.kt:18)
	at org.jetbrains.exposed.dao.EntityCache.flushInserts$exposed_dao(EntityCache.kt:164)
	at org.jetbrains.exposed.dao.DaoEntityID.invokeOnNoValue(DaoEntityID.kt:9)
	at org.jetbrains.exposed.dao.id.EntityID.getValue(EntityID.kt:8)
	at org.jetbrains.exposed.dao.Entity.setValue(Entity.kt:105)
	at Obj2.setRef(ReproduceableIssue.kt:100)
	at ReproduceableIssueKt$main$2$1.invoke(ReproduceableIssue.kt:78)
	at ReproduceableIssueKt$main$2$1.invoke(ReproduceableIssue.kt:76)
	at org.jetbrains.exposed.dao.EntityClass.new(EntityClass.kt:258)
	at ReproduceableIssueKt$main$2.invoke(ReproduceableIssue.kt:76)
	at ReproduceableIssueKt$main$2.invoke(ReproduceableIssue.kt:71)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction$run(ThreadLocalTransactionManager.kt:189)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.access$inTopLevelTransaction$run(ThreadLocalTransactionManager.kt:1)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$inTopLevelTransaction$1.invoke(ThreadLocalTransactionManager.kt:215)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:223)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction(ThreadLocalTransactionManager.kt:214)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$transaction$1.invoke(ThreadLocalTransactionManager.kt:165)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:223)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:135)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:132)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction$default(ThreadLocalTransactionManager.kt:131)
	at ReproduceableIssueKt.main(ReproduceableIssue.kt:71)
	at ReproduceableIssueKt.main(ReproduceableIssue.kt)
Caused by: java.sql.BatchUpdateException: Batch entry 0 INSERT INTO table2 ("a", id) VALUES ('bye world!', 'test')
RETURNING * was aborted: ERROR: null value in column "ref" violates not-null constraint
  Detalhe: Failing row contains (test, bye world!, null).  Call getNextException to see other errors in the batch.
	at org.postgresql.jdbc.BatchResultHandler.handleError(BatchResultHandler.java:165)
	at org.postgresql.core.ResultHandlerDelegate.handleError(ResultHandlerDelegate.java:52)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2365)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:558)
	at org.postgresql.jdbc.PgStatement.internalExecuteBatch(PgStatement.java:881)
	at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:904)
	at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1634)
	at com.zaxxer.hikari.pool.ProxyStatement.executeBatch(ProxyStatement.java:127)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeBatch(HikariProxyPreparedStatement.java)
	at org.jetbrains.exposed.sql.statements.jdbc.JdbcPreparedStatementImpl.executeBatch(JdbcPreparedStatementImpl.kt:48)
	at org.jetbrains.exposed.sql.statements.InsertStatement.execInsertFunction(InsertStatement.kt:118)
	at org.jetbrains.exposed.sql.statements.InsertStatement.executeInternal(InsertStatement.kt:126)
	at org.jetbrains.exposed.sql.statements.InsertStatement.executeInternal(InsertStatement.kt:12)
	at org.jetbrains.exposed.sql.statements.Statement.executeIn$exposed_core(Statement.kt:60)
	... 48 more
Caused by: org.postgresql.util.PSQLException: ERROR: null value in column "ref" violates not-null constraint
  Detalhe: Failing row contains (test, bye world!, null).
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2674)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2364)
	... 59 more
```
Exposed thinks that I didn't provide the `ref` variable but, in fact, I did!

Manually providing the ID fixes the issue
```kotlin
        Obj2.new {
            idWorkaround = DaoEntityID("test", Table2)
            a = "bye world!"
            ref = obj1
        }
```

**Comment by MrPowerGamerBR** [comment]
This only seems to happen if there's a reference in the Table, if there isn't, it works fine
