### ISSUE TITLE
NPE when creating a new table

### ISSUE THREAD

**Issue by LaoLittle** [JetBrains/Exposed#1425]
```
Exception in coroutine <unnamed>
java.lang.NullPointerException
        at org.jetbrains.exposed.sql.vendors.VendorDialect.getAllTableNamesCache(Default.kt:661)
        at org.jetbrains.exposed.sql.vendors.VendorDialect.tableExists(Default.kt:688)
        at org.jetbrains.exposed.sql.QueriesKt.exists(Queries.kt:236)
        at org.jetbrains.exposed.sql.SchemaUtils.createStatements(SchemaUtils.kt:96)
        at org.jetbrains.exposed.sql.SchemaUtils.create(SchemaUtils.kt:255)
        at org.jetbrains.exposed.sql.SchemaUtils.create$default(SchemaUtils.kt:253)
```

**Comment by LaoLittle** [comment]
```kotlin
val exposedVersion = "0.37.2"
```

**Comment by bog-walk** [comment]
@LaoLittle Could you please confirm if this issue persists with current version 0.41.1?

If it does, could you also share more details about the table you're trying to create, so we could attempt to reproduce the problem?
