### ISSUE TITLE
NotImplementedError: An operation is not implemented

### ISSUE THREAD

**Issue by PascalLeMerrerPro** [JetBrains/Exposed#147]
After a connection, I want to insert some data , but I've got an error message:

```
class SQLDB() {

    object countries : Table() {
        val language = varchar("language", 2).primaryKey()
        val list = varchar("list", 65000)
    }
   Database.connect("jdbc:mysql://$DB_HOSTNAME:$DB_PORT/$DB_NAME",
                driver = "com.mysql.jdbc.Driver",
                user = DB_USER,
                password = DB_PASSWORD
        )
}
```
Another class:

```
        transaction {
            SQLDB.countries.insert {
                it[SQLDB.countries.language] = lang.value
                it[SQLDB.countries.list] = countryList

            }
        }
```

The insert line provokes an exception::

```
kotlin.NotImplementedError: An operation is not implemented.

	at org.jetbrains.exposed.sql.transactions.NotInitializedManager.currentOrNull(TransactionApi.kt:29)
	at org.jetbrains.exposed.sql.transactions.TransactionManager$Companion.currentOrNull(TransactionApi.kt:59)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:52)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:49)
```

I assume I'm doing something wrong, but I can't see it.

**Comment by Tapac** [comment]
You should call `Database.connect()` before `transaction`, that's enough to make it single time per application run.

**Comment by PascalLeMerrerPro** [comment]
Ok, i got it.
The problem is that Database.connect() is not invoked before transaction during my unit test (and only in this case).

Just to be sure, is enclosing the calls to the database in transaction{} mandatory whatever is the operation?

**Comment by Tapac** [comment]
It is mandatory to call `Database.connect()` **before first** invocation of transaction{}.
