### ISSUE TITLE
`closeAndUnregister` makes a thread local transaction manager completely dead

### ISSUE THREAD

**Issue by Kaned1as** [JetBrains/Exposed#1476]
After using `TransactionManager.closeAndUnregister(db)` the thread becomes completely unusable for using any other database.

Approximate reproduction steps:
1. Make a database through `Database.connect()` in main thread
2. Use this database in a thread pool (threads 1, 2, 3)
3. Use `TransactionManager.closeAndUnregister` in last task (let's say, thread 1)
4. Now create another database through `Database.connect()` in main thread
5. Try to use this new database through the thread 1 of thread pool

This is what you get:
```
java.lang.IllegalStateException: Please call Database.connect() before using this code
	at org.jetbrains.exposed.sql.transactions.NotInitializedManager.currentOrNull(TransactionApi.kt:38) ~[exposed-core-0.37.3.jar!/:na]
	at org.jetbrains.exposed.sql.transactions.TransactionManager$Companion.currentOrNull(TransactionApi.kt:108) ~[exposed-core-0.37.3.jar!/:na]
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$transaction$1.invoke(ThreadLocalTransactionManager.kt:136) ~[exposed-core-0.37.3.jar!/:na]
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:223) ~[exposed-core-0.37.3.jar!/:na]
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:135) ~[exposed-core-0.37.3.jar!/:na]
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:132) ~[exposed-core-0.37.3.jar!/:na]
```

**Comment by Kaned1as** [comment]
I'll provide a bit more context.

In `TransactionManager.closeAndUnregister` there is following statement:
```kotlin
            val manager = registeredDatabases[database]
            manager?.let {
                registeredDatabases.remove(database)
                databases.remove(database)
                currentDefaultDatabase.compareAndSet(database, null)
                if (currentThreadManager.get() == it) { // <-------- this one
                    currentThreadManager.remove()
                }
            }
```

it calls `currentThreadManager.get()`. If current thread has this thread local removed, it will try to re-initialize it. And will fail, because both `databases` and `registeredDatabases` are empty now, so it will default to `NotInitializedManager`, which will stick and destroy any `transaction(...)` call that you may try afterwards.
