### ISSUE TITLE
SchemaUtils create throws exception with compound primary key and PostgreSQL

### ISSUE THREAD

**Issue by jbenzshawel** [JetBrains/Exposed#1496]
When specifying the schema with the table name, and using a compound primary key, the `SchemaUtils.create` method fails to create the table due to including a period in the primary key constraint name. 

Exposed version: 0.37.3
PostgreSQL Version: 14.1

Example: 

```kotlin
const val SCHEMA = "example"

object FooTable : Table("$SCHEMA.foo_table") {
    val barId = uuid("bar_id") references Bar.id
    val bazId = uuid("baz_id")

    override val primaryKey = PrimaryKey(barId, bazId) // exception is not thrown if constraint name argument is passed 
}

// This throws an exception due to adding a "." in the PK constraint name
SchemaUtils.create(FooTable)
```

Exception that is thrown:
```
org.jetbrains.exposed.exceptions.ExposedSQLException: org.postgresql.util.PSQLException: ERROR: syntax error at or near "."
  Position: 146
SQL: [CREATE TABLE IF NOT EXISTS example.foo_table (bar_id uuid, foo_id uuid, CONSTRAINT pk_example.foo_table PRIMARY KEY (bar_id, foo_id), CONSTRAINT fk_foo_table_bar_id__id FOREIGN KEY (bar_id) REFERENCES example.bar(id) ON DELETE RESTRICT ON UPDATE RESTRICT)]
at org.jetbrains.exposed.sql.statements.Statement.executeIn$exposed_core(Statement.kt:64)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:144)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:130)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:106)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:92)
	at org.jetbrains.exposed.sql.Transaction.exec$default(Transaction.kt:91)
	at org.jetbrains.exposed.sql.SchemaUtils.execStatements(SchemaUtils.kt:248)
	at org.jetbrains.exposed.sql.SchemaUtils.create(SchemaUtils.kt:255)
	at org.jetbrains.exposed.sql.SchemaUtils.create$default(SchemaUtils.kt:253)
```

**Comment by davidwheeler123** [comment]
Perhaps the solution to https://github.com/JetBrains/Exposed/issues/701 would be applicable here too

**Comment by davidwheeler123** [comment]
I've proposed a fix in https://github.com/JetBrains/Exposed/pull/1536
