### ISSUE TITLE
Exposed with sqlite don't support REGEXP expression

### ISSUE THREAD

**Issue by keta1** [JetBrains/Exposed#1554]
```
org.jetbrains.exposed.exceptions.UnsupportedByDialectException: SQLite doesn't provide built in REGEXP expression, use LIKE instead., dialect: sqlite.
	at org.jetbrains.exposed.exceptions.ExceptionsKt.throwUnsupportedException(Exceptions.kt:50)
	at org.jetbrains.exposed.sql.vendors.SQLiteFunctionProvider.regexp(SQLiteDialect.kt:52)
	at org.jetbrains.exposed.sql.RegexpOp.toQueryBuilder(Op.kt:411)
	at org.jetbrains.exposed.sql.QueryBuilder.append(Expression.kt:59)
	at org.jetbrains.exposed.sql.QueryBuilder.unaryPlus(Expression.kt:68)
        .......
```

SQLite3 supports the REGEXP operator:

```

WHERE x REGEXP <regex>

```

http://www.sqlite.org/lang_expr.html#regexp

**Comment by Tapac** [comment]
From [SQLite documentation](https://www.sqlite.org/lang_expr.html#the_like_glob_regexp_match_and_extract_operators):
```
No regexp() user function is defined by default and so use of the REGEXP operator will normally result in an error message.
```

**Comment by keta1** [comment]
thanks
