### ISSUE TITLE
NoSuchMethod error : long kotlin.time.TimeSource$Monotonic.markNow

### ISSUE THREAD

**Issue by ubarua123** [JetBrains/Exposed#1556]
Why am i getting this error? Has exposed moved to kotlin-time? 
That means I can't upgrade the library as I'll have to move everything to kotlin time instead of java time library?

Exposed version : 0.39.2

**Comment by Tapac** [comment]
What kotlin version do you use in your project?

**Comment by ubarua123** [comment]
I am using 1.6.21

**Comment by Tapac** [comment]
That strange as 0.39.2 built with 1.6 target. I'll check.

**Comment by lifestreamy** [comment]
The same happens for me.
```
Exception in thread "main" java.lang.NoSuchMethodError: 'long kotlin.time.TimeSource$Monotonic.markNow-z9LOYto()'
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:233)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:128)
	at org.jetbrains.exposed.sql.statements.Statement.execute(Statement.kt:28)
	at org.jetbrains.exposed.sql.QueriesKt.insert(Queries.kt:73)
	at DataBaseConnectivity.DataBaseConnectivity$Companion$main$insertedNamesId$1.invoke(DataBaseConnectivity.kt:25)
	at DataBaseConnectivity.DataBaseConnectivity$Companion$main$insertedNamesId$1.invoke(DataBaseConnectivity.kt:24)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction$run(ThreadLocalTransactionManager.kt:189)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.access$inTopLevelTransaction$run(ThreadLocalTransactionManager.kt:1)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$inTopLevelTransaction$1.invoke(ThreadLocalTransactionManager.kt:215)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:223)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction(ThreadLocalTransactionManager.kt:214)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$transaction$1.invoke(ThreadLocalTransactionManager.kt:165)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:223)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:135)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:132)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction$default(ThreadLocalTransactionManager.kt:131)
	at DataBaseConnectivity.DataBaseConnectivity$Companion.main(DataBaseConnectivity.kt:24)
	at DataBaseConnectivity.DataBaseConnectivity.main(DataBaseConnectivity.kt)
```

Build.gradle :
```

plugins {
    id 'org.jetbrains.kotlin.jvm' version '1.7.10'
}
group = 'org.example'
version = '1.0-SNAPSHOT'


allprojects {
    repositories {
        mavenCentral()
        maven { url "https://jitpack.io" }
    }
}

dependencies {
    testImplementation 'org.jetbrains.kotlin:kotlin-test'
    testImplementation 'org.slf4j:slf4j-api:2.0.2'
    implementation 'org.slf4j:slf4j-log4j12:1.7.29'
    implementation 'com.github.kotlin-telegram-bot.kotlin-telegram-bot:dispatcher:6.0.7'
    implementation 'org.jetbrains.exposed:exposed-core:0.39.2'
    implementation 'org.jetbrains.exposed:exposed-dao:0.39.2'
    implementation 'org.jetbrains.exposed:exposed-jdbc:0.39.2'
    implementation 'org.postgresql:postgresql:42.2.2'
}

test {
    useJUnitPlatform()
}

compileKotlin {
    kotlinOptions.jvmTarget = '16'
}

compileTestKotlin {
    kotlinOptions.jvmTarget = '16'
}
```

**Comment by lifestreamy** [comment]
When setting JVM target to 1.6:
`e: JVM target 1.6 is no longer supported. Please migrate to JVM target 1.8 or above

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details`

**Comment by bandrefilipe** [comment]
Hi @Tapac! When should we expect a new release with this fix to be out?

**Comment by lifestreamy** [comment]
@bandrefilipe until it is fixed I'd suggest using Exposed version 38.2. Works for me without errors.

**Comment by lifestreamy** [comment]
https://github.com/JetBrains/Exposed/issues/1600#event-7466442875
Here I posted a duplicate of this to get some attention to the issue. 

They commented 7 days ago:
"Fix will be available in a week"

We'll see

**Comment by Tapac** [comment]
Sorry for a delay with release, there were few issues required attention before it. Will be released today.

**Comment by chexov** [comment]
I am running multiplatform example project and hitting this issue with
```plugins {
    kotlin("multiplatform") version "1.7.20"
    application
}

kotlin {
    jvm {
        compilations.all {
            kotlinOptions.jvmTarget = "1.8"
        }
...
```

**Comment by Tapac** [comment]
@chexov , what Exposed version do you use?
