### ISSUE TITLE
java.lang.AbstractMethodError: Method org/sqlite/PrepStmt.isClosed()Z is abstract

### ISSUE THREAD

**Issue by Trqhxrd** [JetBrains/Exposed#1559]
I get this error when trying to use the latest version of exposed and the latest version of xenial's SQLite driver. I know it's kind of a duplicate of #307 but updating to the newest version did not fix it. I also tried using the then-latest version I found in the comments but that did not fix it either. Is this a problem with exposed or a problem with the driver? I'm compiling to Java 8 if that's relevant and connect to the db via ` Database.connect("jdbc:sqlite://path/to/file.sqlite", org.sqlite.JDBC::class.qualifiedName!!)`.

```
java.lang.AbstractMethodError: Method org/sqlite/PrepStmt.isClosed()Z is abstract
	at org.sqlite.PrepStmt.isClosed(PrepStmt.java) ~[spigot-1.8.8.jar:git-Spigot-21fe707-741a1bd]
	at org.jetbrains.exposed.sql.statements.jdbc.JdbcPreparedStatementImpl.closeIfPossible(JdbcPreparedStatementImpl.kt:44) ~[?:?]
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.closeStatementsAndConnection(ThreadLocalTransactionManager.kt:247) ~[?:?]
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction$run(ThreadLocalTransactionManager.kt:209) ~[?:?]
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.access$inTopLevelTransaction$run(ThreadLocalTransactionManager.kt:1) ~[?:?]
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$inTopLevelTransaction$1.invoke(ThreadLocalTransactionManager.kt:215) ~[?:?]
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:223) ~[?:?]
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction(ThreadLocalTransactionManager.kt:214) ~[?:?]
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$transaction$1.invoke(ThreadLocalTransactionManager.kt:165) ~[?:?]
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:223) ~[?:?]
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:135) ~[?:?]
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:132) ~[?:?]
```

**Comment by Trqhxrd** [comment]
Also switching libraries is not an option because my project already uses Exposed a lot and I don't want to have to rewrite all of it.

**Comment by Tapac** [comment]
I'm not sure what driver spigot uses to work with SQlite but looks like it's not ['xerial/sqlite-jdbc'](https://github.com/xerial/sqlite-jdbc), most likely it's https://github.com/redbooth/sqlite-jdbc as there is no `org.sqlite.PrepStmt` class im Xerial but `org.sqlite.jdbc4.JDBC4PreparedStatement`

**Comment by Trqhxrd** [comment]
There is no SQLite driver in the spigot-api-package. I can check in the server jar but I don't think there is a SQLite driver either. They would have added it to the api-package as well so plugin devs can use it.

**Comment by Trqhxrd** [comment]
Thanks for trying to help me and sorry for wasting your time.
