### ISSUE TITLE
SchemaUtils.createMissingTablesAndColumns raise NoSuchElementException

### ISSUE THREAD

**Issue by Komdosh** [JetBrains/Exposed#1568]
I deleted a field in MyFirstTableEntity then I try to restart the server and this exception appears

Code:
```kotlin
    val allTables = listOf(
            MyFirstTableEntity,
            MySecondTableEntity
        )

    transaction(db) {
        SchemaUtils.createMissingTablesAndColumns(*allTables.toTypedArray())
    }
```

Stacktrace:

```
java.util.NoSuchElementException: Key MY_FIRST_TABLE_ENTITY_COPY_4_0 is missing in the map.
	at kotlin.collections.MapsKt__MapWithDefaultKt.getOrImplicitDefaultNullable(MapWithDefault.kt:24)
	at kotlin.collections.MapsKt__MapsKt.getValue(Maps.kt:348)
	at org.jetbrains.exposed.sql.statements.jdbc.JdbcDatabaseMetadataImpl$tableConstraints$1$1.invoke(JdbcDatabaseMetadataImpl.kt:232)
	at org.jetbrains.exposed.sql.statements.jdbc.JdbcDatabaseMetadataImpl$tableConstraints$1$1.invoke(JdbcDatabaseMetadataImpl.kt:221)
	at org.jetbrains.exposed.sql.statements.jdbc.JdbcDatabaseMetadataImplKt.iterate(JdbcDatabaseMetadataImpl.kt:267)
	at org.jetbrains.exposed.sql.statements.jdbc.JdbcDatabaseMetadataImplKt.access$iterate(JdbcDatabaseMetadataImpl.kt:1)
	at org.jetbrains.exposed.sql.statements.jdbc.JdbcDatabaseMetadataImpl.tableConstraints(JdbcDatabaseMetadataImpl.kt:221)
	at org.jetbrains.exposed.sql.vendors.VendorDialect$fillConstraintCacheForTables$1.invoke(Default.kt:740)
	at org.jetbrains.exposed.sql.vendors.VendorDialect$fillConstraintCacheForTables$1.invoke(Default.kt:740)
	at org.jetbrains.exposed.sql.statements.jdbc.JdbcConnectionImpl.metadata(JdbcConnectionImpl.kt:63)
	at org.jetbrains.exposed.sql.Database.metadata$exposed_core(Database.kt:39)
	at org.jetbrains.exposed.sql.vendors.VendorDialect.fillConstraintCacheForTables(Default.kt:740)
	at org.jetbrains.exposed.sql.vendors.VendorDialect.columnConstraints(Default.kt:718)
	at org.jetbrains.exposed.sql.SchemaUtils.addMissingColumnsStatements(SchemaUtils.kt:223)
	at org.jetbrains.exposed.sql.SchemaUtils.createMissingTablesAndColumns(SchemaUtils.kt:318)
	at org.jetbrains.exposed.sql.SchemaUtils.createMissingTablesAndColumns$default(SchemaUtils.kt:306)
        .... my application calls here
```

**Comment by AlexeySoshin** [comment]
@Komdosh Could you please provide the definitions of those entities, and which field have you deleted, so I could try and reproduce this?

**Comment by Tapac** [comment]
@Komdosh , did you remove foreign key constraint as well? 
Or you just remove mapping to the column?

**Comment by Komdosh** [comment]
@AlexeySoshin  I can't really reproduce that
@Tapac I've just remove a mapping to the column

**Comment by Tapac** [comment]
Looks like the problem is that Exposed located foreign key and can't find corresponding column in mapping. I'll take a look how it can be solved.

**Comment by Tapac** [comment]
Should be solved in the next release
