### ISSUE TITLE
Users.username is not in record set

### ISSUE THREAD

**Issue by Tolsi** [JetBrains/Exposed#1634]
Hi, I'm trying to do a simple operation of creating an object with a custom id:

```
import org.jetbrains.exposed.dao.Entity
import org.jetbrains.exposed.dao.EntityClass
import org.jetbrains.exposed.dao.id.EntityID
import org.jetbrains.exposed.dao.id.IdTable
import org.jetbrains.exposed.sql.Column
import org.jetbrains.exposed.sql.Database
import org.jetbrains.exposed.sql.SchemaUtils
import org.jetbrains.exposed.sql.javatime.timestamp
import org.jetbrains.exposed.sql.transactions.transaction
import java.time.Instant

object Users : IdTable<String>() {
    val username = varchar("username", 50)
    val tariff = varchar("tariff", 50)
    val created = timestamp("created")
    override val id: Column<EntityID<String>> = username.entityId()
}

class User(id: EntityID<String>) : Entity<String>(id) {
    companion object : EntityClass<String, User>(Users)

    var username by Users.username
    var tariff by Users.tariff
    var created by Users.created
}

fun main() {
    Database.connect("jdbc:h2:mem:test", driver = "org.h2.Driver")

    transaction {
        SchemaUtils.create(Users)

        val user = User.new {
            username = "@me"
            tariff = "test"
            created = Instant.now()
        }
    }
}
```

but i get an error:

```
2022-11-18 11:37:34.476 [main] DEBUG Exposed - SELECT SETTING_VALUE FROM INFORMATION_SCHEMA.SETTINGS WHERE SETTING_NAME = 'MODE'
2022-11-18 11:37:34.485 [main] DEBUG Exposed - CREATE TABLE IF NOT EXISTS USERS (TARIFF VARCHAR(50) NOT NULL, CREATED DATETIME(9) NOT NULL, USERNAME VARCHAR(50) NOT NULL)
2022-11-18 11:37:34.712 [main] DEBUG Exposed - INSERT INTO USERS (CREATED, TARIFF, USERNAME) VALUES ('2022-11-18T11:37:34.697368', 'test', '@me')
Exception in thread "main" java.lang.IllegalStateException: Users.username is not in record set
	at org.jetbrains.exposed.sql.ResultRow.setInternal(ResultRow.kt:49)
	at org.jetbrains.exposed.sql.ResultRow.set(ResultRow.kt:44)
	at org.jetbrains.exposed.dao.Entity.storeWrittenValues(Entity.kt:292)
	at org.jetbrains.exposed.dao.EntityCache.flushInserts$exposed_dao(EntityCache.kt:201)
	at org.jetbrains.exposed.dao.EntityCache.flush(EntityCache.kt:138)
	at org.jetbrains.exposed.dao.EntityCache.flush(EntityCache.kt:107)
	at org.jetbrains.exposed.dao.EntityCacheKt.flushCache(EntityCache.kt:243)
	at org.jetbrains.exposed.dao.EntityLifecycleInterceptor.beforeCommit(EntityLifecycleInterceptor.kt:73)
	at org.jetbrains.exposed.sql.Transaction.commit(Transaction.kt:69)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction$run(ThreadLocalTransactionManager.kt:215)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.access$inTopLevelTransaction$run(ThreadLocalTransactionManager.kt:1)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$inTopLevelTransaction$1.invoke(ThreadLocalTransactionManager.kt:240)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:248)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction(ThreadLocalTransactionManager.kt:239)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$transaction$1.invoke(ThreadLocalTransactionManager.kt:189)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:248)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:159)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:146)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction$default(ThreadLocalTransactionManager.kt:145)
	at TestKt.main(Test.kt:30)
	at TestKt.main(Test.kt)
```

If you use `IntIdTable`, then there will be no error, but I want to have a table with a string id. I use Exposed 0.41.1

**Comment by Tolsi** [comment]
Linked to #1548. and ok, i remembered that making string as primary key in relational databases is not the best idea.

**Comment by Tolsi** [comment]
Found [this workaround](https://stackoverflow.com/questions/61938730/string-primary-key-with-jetbrains-exposed-library-kotlin/61940820#61940820) in docs
Besides this looks like a duplicate and there is a workaround, I will close this issue
