### ISSUE TITLE
IdentifierManagerApi throws error when it has been accessed from multiple threads

### ISSUE THREAD

**Issue by KengoTODA** [JetBrains/Exposed#1704]
Hello,

Today I found the following exception in my system, which seems that the `LinkedHashMap` used by `IdentifierManagerApi` had been accessed from mutliple threads (refs https://bugs.openjdk.org/browse/JDK-8173671).

Our code is quite simple as follows, but the `toList()` throws the exception. 

```kotlin
  return transaction(db) {
    FooRecord.find {
      ...
    }.orderBy(...).toList()
  }
```

According to my research [`JdbcDatabaseMetadataImpl` caches the instance of `JdbcIdentifierManager`](https://github.com/JetBrains/Exposed/blob/0.41.1/exposed-jdbc/src/main/kotlin/org/jetbrains/exposed/sql/statements/jdbc/JdbcDatabaseMetadataImpl.kt#LL270C44-L270C61) but its cache key is a URL, so it seems that `JdbcIdentifierManager` is intended to be shared amonth threads.

Then I believe `IdentifiersCache` instances should be wrapped by `Collections.synchronizedMap()`... but I may miss several points to debug, please kindly point any misunderstanding.

I use Exposed 0.41.1 with Kotlin 1.8.10. I've checked changelogs and commit histories, it seems that there is no other issues/fixes regarding this `ClassCastException`. Thanks for your support.

```
java.lang.ClassCastException: class java.util.LinkedHashMap$Entry cannot be cast to class java.util.HashMap$TreeNode (java.util.LinkedHashMap$Entry and java.util.HashMap$TreeNode are in module java.base of loader 'bootstrap')
    at java.util.HashMap$TreeNode.moveRootToFront
    at java.util.HashMap$TreeNode.treeify
    at java.util.HashMap.treeifyBin
    at java.util.HashMap.putVal
    at java.util.HashMap.put
    at org.jetbrains.exposed.sql.statements.api.IdentifierManagerApi.inProperCase(IdentifierManagerApi.kt:128)
    at org.jetbrains.exposed.sql.vendors.DefaultKt.inProperCase(Default.kt:903)
    at org.jetbrains.exposed.sql.Transaction$fullIdentity$2.invoke(Transaction.kt:176)
    at org.jetbrains.exposed.sql.Transaction$fullIdentity$2.invoke(Transaction.kt:172)
    at org.jetbrains.exposed.sql.QueryBuilder.invoke(Expression.kt:18)
    at org.jetbrains.exposed.sql.Transaction.fullIdentity$exposed_core(Transaction.kt:172)
    at org.jetbrains.exposed.sql.Column.toQueryBuilder(Column.kt:39)
    at org.jetbrains.exposed.sql.QueryBuilder.append(Expression.kt:57)
    at org.jetbrains.exposed.sql.QueryBuilder.unaryPlus(Expression.kt:66)
    at org.jetbrains.exposed.sql.Query$prepareSQL$1$1.invoke(Query.kt:117)
    at org.jetbrains.exposed.sql.Query$prepareSQL$1$1.invoke(Query.kt:117)
    at org.jetbrains.exposed.sql.QueryBuilder.appendTo(Expression.kt:30)
    at org.jetbrains.exposed.sql.QueryBuilder.appendTo$default(Expression.kt:21)
    at org.jetbrains.exposed.sql.Query$prepareSQL$1.invoke(Query.kt:117)
    at org.jetbrains.exposed.sql.Query$prepareSQL$1.invoke(Query.kt:108)
    at org.jetbrains.exposed.sql.QueryBuilder.invoke(Expression.kt:18)
    at org.jetbrains.exposed.sql.Query.prepareSQL(Query.kt:108)
    at org.jetbrains.exposed.sql.AbstractQuery.arguments(AbstractQuery.kt:35)
    at org.jetbrains.exposed.sql.AbstractQuery.arguments(AbstractQuery.kt:8)
    at org.jetbrains.exposed.sql.statements.Statement.executeIn$exposed_core(Statement.kt:31)
    at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:141)
    at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:127)
    at org.jetbrains.exposed.sql.AbstractQuery.iterator(AbstractQuery.kt:61)
    at org.jetbrains.exposed.sql.IterableExKt$mapLazy$1.iterator(IterableEx.kt:136)
    at kotlin.collections.CollectionsKt___CollectionsKt.toCollection(_Collections.kt:1295)
    at kotlin.collections.CollectionsKt___CollectionsKt.toMutableList(_Collections.kt:1328)
    at kotlin.collections.CollectionsKt___CollectionsKt.toList(_Collections.kt:1319)
```

**Comment by KengoTODA** [comment]
Seems that the cause was my code, simply reverted a change then everything worked fine.

Even though the reason is still unclear, I'll close this issue. Thanks!

**Comment by m-mercuri** [comment]
We just had this same error on our production instance. @KengoTODA, in your case, what was the change that produced this error?
Thanks!

**Comment by dzikoysk** [comment]
Just got pretty much the same exception:

```
java.lang.ClassCastException: class java.util.LinkedHashMap$Entry cannot be cast to class java.util.HashMap$TreeNode (java.util.LinkedHashMap$Entry and java.util.HashMap$TreeNode are in module java.base of loader 'bootstrap')
    at java.util.HashMap$TreeNode.moveRootToFront
    at java.util.HashMap$TreeNode.treeify
    at java.util.HashMap.treeifyBin
    at java.util.HashMap.putVal
    at java.util.HashMap.put
    at org.jetbrains.exposed.sql.statements.api.IdentifierManagerApi.needQuotes(IdentifierManagerApi.kt:174)
    at org.jetbrains.exposed.sql.statements.api.IdentifierManagerApi.quoteTokenIfNecessary(IdentifierManagerApi.kt:149)
    at org.jetbrains.exposed.sql.statements.api.IdentifierManagerApi.quoteIfNecessary(IdentifierManagerApi.kt:132)
    at org.jetbrains.exposed.sql.statements.api.IdentifierManagerApi.quoteIdentifierWhenWrongCaseOrNecessary(IdentifierManagerApi.kt:142)
    at org.jetbrains.exposed.sql.Transaction.identity(Transaction.kt:299)
    at org.jetbrains.exposed.sql.Transaction$fullIdentity$2.invoke(Transaction.kt:295)
    at org.jetbrains.exposed.sql.Transaction$fullIdentity$2.invoke(Transaction.kt:288)
    at org.jetbrains.exposed.sql.QueryBuilder.invoke(Expression.kt:19)
    at org.jetbrains.exposed.sql.Transaction.fullIdentity$exposed_core(Transaction.kt:288)
    at org.jetbrains.exposed.sql.Column.toQueryBuilder(Column.kt:47)
    at org.jetbrains.exposed.sql.QueryBuilder.append(Expression.kt:58)
    at org.jetbrains.exposed.sql.ExpressionKt.append(Expression.kt:121)
    at org.jetbrains.exposed.sql.Join$JoinPart$appendConditions$1$1.invoke(Table.kt:385)
    at org.jetbrains.exposed.sql.Join$JoinPart$appendConditions$1$1.invoke(Table.kt:385)
    at org.jetbrains.exposed.sql.QueryBuilder.appendTo(Expression.kt:31)
    at org.jetbrains.exposed.sql.ExpressionKt.appendTo(Expression.kt:134)
    at org.jetbrains.exposed.sql.ExpressionKt.appendTo$default(Expression.kt:128)
    at org.jetbrains.exposed.sql.Join$JoinPart$appendConditions$1.invoke(Table.kt:385)
    at org.jetbrains.exposed.sql.Join$JoinPart$appendConditions$1.invoke(Table.kt:384)
    at org.jetbrains.exposed.sql.QueryBuilder.invoke(Expression.kt:19)
    at org.jetbrains.exposed.sql.Join$JoinPart.appendConditions(Table.kt:384)
    at org.jetbrains.exposed.sql.Join$JoinPart.describe(Table.kt:379)
    at org.jetbrains.exposed.sql.Join$describe$1.invoke(Table.kt:275)
    at org.jetbrains.exposed.sql.Join$describe$1.invoke(Table.kt:272)
    at org.jetbrains.exposed.sql.QueryBuilder.invoke(Expression.kt:19)
    at org.jetbrains.exposed.sql.Join.describe(Table.kt:272)
    at org.jetbrains.exposed.sql.Query$prepareSQL$2.invoke(Query.kt:151)
    at org.jetbrains.exposed.sql.Query$prepareSQL$2.invoke(Query.kt:138)
    at org.jetbrains.exposed.sql.QueryBuilder.invoke(Expression.kt:19)
    at org.jetbrains.exposed.sql.Query.prepareSQL(Query.kt:138)
    at org.jetbrains.exposed.sql.AbstractQuery.arguments(AbstractQuery.kt:47)
    at org.jetbrains.exposed.sql.AbstractQuery.arguments(AbstractQuery.kt:9)
    at org.jetbrains.exposed.sql.statements.Statement.executeIn$exposed_core(Statement.kt:63)
    at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:255)
    at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:232)
    at org.jetbrains.exposed.sql.AbstractQuery.iterator(AbstractQuery.kt:78)
    at org.jetbrains.exposed.sql.IterableExKt$mapLazy$1.iterator(IterableEx.kt:168)
    at xxx$$inlined$groupingBy$1.sourceIterator(_Collections.kt:1537)
```

Literally just calling `query.mapLazy { Dto(id = result[Table.id] /* + some other data from result row */) }.groupingBy { it.id }`, only one thread involved on the query side. One time error, so a bit hard to reproduce on my side, but I'd say there's something wrong with the transaction manager, because probably that's were multiple threads can get involved. 

Kotlin: 1.9.23
Exposed: 0.49.0

**Comment by dzikoysk** [comment]
@fokkoru it might be a good idea to report it on YouTrack these days
