### ISSUE TITLE
Cross References

### ISSUE THREAD

**Issue by PaulMuriithi** [JetBrains/Exposed#185]
I am wondering why this does not work, if I have 2 tables as below where a User belongs to a team and a team has a lead who is a User;

Teams:
```
object Teams : IntIdTable() {
    val lead = reference("leadId", Users)
    ... other properties
}

class Team(id: EntityID<Int>) : IntEntity(id) {
    companion object : IntEntityClass<Team>(Teams)

    var lead by User referencedOn Teams.lead
    ... other properties
}
```

Users:
```
object Users : IntIdTable() {
    val team = reference("teamId", Teams)
    ... other properties
}

class User(id: EntityID<Int>) : IntEntity(id) {
    companion object : IntEntityClass<User>(Users)

    var team by Team referencedOn Users.team
    ... other properties
}
```

when I try to create them, I am getting the following exception:
```
[main] INFO Exposed - Transaction attempt #0: Cannot add foreign key constraint. Statement: com.mysql.cj.jdbc.PreparedStatement@189cbd7c: CREATE TABLE IF NOT EXISTS Teams (id INT AUTO_INCREMENT PRIMARY KEY, leadId INT NOT NULL,  FOREIGN KEY (leadId) REFERENCES Users(id) ON DELETE RESTRICT)
java.sql.SQLException: Cannot add foreign key constraint
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:545)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:513)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:115)
	at com.mysql.cj.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:1983)
	at com.mysql.cj.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1826)
	at com.mysql.cj.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2034)
	at com.mysql.cj.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:1970)
	at com.mysql.cj.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5001)
	at com.mysql.cj.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1955)
	at org.jetbrains.exposed.sql.Transaction$exec$2.executeInternal(Transaction.kt:86)
	at org.jetbrains.exposed.sql.statements.Statement.executeIn$exposed_main(Statement.kt:55)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:103)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:97)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:82)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:76)
	at org.jetbrains.exposed.sql.SchemaUtils.create(SchemaUtils.kt:101)
	at db.DbInitKt$main$1.invoke(DbInit.kt:13)
	at db.DbInitKt$main$1.invoke(DbInit.kt)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction(ThreadLocalTransactionManager.kt:73)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:61)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:52)
	at db.DbInitKt.main(DbInit.kt:11)
```

**Comment by Tapac** [comment]
I guess it's impossible to create two tables which simultaneously reference each other.
The first table (Team) wants to refer to the second table (Users) which doesn't exist yet.  And visa-versa. 
 
More other you can't insert team without inserting user which also requires a team. It's cyclic problem in your schema. 
![Uroboros](https://historytime.ru/wp-content/uploads/2016/06/1-6-770x458.jpg)

You should make one of the reference optional. And create a scheme in few steps:
1. Create Team without reference to Users
2. Create Users
3. Adjust Team in code by adding an optional reference to Users.
Please use SchemaUtils.createMissingTablesAndColumns function which know how to add new columns to existing tables.

**Comment by PaulMuriithi** [comment]
Thanks for your answer and suggestions. They have been of great help.

**Comment by oshai** [comment]
I added it to wiki: https://github.com/JetBrains/Exposed/wiki/FAQ#q-is-it-possible-to-create-tables-with-cross--cyclic-reference

**Comment by Tapac** [comment]
After the next release (0.10.6) it will be possible to create cyclic referenced tables without any additional workarounds.

**Comment by mirfatif** [comment]
https://jetbrains.github.io/Exposed/frequently-asked-questions.html#q-is-it-possible-to-create-tables-with-cross-cyclic-reference states:

> **Q: Is it possible to create tables with cross / cyclic reference?**
> A: Yes, it's possible since Exposed 0.11.1 version

But how? Using the `createMissingTablesAndColumns()`? Or `optReference()`?

Also not clear from the [test](https://github.com/JetBrains/Exposed/blob/0.52.0/exposed-tests/src/test/kotlin/org/jetbrains/exposed/sql/tests/shared/DDLTests.kt#L755):
```
    object Table1 : IntIdTable() {
        val table2 = reference("teamId", Table2, onDelete = ReferenceOption.NO_ACTION)
    }

    object Table2 : IntIdTable() {
        val table1 = optReference("teamId", Table1, onDelete = ReferenceOption.NO_ACTION)
    }

    @Test
    fun testCrossReference() {
        withTables(Table1, Table2) {
            val table2id = Table2.insertAndGetId {}
            val table1id = Table1.insertAndGetId {
                it[table2] = table2id
            }

            Table2.insertAndGetId {
                it[table1] = table1id
            }

            assertEquals(1L, Table1.selectAll().count())
            assertEquals(2L, Table2.selectAll().count())

            Table2.update {
                it[table1] = null
            }

            Table1.deleteAll()
            Table2.deleteAll()

            if (currentDialectTest !is SQLiteDialect) {
                exec(Table2.table1.foreignKey!!.dropStatement().single())
            }
        }
    }
```
