### ISSUE TITLE
SQLite: Column names not being quoted causes SQLiteException

### ISSUE THREAD

**Issue by SackCastellon** [JetBrains/Exposed#211]
## Description
Creating a table in an SQLite database when the table name is a reserved word, causes the database driver to throw an SQLiteException because the driver interprets it as a statement instead of as a table name.

### Example 1
```kotlin
import org.jetbrains.exposed.sql.*
import org.jetbrains.exposed.sql.SchemaUtils.create
import org.jetbrains.exposed.sql.SchemaUtils.drop
import org.jetbrains.exposed.sql.transactions.*
import java.sql.Connection

object Test : Table() {
    val group = integer("group")
}

fun main(args: Array<String>) {
    Database.connect("jdbc:sqlite:D:/sqlite.db", "org.sqlite.JDBC",
            manager = { ThreadLocalTransactionManager(it, Connection.TRANSACTION_SERIALIZABLE) })

    transaction {
        logger.addLogger(StdOutSqlLogger)
        create(Test)
        drop(Test)
    }
}
```
The previous code throws the following exception
```
Exception in thread "main" org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (near "group": syntax error)
	at org.sqlite.core.DB.newSQLException(DB.java:909)
	at org.sqlite.core.DB.newSQLException(DB.java:921)
	at org.sqlite.core.DB.throwex(DB.java:886)
	at org.sqlite.core.NativeDB.prepare_utf8(Native Method)
	at org.sqlite.core.NativeDB.prepare(NativeDB.java:127)
	at org.sqlite.core.DB.prepare(DB.java:227)
	at org.sqlite.core.CorePreparedStatement.<init>(CorePreparedStatement.java:41)
	at org.sqlite.jdbc3.JDBC3PreparedStatement.<init>(JDBC3PreparedStatement.java:30)
	at org.sqlite.jdbc4.JDBC4PreparedStatement.<init>(JDBC4PreparedStatement.java:19)
	at org.sqlite.jdbc4.JDBC4Connection.prepareStatement(JDBC4Connection.java:48)
	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:263)
	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:235)
	at org.sqlite.jdbc3.JDBC3Connection.prepareStatement(JDBC3Connection.java:242)
	at org.jetbrains.exposed.sql.statements.Statement.prepared(Statement.kt:23)
	at org.jetbrains.exposed.sql.statements.Statement.executeIn$exposed(Statement.kt:46)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:103)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:97)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:82)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:76)
	at org.jetbrains.exposed.sql.SchemaUtils.create(SchemaUtils.kt:101)
	at SQLTestKt$main$2.invoke(SQLTest.kt:17)
	at SQLTestKt$main$2.invoke(SQLTest.kt)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction(ThreadLocalTransactionManager.kt:92)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:64)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:55)
	at SQLTestKt.main(SQLTest.kt:15)
```
### Example 2
This is another example but this time with the table name changed to make it work
```kotlin
import org.jetbrains.exposed.sql.*
import org.jetbrains.exposed.sql.SchemaUtils.create
import org.jetbrains.exposed.sql.SchemaUtils.drop
import org.jetbrains.exposed.sql.transactions.*
import java.sql.Connection

object Test : Table() {
    val groups = integer("groups")
}

fun main(args: Array<String>) {
    Database.connect("jdbc:sqlite:D:/sqlite.db", "org.sqlite.JDBC",
            manager = { ThreadLocalTransactionManager(it, Connection.TRANSACTION_SERIALIZABLE) })

    transaction {
        logger.addLogger(StdOutSqlLogger)
        create(Test)
        drop(Test)
    }
}
```
And this is the output of the working example
```
SQL: CREATE TABLE IF NOT EXISTS Test (groups INT NOT NULL)
SQL: DROP TABLE  IF EXISTS Test
```
## Environment
IntelliJ IDEA 2017.3
JRE: 1.8.0_152-release-1024-b6 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
SQLite Driver: 3.21.0 (via Maven)
## Possible related issues
- #192

**Comment by Tapac** [comment]
Exposed relies on jdbc DatabaseMetadata.getKeywords() values to ensure which identifiers should be escaped, but looks like SQLite driver doesn't provide any of them ([source of driver](https://bitbucket.org/xerial/sqlite-jdbc/src/8de652d3f54cdfd32d5a493130c995f36e16c652/src/main/java/org/sqlite/MetaData.java?at=default&fileviewer=file-view-default#MetaData.java-482)).
I will temporary add [SQLIte keywords](https://sqlite.org/lang_keywords.html) to Exposed SQLiteDialect and create PR to jdbc-driver project.

**Comment by Tapac** [comment]
@SackCastellon , I found out that driver sources moved to [github](https://github.com/xerial/sqlite-jdbc) and keyword issue was fixed there, but not released yet. But in closer look, I found that current stable driver doesn't provide quote character (#getIdentifierQuoteString), what also fixed at master.

You may use `org.xerial:sqlite-jdbc:3.21.1-SNAPSHOT` without a need to wait for Exposed release to workaround your issue.

**Comment by SackCastellon** [comment]
Ok, thank you.
