### ISSUE TITLE
'SELECT MAX(datetime)' throws ClassCastException

### ISSUE THREAD

**Issue by SackCastellon** [JetBrains/Exposed#279]
When running this code, using Kotlin 1.2.31 and Exposed 0.10.2:
```kotlin
fun main(args: Array<String>) {
    Database.connect("jdbc:sqlite::memory:", "org.sqlite.JDBC", manager = { ThreadLocalTransactionManager(it, Connection.TRANSACTION_SERIALIZABLE) })

    transaction {
        create(Data)

        for (i in 1..12) Data.insert { it[dateTime] = DateTime(2018, i, i * 2, 0, 0, 0, 0) }

        val maxDateTime = Data.dateTime.max().alias("maxDateTime")

        Data.slice(maxDateTime).selectAll().forEach {
            val dateTime: DateTime = it[maxDateTime]!! // Exception thrown here
            println(dateTime)
        }

        drop(Data)
    }
}

object Data : Table() {
    val dateTime: Column<DateTime> = datetime("dateTime")
}
```
I get this exception thrown:
```plain
Exception in thread "main" java.lang.ClassCastException: java.lang.Long cannot be cast to org.joda.time.DateTime
	at MainKt$main$2.invoke(Main.kt:20)
	at MainKt$main$2.invoke(Main.kt)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction(ThreadLocalTransactionManager.kt:101)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:72)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:55)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction$default(ThreadLocalTransactionManager.kt:55)
	at MainKt.main(Main.kt:12)
```
But if I change the type from `org.joda.time.DateTime` to `kotlin.Int` everything works fine.
Is this a bug or am I doing anything wrong?

**Comment by Tapac** [comment]
Thank you for a report. This is a bug in ResultRow, which doesn't know about ExpressionAlias. 
Now it is fixed in master and will be released today after all test will pass on TeamCity.
