### ISSUE TITLE
Update Limit not working with PostgreSQL

### ISSUE THREAD

**Issue by AllanWang** [JetBrains/Exposed#287]
(This is my first time working with databases. I'm not sure if this issue is relevant to exposed, but I am posting nonetheless)

With PostgreSQL v10, and drivers 42.2.2 from gradle, calling `Table.update(..., 1)` with a limit does not work:

```
org.postgresql.util.PSQLException: ERROR: syntax error at or near "LIMIT"
  Position: 108

	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2433)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2178)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:306)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:155)
	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:132)
	at org.jetbrains.exposed.sql.statements.UpdateStatement.executeInternal(UpdateStatement.kt:13)
	at org.jetbrains.exposed.sql.statements.UpdateStatement.executeInternal(UpdateStatement.kt:6)
	at org.jetbrains.exposed.sql.statements.Statement.executeIn$exposed(Statement.kt:55)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:111)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:105)
	at org.jetbrains.exposed.sql.statements.Statement.execute(Statement.kt:27)
	at org.jetbrains.exposed.sql.QueriesKt.update(Queries.kt:132)
```

The call works fine without adding a limit, so maybe the syntax order has changed?

**Comment by Tapac** [comment]
Sad, but postgresql doesn't support UPDATE... LIMIT syntax:
https://www.postgresql.org/docs/9.5/static/sql-update.html
I guess it worth to throw a more meaningful exception when you try to call Exposed update with a limit param.

**Comment by Tapac** [comment]
Fixed in master. UnsupportedByDialectException will be thrown when an update function called with limit parameter

**Comment by honglou2001** [comment]
I encounter the same issue. which jar version should I use?
