### ISSUE TITLE
org.h2.Driver not found

### ISSUE THREAD

**Issue by KingIdee** [JetBrains/Exposed#297]
I am getting this error:

```
Exception in thread "main" java.lang.ClassNotFoundException: org.h2.Driver
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at org.jetbrains.exposed.sql.Database$Companion.connect(Database.kt:102)
        at org.jetbrains.exposed.sql.Database$Companion.connect$default(Database.kt:101)
        at MainKt.main(Main.kt:30)
```

**Comment by raharrison** [comment]
Do you have H2 in your classpath? Add `compile group: 'com.h2database', name: 'h2', version: '1.4.197'` to your gradle
