### ISSUE TITLE
PSQLException : Transaction isolation level 4 not supported

### ISSUE THREAD

**Issue by brabo-hi** [JetBrains/Exposed#302]
Trying to create table (postgres + exposed + ktor), i got that error

**build.gradle**
             compile group: 'postgresql', name: 'postgresql', version: '9.0-801.jdbc4'

**Hello.kt**
object Pays : Table() {
    val id = integer("id").autoIncrement().primaryKey() // Column<Int>
    val name = varchar("name", 50) // Column<String>
}

fun main(args: Array<String>) {
    Database.connect("jdbc:postgresql://localhost/my_db", driver = "org.postgresql.Driver", user = "user", password = "password")

    transaction {
        logger.addLogger(StdOutSqlLogger)
        create (Pays)
    }
}

**ERROR**
Exception in thread "main" java.lang.ExceptionInInitializerError
	at pages.HelloKt$main$1.invoke(Hello.kt:18)
	at pages.HelloKt$main$1.invoke(Hello.kt)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction(ThreadLocalTransactionManager.kt:101)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:72)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:55)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction$default(ThreadLocalTransactionManager.kt:55)
	at pages.HelloKt.main(Hello.kt:16)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at kotlin.reflect.jvm.internal.FunctionCaller$Method.callMethod(FunctionCaller.kt:98)
	at kotlin.reflect.jvm.internal.FunctionCaller$InstanceMethod.call(FunctionCaller.kt:115)
	at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:107)
	at kotlin.reflect.jvm.internal.KProperty1Impl.get(KProperty1Impl.kt:33)
	at org.jetbrains.exposed.sql.Table.clone(Table.kt:207)
	at org.jetbrains.exposed.sql.Table.cloneWithAutoInc(Table.kt:328)
	at org.jetbrains.exposed.sql.Table.autoIncrement(Table.kt:332)
	at org.jetbrains.exposed.sql.Table.autoIncrement$default(Table.kt:332)
	at pages.Pays.<clinit>(Hello.kt:9)
	... 7 more
Caused by: org.postgresql.util.PSQLException: Transaction isolation level 4 not supported.
	at org.postgresql.jdbc2.AbstractJdbc2Connection.setTransactionIsolation(AbstractJdbc2Connection.java:826)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManager$ThreadLocalTransaction$connectionLazy$1.invoke(ThreadLocalTransactionManager.kt:25)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManager$ThreadLocalTransaction$connectionLazy$1.invoke(ThreadLocalTransactionManager.kt:20)
	at kotlin.UnsafeLazyImpl.getValue(Lazy.kt:154)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManager$ThreadLocalTransaction.getConnection(ThreadLocalTransactionManager.kt:29)
	at org.jetbrains.exposed.sql.Transaction.getConnection(Transaction.kt)
	at org.jetbrains.exposed.sql.Database.getMetadata$exposed(Database.kt:17)
	at org.jetbrains.exposed.sql.Database$url$2.invoke(Database.kt:26)
	at org.jetbrains.exposed.sql.Database$url$2.invoke(Database.kt:15)
	at kotlin.SynchronizedLazyImpl.getValue(Lazy.kt:131)
	at org.jetbrains.exposed.sql.Database.getUrl(Database.kt)
	at org.jetbrains.exposed.sql.Database$dialect$2.invoke(Database.kt:29)
	at org.jetbrains.exposed.sql.Database$dialect$2.invoke(Database.kt:15)
	at kotlin.SynchronizedLazyImpl.getValue(Lazy.kt:131)
	at org.jetbrains.exposed.sql.Database.getDialect$exposed(Database.kt)
	at org.jetbrains.exposed.sql.vendors.DefaultKt.getCurrentDialect(Default.kt:319)
	at org.jetbrains.exposed.sql.vendors.DefaultKt.getCurrentDialectIfAvailable(Default.kt:323)
	at org.jetbrains.exposed.sql.Column.getOnDelete$exposed(Column.kt:14)
	... 20 more

**Comment by Tapac** [comment]
Please, provide PostgreSQL server  version.
Also, you may try to update jdbc driver to 'org.postgresql:postgresql:42.2.2.jre6'

**Comment by brabo-hi** [comment]
I'm running on PostgreSQL 10

**Comment by Tapac** [comment]
Update your jdbc driver to 'org.postgresql:postgresql:42.2.2' or 'org.postgresql:postgresql:9.4.1212'

**Comment by brabo-hi** [comment]
Problem fixed, after updating to  compile "org.postgresql:postgresql:42.2.2", thanks @Tapac
