### ISSUE TITLE
Sqlite transaction execution error

### ISSUE THREAD

**Issue by AlphaFase** [JetBrains/Exposed#307]
### exposed: 0.10.2
> Sqlite transaction exit error
```ktor
import org.jetbrains.exposed.dao.IntIdTable
import org.jetbrains.exposed.sql.*
import org.jetbrains.exposed.sql.transactions.DEFAULT_ISOLATION_LEVEL
import org.jetbrains.exposed.sql.transactions.TransactionManager
import org.jetbrains.exposed.sql.transactions.inTopLevelTransaction
import org.jetbrains.exposed.sql.transactions.transaction
import java.sql.Connection
import java.sql.DriverManager

object GjjInfo: Table() {
    val phone = varchar("sjhm", length = 25)
}
fun main(args: Array<String>) {
    val dataFile = """F:\data\gjj_code\data.db"""
    val db = Database.connect("jdbc:sqlite:${dataFile}", "org.sqlite.JDBC")
    TransactionManager.manager.defaultIsolationLevel = Connection.TRANSACTION_SERIALIZABLE
    transaction {
        logger.addLogger(StdOutSqlLogger)
        println(GjjInfo.select({ GjjInfo.phone like "1%"}).count())
    }     // Sqlite transaction exit error
    println(1)

}
```

```
Exception in thread "main" java.lang.AbstractMethodError: Method org/sqlite/PrepStmt.isClosed()Z is abstract
	at org.sqlite.PrepStmt.isClosed(PrepStmt.java)
	at org.jetbrains.exposed.sql.Transaction.closeExecutedStatements(Transaction.kt:162)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction(ThreadLocalTransactionManager.kt:127)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:72)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:55)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction$default(ThreadLocalTransactionManager.kt:55)
	at MainKt.main(main.kt:17)
```

**Comment by Tapac** [comment]
Which version of sqlite driver do you use?

**Comment by AlphaFase** [comment]
compile group: 'org.xerial', name: 'sqlite-jdbc', version: '3.7.2'

**Comment by Tapac** [comment]
Please try latest version: org.xerial:sqlite-jdbc:3.21.0.1
