### ISSUE TITLE
IllegalArgumentException when trying to create tables(Android)

### ISSUE THREAD

**Issue by Miggets7** [JetBrains/Exposed#315]
I'm using 0.10.2 of exposed in Android and get the following exception:
```
Caused by: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter $receiver
                      at kotlin.text.StringsKt__StringsKt.removePrefix(Strings.kt)
                      at org.jetbrains.exposed.sql.Database$dialect$2.invoke(Database.kt:29)
                      at org.jetbrains.exposed.sql.Database$dialect$2.invoke(Database.kt:15)
                      at kotlin.SynchronizedLazyImpl.getValue(Lazy.kt:131)
                      at org.jetbrains.exposed.sql.Database.getDialect$exposed(Database.kt)
                      at org.jetbrains.exposed.sql.vendors.DefaultKt.getCurrentDialect(Default.kt:319)
                      at org.jetbrains.exposed.sql.vendors.DefaultKt.getCurrentDialectIfAvailable(Default.kt:323)
                      at org.jetbrains.exposed.sql.Column.getOnDelete$exposed(Column.kt:14)
```

This is the code used:

    val databaseFile = File(applicationContext.getDir("data", Context.MODE_PRIVATE), "vgDB.db")
    Database.connect("jdbc:sqlite:${databaseFile.path}", "org.sqldroid.SQLDroidDriver")
    
        transaction {
            create(Tasks, TapRegistrations)
        }

I tried using the `org.sqlite.JDBC` driver, but get the following error:
```
Caused by: java.lang.reflect.InvocationTargetException
                      at java.lang.reflect.Method.invoke(Native Method)
                      at kotlin.reflect.jvm.internal.FunctionCaller$Method.callMethod(FunctionCaller.kt:98)
                      at kotlin.reflect.jvm.internal.FunctionCaller$InstanceMethod.call(FunctionCaller.kt:115)
                      at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:107)
                      at kotlin.reflect.jvm.internal.KProperty1Impl.get(KProperty1Impl.kt:33)
                      at org.jetbrains.exposed.sql.Table.clone(Table.kt:207)
                      at org.jetbrains.exposed.sql.Table.cloneWithAutoInc(Table.kt:328)
                      at org.jetbrains.exposed.sql.Table.autoIncrement(Table.kt:332)
                      at org.jetbrains.exposed.sql.Table.autoIncrement$default(Table.kt:332)
                      at org.jetbrains.exposed.dao.IntIdTable.<init>(IntEntity.kt:6)
                      at org.jetbrains.exposed.dao.IntIdTable.<init>(IntEntity.kt:5)
                      at com.appbriek.vigilancebuddy.model.Tasks.<init>(Task.kt:8)
                      at com.appbriek.vigilancebuddy.model.Tasks.<clinit>(Task.kt:8)
                      at com.appbriek.vigilancebuddy.VigilanceBuddyApplication$onCreate$1.invoke(VigilanceBuddyApplication.kt:28) 
                      at com.appbriek.vigilancebuddy.VigilanceBuddyApplication$onCreate$1.invoke(VigilanceBuddyApplication.kt:18) 
                      at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction(ThreadLocalTransactionManager.kt:101) 
                      at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:72) 
                      at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:55) 
                      at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction$default(ThreadLocalTransactionManager.kt:55) 
                      at com.appbriek.vigilancebuddy.VigilanceBuddyApplication.onCreate(VigilanceBuddyApplication.kt:27) 
                      at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1024) 
                      at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5545) 
                      at android.app.ActivityThread.-wrap2(ActivityThread.java) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1612) 
                      at android.os.Handler.dispatchMessage(Handler.java:110) 
                      at android.os.Looper.loop(Looper.java:203) 
                      at android.app.ActivityThread.main(ActivityThread.java:6293) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1084) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:945) 
                   Caused by: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.appbriek.vigilancebuddy-2/base.apk"],nativeLibraryDirectories=[/data/app/com.appbriek.vigilancebuddy-2/lib/arm64, /system/lib64, /vendor/lib64]]] couldn't find "libsqlitejdbc.so"
                      at java.lang.Runtime.loadLibrary0(Runtime.java:984)
                      at java.lang.System.loadLibrary(System.java:1530)
                      at org.sqlite.core.NativeDB.<clinit>(NativeDB.java:38)
                      at org.sqlite.core.NativeDB.load(NativeDB.java:53)
                      at org.sqlite.core.CoreConnection.open(CoreConnection.java:211)
                      at org.sqlite.core.CoreConnection.<init>(CoreConnection.java:76)
                      at org.sqlite.jdbc3.JDBC3Connection.<init>(JDBC3Connection.java:25)
                      at org.sqlite.jdbc4.JDBC4Connection.<init>(JDBC4Connection.java:24)
                      at org.sqlite.SQLiteConnection.<init>(SQLiteConnection.java:45)
                      at org.sqlite.JDBC.createConnection(JDBC.java:114)
                      at org.sqlite.JDBC.connect(JDBC.java:88)
                      at java.sql.DriverManager.getConnection(DriverManager.java:569)
                      at java.sql.DriverManager.getConnection(DriverManager.java:219)
                      at org.jetbrains.exposed.sql.Database$Companion$connect$7.invoke(Database.kt:104)
                      at org.jetbrains.exposed.sql.Database$Companion$connect$7.invoke(Database.kt:63)
                      at org.jetbrains.exposed.sql.Database$Companion$doConnect$3.invoke(Database.kt:83)
                      at org.jetbrains.exposed.sql.Database$Companion$doConnect$3.invoke(Database.kt:63)
```

Could you guys help out? Thank you!

**Comment by Tapac** [comment]
Looks like an issue in SQLite driver (https://github.com/xerial/sqlite-jdbc/issues/248)
