### ISSUE TITLE
createInstance gives a out invocation error

### ISSUE THREAD

**Issue by lephyrius** [JetBrains/Exposed#324]
I get this error:

```
java.lang.IllegalArgumentException: wrong number of arguments
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
	at org.jetbrains.exposed.dao.EntityClass.createInstance(Entity.kt:612)
	at org.jetbrains.exposed.dao.EntityClass.wrap(Entity.kt:616)
	at org.jetbrains.exposed.dao.EntityClass.wrapRow(Entity.kt:554)
	at org.jetbrains.exposed.dao.EntityClass$wrapRows$1.invoke(Entity.kt:547)
	at org.jetbrains.exposed.dao.EntityClass$wrapRows$1.invoke(Entity.kt:474)
	at org.jetbrains.exposed.sql.IterableExKt$mapLazy$1$iterator$1.next(IterableEx.kt:88)
	at controllers.ApiController.serializeToGson(ApiController.kt:76)

```
It seems like it is when I get stuff out of the database. 

It seems to work when the default constructor is removed from the model.

**Comment by Tapac** [comment]
Could you provide sample code with Entity/EntityClass mapping?

**Comment by Tapac** [comment]
@lephyrius, after some investigation this behavior can happen when you define an entity as a local or inner class and it captures a reference to an outer class. Try to avoid such definitions.
