### ISSUE TITLE
SQLite autoincrement table is not created correctly 

### ISSUE THREAD

**Issue by xgouchet** [JetBrains/Exposed#328]
I'm testing exposed with a SQLite driver (https://github.com/xerial/sqlite-jdbc). I use the following table definition : 

```
object Polls : Table() {
    val id = integer("id").primaryKey().autoIncrement()
    val question = varchar("question", 255)
}
``` 

And my insert method is doing this : 

```
fun createNewPoll(question : String) : Int?{
        return Polls.insert({ p ->
            p[question] = poll.question
        }) get Polls.id
}
```

But when I try to insert a new entry, leaving the id empty to let the autoincrement do its job, I get the following error : 

```
Caused by: org.sqlite.SQLiteException: [SQLITE_CONSTRAINT_NOTNULL]  A NOT NULL constraint failed (NOT NULL constraint failed: Polls.id)
	at org.sqlite.core.DB.newSQLException(DB.java:909)
	at org.sqlite.core.DB.newSQLException(DB.java:921)
	at org.sqlite.core.DB.execute(DB.java:825)
	at org.sqlite.core.DB.executeUpdate(DB.java:863)
	at org.sqlite.jdbc3.JDBC3PreparedStatement.executeUpdate(JDBC3PreparedStatement.java:102)
	at org.jetbrains.exposed.sql.statements.InsertStatement.execInsertFunction(InsertStatement.kt:86)
	at org.jetbrains.exposed.sql.statements.InsertStatement.executeInternal(InsertStatement.kt:95)
	at org.jetbrains.exposed.sql.statements.InsertStatement.executeInternal(InsertStatement.kt:12)
	at org.jetbrains.exposed.sql.statements.Statement.executeIn$exposed(Statement.kt:59)
	... 24 common frames omitted
```

When looking into the created file, here's what it looks like : 

```
CREATE TABLE Polls (
    id INTEGER AUTO_INCREMENT NOT NULL, 
    question VARCHAR(255) NOT NULL, 
    CONSTRAINT pk_Polls PRIMARY KEY (id)
)
```

which uses `AUTO_INCREMENT` instead of [`AUTOINCREMENT`](https://www.sqlite.org/autoinc.html)

**Comment by Tapac** [comment]
Thank you for a report, strange that none of the unit-tests hit that problem.
Possibly that if there is not `AUTO_INCREMENT` column then `PreparedStatatement.generatedKeys()` returns ROW_ID. 

Release with the fix for that issue will be available on the next week.

**Comment by tapanrgohil** [comment]
@Tapac  
Please merge this commit to master branch as still it is failing in current version.

**Comment by Tapac** [comment]
@tapanrgohil , oh thank you for your attention, I've just noticed that the fix was committed to non-master branch. I'll cherry-pick it and reject your PR.

Release is planned on today-tomorrow.

**Comment by tapanrgohil** [comment]
@tapac actually this prs is from current master branch 6 I think you can merge it
