### ISSUE TITLE
Cycle references detected, can't sort table references

### ISSUE THREAD

**Issue by gcscaglia** [JetBrains/Exposed#42]
Certain model structures cause `SchemaUtils.create` and many other operations to fail with `java.lang.IllegalStateException: Cycle references detected, can't sort table references!`.

This seems to triggered by tables with self-references, but it only when the table has other references as well. On the attached example, removing either reference from `Posts` cause creation to succeed. The Post table should be perfectly valid as is.

Minimal example for bug reproduction:
[cycle-example.zip](https://github.com/JetBrains/Exposed/files/440769/cycle-example.zip)

**Comment by gcscaglia** [comment]
Just in case downloading and running the example is cumbersome or otherwise inviable, here is the offending model:

```kotlin
object Boards : IntIdTable(name = "board") {
    val name = varchar("name", 255).index(isUnique = true)
}

object Posts : IntIdTable(name = "posts") {
    val board = optReference("board", Boards)
    val parent = optReference("parent", Posts)
}
```

The full exception with stacktrace (omitting JUnit stuff) is:
```
java.lang.IllegalStateException: Cycle references detected, can't sort table references!
	at org.jetbrains.exposed.dao.EntityCache$Companion.sortTablesByReferences(Entity.kt:437)
	at org.jetbrains.exposed.sql.SchemaUtils.createStatements(SchemaUtils.kt:15)
	at org.jetbrains.exposed.sql.SchemaUtils.create(SchemaUtils.kt:102)
	at example.TestMetaModels$testCreate$1.invoke(TestMetaModels.kt:22)
	at example.TestMetaModels$testCreate$1.invoke(TestMetaModels.kt:12)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction(ThreadLocalTransactionManager.kt:69)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:57)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:48)
	at example.TestMetaModels.testCreate(TestMetaModels.kt:21)
```

**Comment by guredd** [comment]
@gcscaglia Thank you for reporting this! Will be fixed very soon.

**Comment by guredd** [comment]
Fixed. Test added.
