### ISSUE TITLE
Support PostgreSQL's WITH Queries ?

### ISSUE THREAD

**Issue by ttarcher** [JetBrains/Exposed#423]
How to write a  [`WITH` Queries](https://www.postgresql.org/docs/current/static/queries-with.html) with `Exposed`?
according to #118  this issue.
I write :
```kotlin
TransactionManager.current().exec(
            "WITH RECURSIVE t AS( " +
                "SELECT id,name,parent_id,ARRAY[ID] AS path,1 AS DEPTH FROM categories WHERE parent_id IS null " +
                "UNION ALL " +
                "SELECT c.id,c.name,c.parent_id,t.path || c.id,t.depth + 1 AS depth FROM categories c " +
                "JOIN t on c.parent_id=t.id" +
                ") " +
                "SELECT id,name,parent_id,path,depth FROM t"
        ) {
            ...
        }
```
and get a `ExposedSQLException` :
```
2018-11-05 18:38:52.930 [nettyCallPool-4-1] DEBUG Exposed - WITH RECURSIVE t AS( SELECT id,name,parent_id,ARRAY[ID] AS path,1 AS DEPTH FROM categories WHERE parent_id IS null UNION ALL SELECT c.id,c.name,c.parent_id,t.path || c.id,t.depth + 1 AS depth FROM categories c JOIN t on c.parent_id=t.id) SELECT id,name,parent_id,path,depth FROM t
2018-11-05 18:38:52.932 [nettyCallPool-4-1] INFO  Exposed - Transaction attempt #0 failed: org.postgresql.util.PSQLException: A result was returned when none was expected. Statement(s): WITH RECURSIVE t AS( SELECT id,name,parent_id,ARRAY[ID] AS path,1 AS DEPTH FROM categories WHERE parent_id IS null UNION ALL SELECT c.id,c.name,c.parent_id,t.path || c.id,t.depth + 1 AS depth FROM categories c JOIN t on c.parent_id=t.id) SELECT id,name,parent_id,path,depth FROM t
org.jetbrains.exposed.exceptions.ExposedSQLException: org.postgresql.util.PSQLException: A result was returned when none was expected.
	at org.jetbrains.exposed.sql.statements.Statement.executeIn$exposed(Statement.kt:61)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:128)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:122)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:101)
	at ...
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction(ThreadLocalTransactionManager.kt:104)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:75)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:58)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction$default(ThreadLocalTransactionManager.kt:58)
	at ...
	at io.ktor.locations.LocationKt$handle$1.invokeSuspend(Location.kt:214)
	at io.ktor.locations.LocationKt$handle$1.invoke(Location.kt)
	at io.ktor.util.pipeline.PipelineContext.proceed(PipelineContext.kt:53)
	at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:24)
	at io.ktor.routing.Routing.executeResult(Routing.kt:110)
	at io.ktor.routing.Routing.interceptor(Routing.kt:29)
	at io.ktor.routing.Routing$Feature$install$1.invokeSuspend(Routing.kt:75)
	at io.ktor.routing.Routing$Feature$install$1.invoke(Routing.kt)
	at io.ktor.util.pipeline.PipelineContext.proceed(PipelineContext.kt:53)
	at io.ktor.features.ContentNegotiation$Feature$install$1.invokeSuspend(ContentNegotiation.kt:60)
	at io.ktor.features.ContentNegotiation$Feature$install$1.invoke(ContentNegotiation.kt)
	at io.ktor.util.pipeline.PipelineContext.proceed(PipelineContext.kt:53)
	at io.ktor.features.CallLogging$Feature$install$2.invokeSuspend(CallLogging.kt:124)
	at io.ktor.features.CallLogging$Feature$install$2.invoke(CallLogging.kt)
	at io.ktor.util.pipeline.PipelineContext.proceed(PipelineContext.kt:53)
	at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:24)
	at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$2.invokeSuspend(DefaultEnginePipeline.kt:80)
	at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$2.invoke(DefaultEnginePipeline.kt)
	at io.ktor.util.pipeline.PipelineContext.proceed(PipelineContext.kt:53)
	at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:24)
	at io.ktor.server.netty.NettyApplicationCallHandler$handleRequest$1.invokeSuspend(NettyApplicationCallHandler.kt:31)
	at io.ktor.server.netty.NettyApplicationCallHandler$handleRequest$1.invoke(NettyApplicationCallHandler.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:54)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:111)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:160)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:54)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
	at io.ktor.server.netty.NettyApplicationCallHandler.handleRequest(NettyApplicationCallHandler.kt:22)
	at io.ktor.server.netty.NettyApplicationCallHandler.channelRead(NettyApplicationCallHandler.kt:16)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:38)
	at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:353)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.postgresql.util.PSQLException: A result was returned when none was expected.
	at org.postgresql.jdbc.PgStatement.getNoResultUpdateCount(PgStatement.java:254)
	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:122)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
	at org.jetbrains.exposed.sql.Transaction$exec$2.executeInternal(Transaction.kt:105)
	at org.jetbrains.exposed.sql.statements.Statement.executeIn$exposed(Statement.kt:59)
	... 50 common frames omitted
```
then I found a question [PostgreSQL error: A result was returned when none was expected](https://stackoverflow.com/questions/50765824/postgresql-error-a-result-was-returned-when-none-was-expected)

according to the answer (I don't know it is right or not)
> Using execute() instead of executeUpdate() in Java fixed the problem!

And then I see the source code of  `exec()` 
```kotlin
...
when (type) {
    StatementType.SELECT -> executeQuery()
    else  -> executeUpdate()
}
...
```
So, is there has another way to execute a `WITH` Queries ?

**Comment by Globegitter** [comment]
I am having a `UPDATE ... RETURNING *;` and running into the same issue. Any solution for this?

**Comment by willtrking** [comment]
+1 to adding CTE support, especially as they have started to creep into previously unsupported databases (e.g. Mysql 8 supports CTEs)


For now, I'm using an extension function to support this. This really only works for me since all my CTE's are raw SQL strings anyway

```kotlin
fun <T:Any> Transaction.execCTE(stmt: String, transform: (ResultSet) -> T): T? {
    if (stmt.isEmpty()) return null

    val type = StatementType.SELECT

    return exec(object : Statement<T>(type, emptyList()) {
        override fun PreparedStatement.executeInternal(transaction: Transaction): T? {
            executeQuery()
            return resultSet?.let {
                try {
                    transform(it)
                } finally {
                    it.close()
                }
            }
        }

        override fun prepareSQL(transaction: Transaction): String = stmt

        override fun arguments(): Iterable<Iterable<Pair<ColumnType, Any?>>> = emptyList()
    })
}
```

**Comment by Tapac** [comment]
Explicit statementType for Transaction.exec functions (also, EXEC StatementType was introduced) available since 0.32.1.

**Comment by indeep99** [comment]
For anyone who might still be confused, this is what exec function looks like in Exposed and what @Tapac is referring to:

```
exec(stmt: String, args: Iterable<Pair<IColumnType, Any?>> = emptyList(), explicitStatementType: StatementType? = null)
```

And these are the possible StatementType values:

```kotlin
INSERT(StatementGroup.DML),
UPDATE(StatementGroup.DML),
DELETE(StatementGroup.DML),
SELECT(StatementGroup.DML),
CREATE(StatementGroup.DDL),
ALTER(StatementGroup.DDL),
TRUNCATE(StatementGroup.DDL),
DROP(StatementGroup.DDL),
GRANT(StatementGroup.DDL),
EXEC(StatementGroup.DML),
OTHER(StatementGroup.DDL)
```

**Comment by fokkoru** [comment]
Do we have any updates on adding support for CTEs (Common Table Expressions)?

**Comment by mahramane** [comment]
+++

**Comment by mahramane** [comment]
any update?

**Comment by christopher-trotter-statnett** [comment]
Would love to have this feature. Any updates?

**Comment by mahramane** [comment]
+++

**Comment by Oskar-Przyborski** [comment]
Also waiting for this feature!
