### ISSUE TITLE
Using customEnumeration() with H2 creates database excption messages in db fields

### ISSUE THREAD

**Issue by StefanHub** [JetBrains/Exposed#428]
I am trying to use the customEnumeration() function for defining db specific enum types as explained in: https://github.com/JetBrains/Exposed/wiki/DataTypes#how-to-use-database-enum-types

The code snippet for H2 (1.4.197)
`val newEnumColumn = customEnumeration("enumColumn", "ENUM('Bar', 'Baz')" {Foo.values()[it as Int]}, {it.name})`
is missing a comma ',' I guess.
The toDb() fun uses it.name. I would have expected that it would be it.ordinal since the fromDB() gets an Int.

However, with both variants (name, ordinal) the database fields for the enum type contain the following exception string when inserting entries:
`<failed to load>
org.h2.jdbc.JdbcSQLException: Allgemeiner Fehler: "java.lang.RuntimeException: type=25"
General error: "java.lang.RuntimeException: type=25" [50000-196]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:168)
	at org.h2.message.DbException.convert(DbException.java:295)
	at org.h2.message.DbException.toSQLException(DbException.java:268)
	at org.h2.message.TraceObject.logAndConvert(TraceObject.java:352)
	at org.h2.jdbc.JdbcResultSetMetaData.getColumnClassName(JdbcResultSetMetaData.java:376)
	at com.intellij.database.remote.jdbc.impl.RemoteResultSetImpl.getObject(RemoteResultSetImpl.java:1269)
	at com.intellij.database.remote.jdbc.impl.RemoteResultSetImpl.getCurrentRow(RemoteResultSetImpl.java:1249)
	at com.intellij.database.remote.jdbc.impl.RemoteResultSetImpl.getObjects(RemoteResultSetImpl.java:1229)
	at sun.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:346)
	at sun.rmi.transport.Transport$1.run(Transport.java:200)
	at sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:568)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:826)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:683)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:682)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: type=25
	at org.h2.message.DbException.throwInternalError(DbException.java:242)
	at org.h2.value.DataType.getTypeClassName(DataType.java:789)
	at org.h2.jdbc.JdbcResultSetMetaData.getColumnClassName(JdbcResultSetMetaData.java:374)
	... 19 more
`
I have never seen something like that. Any idea?

**Comment by Tapac** [comment]
Try to update to latest (1.4.197) version of h2, there were a lot of fixes related to enums (http://www.h2database.com/html/changelog.html).

**Comment by StefanHub** [comment]
That is the version I am using.

Am Mi., 14. Nov. 2018, 16:16 hat Andrey.Tarashevskiy <
notifications@github.com> geschrieben:

**Comment by Tapac** [comment]
`[50000-196]` in error message means that you are using h2 1.4.196.
But stacktrace contains `com.intellij.database` and nothing about Exposed, maybe you have to update your jdbc driver in IDEA `Database` console?

**Comment by StefanHub** [comment]
Sorry, I was downgrading H2 to see if things change. But it did not.

Yes, it seems to happen in the database/driver. I will try to update the jdbc driver. Thanks.

**Comment by StefanHub** [comment]
Yes, it has been a driver problem. With the latest driver version 1.4.197 it works fine.  Unfortunatly, IDEA does not offer this driver version. Their latest version is 1.4.196.

However, there is still an open question for me. What is the 'correct' toDb() mapping function? The documentation says that it is:
`{it.name}`
and I thought that this is may be an mistake and that it should rather be:
`{it.ordinal}`
because the fromDb()
`{Foo.values()[it as Int]}`
expects an Int from the database.

**Comment by Tapac** [comment]
No, H2 driver works this way. All supported databases are covered in `DDLTests.testCustomEnumeration01()` test.
