### ISSUE TITLE
"ERROR: column "punished_at" specified more than once" even when... it isn't?

### ISSUE THREAD

**Issue by MrPowerGamerBR** [JetBrains/Exposed#429]
This issue is driving me crazy, I have no idea what causes it

```
[21:57:31] [main/INFO] [Exposed]: Transaction attempt #0 failed: org.postgresql.util.PSQLException: ERROR: column "punished_at" specified more than once
  Location: File: tablecmds.c, Routine: MergeAttributes, Line: 1712
  Server SQLState: 42701. Statement(s): CREATE TABLE IF NOT EXISTS bans (id BIGSERIAL PRIMARY KEY, player uuid NOT NULL, punished_by uuid NULL, punisher_name TEXT NOT NULL, punished_at BIGINT NOT NULL, reason TEXT NULL, temporary BOOLEAN NOT NULL, expires_at BIGINT NULL, punished_at BIGINT NOT NULL, temporary BOOLEAN NOT NULL, expires_at BIGINT NULL)
org.jetbrains.exposed.exceptions.ExposedSQLException: org.postgresql.util.PSQLException: ERROR: column "punished_at" specified more than once
  Location: File: tablecmds.c, Routine: MergeAttributes, Line: 1712
  Server SQLState: 42701
        at org.jetbrains.exposed.sql.statements.Statement.executeIn$exposed(Statement.kt:61) ~[?:?]
        at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:128) ~[?:?]
        at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:122) ~[?:?]
        at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:101) ~[?:?]
        at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:92) ~[?:?]
        at org.jetbrains.exposed.sql.SchemaUtils.createMissingTablesAndColumns(SchemaUtils.kt:191) ~[?:?]
        at net.perfectdreams.dreamnetworkbans.DreamNetworkBans$onEnable$1.invoke(DreamNetworkBans.kt:38) ~[?:?]
        at net.perfectdreams.dreamnetworkbans.DreamNetworkBans$onEnable$1.invoke(DreamNetworkBans.kt:16) ~[?:?]
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction(ThreadLocalTransactionManager.kt:104) ~[?:?]
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:75) ~[?:?]
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:58) ~[?:?]
        at net.perfectdreams.dreamnetworkbans.DreamNetworkBans.onEnable(DreamNetworkBans.kt:37) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:261) ~[BungeeCord.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:067d55c:68]
        at net.md_5.bungee.BungeeCord.start(BungeeCord.java:291) ~[BungeeCord.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:067d55c:68]
        at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:56) ~[BungeeCord.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:067d55c:68]
        at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) ~[BungeeCord.jar:git:Travertine-Bootstrap:1.13-SNAPSHOT:067d55c:68]
Caused by: org.postgresql.util.PSQLException: ERROR: column "punished_at" specified more than once
  Location: File: tablecmds.c, Routine: MergeAttributes, Line: 1712
  Server SQLState: 42701
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440) ~[?:?]
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2183) ~[?:?]
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308) ~[?:?]
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441) ~[?:?]
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365) ~[?:?]
        at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:143) ~[?:?]
        at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:120) ~[?:?]
        at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61) ~[?:?]
        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java) ~[?:?]
        at org.jetbrains.exposed.sql.Transaction$exec$2.executeInternal(Transaction.kt:105) ~[?:?]
        at org.jetbrains.exposed.sql.statements.Statement.executeIn$exposed(Statement.kt:59) ~[?:?]
        ... 15 more
```

I already checked and double checked, but there isn't ANY duplicates on my table. (you can see all tables here: https://github.com/PerfectDreams/DreamNetworkBans/tree/master/src/main/kotlin/net/perfectdreams/dreamnetworkbans/tables)

I'm not sure if this is an mistake on my side, of it is an issue in Exposed... if it is an issue in Exposed, it would be good if it had a more "user friendly" error because this is getting very difficult to track down. 😭

**Comment by MrPowerGamerBR** [comment]
Thank you, I guess I made a mistake while copying and pasting the table entries and I forgot to fix that (and I even looked at the tables a lot of times, it seems that small typo slipped) 😢 

I will close the issue, if the issue doesn't go away after changing that (it will probably fix) then I will reopen the issue, thank you! 😊
