### ISSUE TITLE
get value from column out of `transaction` block

### ISSUE THREAD

**Issue by Aragami1408** [JetBrains/Exposed#436]
Hi. I have a problem:

```kotlin
object Configuration : Table() {
    val token = varchar("token", 255).primaryKey()
    val serverId = varchar("server_id", 20).primaryKey()
    val prefix = varchar("prefix", 2)

    val joinChannel = varchar("join_channel", 20).nullable()
    val suggestionChannel = varchar("suggest_channel", 20).nullable()

    val disableJoinLog = bool("disable_join_log")
    val disableSuggest = bool("disable_suggest")
}
```

the code snippet above is my Configuration table. I put that values. But I want to get it in another class like:

```kotlin
fun main(args: Array<String>) { 
    val prefix = Configuration.slice(Configuration.prefix).selectAll().map {it[Configuration.prefix]}
}
```

but when I run the code, the error log below:

```
Exception in thread "main" java.lang.IllegalStateException: No transaction in context.
	at org.jetbrains.exposed.sql.transactions.TransactionManager$Companion.current(TransactionApi.kt:76)
	at org.jetbrains.exposed.sql.Query.getTransaction(Query.kt:85)
	at org.jetbrains.exposed.sql.Query.flushEntities(Query.kt:275)
	at org.jetbrains.exposed.sql.Query.iterator(Query.kt:279)
	at com.harrycoder.discordbots.thighbot.BotKt.main(Bot.kt:30)
```

How can I solve that?

**Comment by Tapac** [comment]
https://github.com/JetBrains/Exposed/wiki/Getting-Started#starting-a-transaction
