### ISSUE TITLE
Cannot serialize entity - problem with id.

### ISSUE THREAD

**Issue by LookBad** [JetBrains/Exposed#438]
I try get data from database (PG) and serialize :(
`2018-11-24 16:04:55.338 [pool-1-thread-1] DEBUG Exposed - SELECT book.id, book.title, book.author, book.description FROM book
2018-11-24 16:04:55.532 [pool-1-thread-1] ERROR Application - Unhandled: GET - /books
java.lang.StackOverflowError: null
	at java.base/java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:605)
	at java.base/java.lang.StringBuffer.append(StringBuffer.java:355)
	at java.base/java.io.StringWriter.write(StringWriter.java:122)
	at com.google.gson.stream.JsonWriter.string(JsonWriter.java:591)
	at com.google.gson.stream.JsonWriter.writeDeferredName(JsonWriter.java:402)
	at com.google.gson.stream.JsonWriter.beginObject(JsonWriter.java:307)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:240)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:127)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:245)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:127)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:245)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:127)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:245)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:127)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:245)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:127)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:245)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:69)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:127)
`

**Comment by bradcypert** [comment]
@LookBad Did you ever find any help with this? If not, please share some code regarding your table structure, your transaction, and the call site please :) i'd be happy to try to help.
