### ISSUE TITLE
SQL syntax error on create table

### ISSUE THREAD

**Issue by DevSrSouza** [JetBrains/Exposed#441]
I get this exception when I try to create the table.
I'm using MariaDB 10.1.34
Exposed version 0.11.2

```
org.jetbrains.exposed.exceptions.ExposedSQLException: 
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: 
You have an error in your SQL syntax; check themanual that corresponds to
your MariaDB server version for the right syntax to use near 
'VARCHAR(25) NOT NULL, duration INT NOT NULL, vip VARCHAR(30) NOT NULL, usageBy B' at line 1
	at org.jetbrains.exposed.sql.statements.Statement.executeIn$exposed(Statement.kt:61) ~[?:?]
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:128) ~[?:?]
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:122) ~[?:?]
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:101) ~[?:?]
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:92) ~[?:?]
	at org.jetbrains.exposed.sql.SchemaUtils.create(SchemaUtils.kt:160) ~[?:?]
	at br.com.devsrsouza.souzavip.VipManager$1.invoke(VipManager.kt:34) ~[?:?]
	at br.com.devsrsouza.souzavip.VipManager$1.invoke(VipManager.kt:20) ~[?:?]
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction(ThreadLocalTransactionManager.kt:104) ~[?:?]
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:75) ~[?:?]
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:58) ~[?:?]
	at br.com.devsrsouza.souzavip.VipManager.<init>(VipManager.kt:34) ~[?:?]

```

My code in line 34

```kotlin
transaction(database) { SchemaUtils.create(KeyTable, PlayerVipTable) }
```

The table
```kotlin
object KeyTable : IntIdTable(DatabaseConfig.keysTable) {
    val key = varchar("key", KEY_LENGTH).uniqueIndex()
    val duration = integer("duration")
    val vip = varchar("vip", 30)
    val usageBy = uuid("usageBy").nullable()
    val forWho = uuid("forWho").nullable()
    val generatedBy = uuid("generated").nullable()
}
```

**Comment by DevSrSouza** [comment]
I found the problem changing the name of the column key. I search about that and the problem is that the `key` is a reserved word of MySQL, but to fix that is just put a backticks(`) arround key.
How I can add that or you guys have plan to add backticks no the future for fix this problem?

(sorry for my bad english :S)

**Comment by Tapac** [comment]
Which jdbc driver do you use? Mysql driver 5.1.46 contains `key` as a keyword and should be quoted by default. Maybe Maria DB driver doesn't have such word in `DatabaseMetada,SQLKeywords` list?

**Comment by DevSrSouza** [comment]
I dont know exacly the version usage on the project that I use the API but i think is pretty old.
And the server is MariaDB but I'm actually using MySQL connector of the API.
I will test with MariaDB connector if works.

**Comment by DevSrSouza** [comment]
Now is give this exception, i think is because the Exposed not support MariaDB directly
```kotlin
Caused by: java.lang.IllegalStateException: No dialect registered for mariadb. URL=jdbc:mariadb://localhost:3306/rankup
	at org.jetbrains.exposed.sql.Database$dialect$2.invoke(Database.kt:31) ~[?:?]
	at org.jetbrains.exposed.sql.Database$dialect$2.invoke(Database.kt:16) ~[?:?]
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74) ~[?:?]
	at org.jetbrains.exposed.sql.Database.getDialect(Database.kt) ~[?:?]
	at org.jetbrains.exposed.sql.vendors.DefaultKt.getCurrentDialect(Default.kt:363) ~[?:?]
	at org.jetbrains.exposed.sql.vendors.DefaultKt.getCurrentDialectIfAvailable(Default.kt:367) ~[?:?]
	at org.jetbrains.exposed.sql.Column.getOnDelete$exposed(Column.kt:17) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
	at kotlin.reflect.jvm.internal.calls.CallerImpl$Method.callMethod(CallerImpl.kt:71) ~[?:?]
	at kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Instance.call(CallerImpl.kt:87) ~[?:?]
	at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:106) ~[?:?]
	at kotlin.reflect.jvm.internal.KProperty1Impl.get(KProperty1Impl.kt:35) ~[?:?]
	at org.jetbrains.exposed.sql.Table.clone(Table.kt:212) ~[?:?]
	at org.jetbrains.exposed.sql.Table.cloneWithAutoInc(Table.kt:360) ~[?:?]
	at org.jetbrains.exposed.sql.Table.autoIncrement(Table.kt:364) ~[?:?]
	at org.jetbrains.exposed.sql.Table.autoIncrement$default(Table.kt:364) ~[?:?]
	at org.jetbrains.exposed.dao.IntIdTable.<init>(IntEntity.kt:6) ~[?:?]
	at org.jetbrains.exposed.dao.IntIdTable.<init>(IntEntity.kt:5) ~[?:?]
	at br.com.devsrsouza.souzavip.KeyTable.<init>(SQL.kt:42) ~[?:?]
	at br.com.devsrsouza.souzavip.KeyTable.<clinit>(SQL.kt:42) ~[?:?]
	... 18 more
```

**Comment by Tapac** [comment]
@DevSrSouza, could you please try to register dialect for MariaDB with MysqlDialect and leave feedback how it will work? 
```kotlin
Database.registerDialect("mariadb") { MysqlDialect() }
Database.connect("jdbc:mariadb://localhost:3306/rankup",....)
