### ISSUE TITLE
Leaking conection with hikari and postgres

### ISSUE THREAD

**Issue by spolnik** [JetBrains/Exposed#487]
Using: exposed 0.12.1, PG 42.2.5, hikari 3.2.0

The way I run transaction:

```java
private fun <T> runWithinTransaction(db: Database, block: () -> T): T {
        return transaction(db) {
            addLogger(Slf4jSqlDebugLogger)
            warnLongQueriesDuration = 2000
            connection.prepareStatement("SET LOCAL statement_timeout TO 1").use {
                it.execute()
            }
            block()
        }
    }
```
I've set it to 1ms by design in test, so I can achieve in shorter time same what happen on prod with longer timeouts.

```java
"DefaultDispatcher-worker-4 @request#72" #34 daemon prio=5 os_prio=31 tid=0x00007fdfd9acb800 nid=0x5e07 runnable [0x0000700011556000]
   java.lang.Thread.State: RUNNABLE
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
        at java.net.SocketInputStream.read(SocketInputStream.java:171)
        at java.net.SocketInputStream.read(SocketInputStream.java:141)
        at org.postgresql.core.VisibleBufferedInputStream.readMore(VisibleBufferedInputStream.java:140)
        at org.postgresql.core.VisibleBufferedInputStream.ensureBytes(VisibleBufferedInputStream.java:109)
        at org.postgresql.core.VisibleBufferedInputStream.read(VisibleBufferedInputStream.java:67)
        at org.postgresql.core.PGStream.receiveChar(PGStream.java:306)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1952)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308)
        - locked <0x000000076f80c298> (a org.postgresql.core.v3.QueryExecutorImpl)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
        at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:307)
        at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:293)
        at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:270)
        at org.postgresql.jdbc.PgStatement.executeQuery(PgStatement.java:224)
        at org.postgresql.jdbc.PgDatabaseMetaData.getSQLKeywords(PgDatabaseMetaData.java:320)
        at org.jetbrains.exposed.sql.Database$keywords$2.invoke(Database.kt:42)
        at org.jetbrains.exposed.sql.Database$keywords$2.invoke(Database.kt:16)
        at kotlin.UnsafeLazyImpl.getValue(Lazy.kt:81)
        at org.jetbrains.exposed.sql.Database.getKeywords(Database.kt)
        at org.jetbrains.exposed.sql.Database.needQuotes(Database.kt:57)
        at org.jetbrains.exposed.sql.Transaction.quoteTokenIfNecessary(Transaction.kt:164)
        at org.jetbrains.exposed.sql.Transaction.quoteIfNecessary$exposed(Transaction.kt:158)
        at org.jetbrains.exposed.sql.Transaction.fullIdentity(Transaction.kt:170)
        at org.jetbrains.exposed.sql.Column.toSQL(Column.kt:32)
        at org.jetbrains.exposed.sql.Query$prepareSQL$$inlined$buildString$lambda$1.invoke(Query.kt:169)
        at org.jetbrains.exposed.sql.Query$prepareSQL$$inlined$buildString$lambda$1.invoke(Query.kt:84)
        at kotlin.text.StringsKt__StringBuilderKt.appendElement(StringBuilder.kt:58)
        at kotlin.collections.CollectionsKt___CollectionsKt.joinTo(_Collections.kt:2274)
        at kotlin.collections.CollectionsKt___CollectionsKt.joinToString(_Collections.kt:2291)
        at kotlin.collections.CollectionsKt___CollectionsKt.joinToString$default(_Collections.kt:2290)
        at org.jetbrains.exposed.sql.Query.prepareSQL(Query.kt:169)
        at org.jetbrains.exposed.sql.Query.arguments(Query.kt:153)
        at org.jetbrains.exposed.sql.Query.arguments(Query.kt:84)
        at org.jetbrains.exposed.sql.statements.Statement.executeIn$exposed(Statement.kt:32)
        at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:131)
        at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:125)
        at org.jetbrains.exposed.sql.Query.iterator(Query.kt:291)

```

Any suggestion what may cause it?

Additionally, is there any other way to set query timeout ?

**Comment by Tapac** [comment]
Is this ok if do the same without Exposed on plain connection / prepareStatement?

**Comment by spolnik** [comment]
Yes, I'm doing similar stuff with streaming offline via cursor (autocommit = false, setFetchSize=512) and pure jdbc and there is no issues. Interestingly it doesn't happen always, so sometimes when I run it it passes without hanging, and sometimes it hangs.

Would repeat my question in other way - is there any way to deal with long running queries - the warn as I see is generated only once query is done as I understand (I do not see it for hanging cases).

So ideally, similarly as hikari Exposed should report leaking connections (although Hikari already does it) and allow to recover somehow from that, eg via setQueryTimeout on PreparedStatement - any ideas?

**Comment by Tapac** [comment]
As I can see from a stacktrace the Exposed calls `connection.metadata.keywords` and possibly there is an issue with timeout? Could you try to make the same call in your test with plain connection?

Our aim is to make Exposed connection/pool agnostic and just to ensure that it doesn't override connection properties. We already resolve some leakage issues and you are the first for a long time who report it.

`warnLongQueriesDuration` is mostly used to detect and debug long executed queries.

**Comment by spolnik** [comment]
Unfortunately it's not that easy to do, as I use exposed on top hikari and lots of code depends on it (e.g. many threads use connections, so I would need to manage it somehow manually to make it working).

For me enough would be to have possibility to rescue from such situation, so instead of me doing:

```java
private fun <T> runWithinTransaction(db: Database, block: () -> T): T {
        return transaction(
                transactionIsolation = TransactionManager.manager.defaultIsolationLevel,
                repetitionAttempts = 0,
                db = db
        ) {
            addLogger(Slf4jSqlDebugLogger)
            warnLongQueriesDuration = 2000
            connection.prepareStatement("SET LOCAL statement_timeout TO 60000").use {
                it.execute()
            }
            block()
        }
    }
```

I would like to do:

```java
private fun <T> runWithinTransaction(db: Database, block: () -> T): T {
        return transaction(
                transactionIsolation = TransactionManager.manager.defaultIsolationLevel,
                repetitionAttempts = 0,
                db = db
        ) {
            addLogger(Slf4jSqlDebugLogger)
            warnLongQueriesDuration = 2000
            queryTimeout = 60000
            block()
        }
    }
```

That should pass to `PreparedStatement` the timeout and then it would guarantee that it will stop once timeout is done, and rescue from this situation in a proper way. Not sure if doing the way I do with separate statement call is actually impacting anything - what do you think?

**Comment by Tapac** [comment]
Could you provide a sample of how do you setup hikaryCP?

**Comment by spolnik** [comment]
```
private fun hikariDataSource(config: DatabaseConfig, name: String) = HikariDataSource().apply {
    poolName = name
    driverClassName = config.driverClass
    jdbcUrl = config.url
    username = config.user
    password = config.password
    minimumIdle = 1
    maximumPoolSize = config.maxPoolSize
    connectionTimeout = config.connectionTimeout
    leakDetectionThreshold = (config.leakDetectionThresholdSecs * 1000).toLong()
    transactionIsolation = "TRANSACTION_READ_COMMITTED"
    connectionTestQuery = "SELECT 1"
}
```

**Comment by Tapac** [comment]
Could it be the problem with Postgresql jdbc driver's `preparedStatementCache`?
Please try to set it to 0 and try again. Also, please, test it with lower `socketTimeout`.
More details is [here](https://jdbc.postgresql.org/documentation/head/connect.html#connection-parameters)

**Comment by spolnik** [comment]
I doubt it's with cache as I have pool of connections, and under tests don't overuse same connections much - and this limit of 256 is per connection as I understand. SocketTimeout is not here a problem - can you expose setting `queryTimeout`

**Comment by spolnik** [comment]
or would this work?
```kotlin
addLogger(Slf4jSqlDebugLogger)
                warnLongQueriesDuration = 2000
                currentStatement!!.queryTimeout = 60
                block()
```

**Comment by le-co** [comment]
Hi @spolnik 

I tried this 👎 
```
addLogger(Slf4jSqlDebugLogger)
warnLongQueriesDuration = 2000
currentStatement!!.queryTimeout = 60
block()
```

but, this is not working.

I created the new project for testing query timeout

```
val DRIVER_CLASS_NAME = System.getenv("DRIVER_CLASS_NAME") ?: "org.postgresql.Driver"
val DB_URL = System.getenv("DB_URL") ?: "jdbc:postgresql://localhost:5432/hikari-post"
val DB_USER = System.getenv("DB_USER") ?: "sa"
val DB_PASSWORD = System.getenv("DB_PASSWORD") ?: "sa"
val DB_MAX_POOL = System.getenv("DB_MAX_POOL")?.toInt() ?: 10


fun hikariDataSource(name: String) = HikariDataSource().apply {
    poolName = name
    driverClassName = DRIVER_CLASS_NAME
    jdbcUrl = DB_URL
    username = DB_USER
    password = DB_PASSWORD
    connectionTimeout = 1500
    validationTimeout = 1000
    maxLifetime = 1000
    minimumIdle = 1
    maximumPoolSize = DB_MAX_POOL
    transactionIsolation = "TRANSACTION_READ_COMMITTED"
    connectionTestQuery = "SELECT 1"
    addDataSourceProperty("statement_timeout", 60000)
}
```

```
        val conn = TransactionManager.current().connection
        val statement = conn.createStatement()
        val query = "SELECT pg_sleep(50)"
        statement.execute(query)
```

But I think the problem may be in hikari

**Comment by le-co** [comment]
I tried this version `compile 'org.jetbrains.exposed:exposed:0.11.2'`
but the error continues

**Comment by spolnik** [comment]
@Tapac - any updates on it please?

**Comment by Tapac** [comment]
I was trying to reproduce your case, but every time I've got  `org.postgresql.util.PSQLException: ERROR: canceling statement due to statement timeout` error.

My code is 
```kotlin
    @Test fun hikaritest() {
        val source = HikariDataSource().apply {
            driverClassName = TestDB.POSTGRESQL.driver
            username = TestDB.POSTGRESQL.user
            password = TestDB.POSTGRESQL.pass
            jdbcUrl = TestDB.POSTGRESQL.connection()
            minimumIdle = 1
            maximumPoolSize = 2
            leakDetectionThreshold = 2000L
            transactionIsolation = "TRANSACTION_READ_COMMITTED"
            connectionTestQuery = "SELECT 1"
        }
        withDb(TestDB.POSTGRESQL) {
            val pgDB = Database.Companion.connect(source)
            runWithinTransaction(pgDB) {
                SchemaUtils.create(LongIdTables.Cities)
            }
        }
    }

    private fun <T> runWithinTransaction(db: Database, block: () -> T): T {
        return transaction(db) {
            debug = true
            addLogger(Slf4jSqlDebugLogger)
            warnLongQueriesDuration = 2000
            exec("SET LOCAL statement_timeout TO 1")
            block()
        }
    }
```
Tested with HikariCP: 3.3.1

**Comment by spolnik** [comment]
hey, did you try to run it from many threads? We have many concurrent connections possible - thanks

**Comment by Tapac** [comment]
No, I test it in a single-thread test. Could you provide sample app where it can be reproduced?
Also, do you use coroutines or share a transaction between threads?

**Comment by spolnik** [comment]
Unfortunately it's part of our internal code, cannot share it. I'm using Ktor, which is accepting connections then I run queries within:
```kotlin
@Trace(async = true)
    private suspend fun <T> dbQuery(db: Database, token: Token, block: () -> T): T {
        token.link()
        return withContext(Dispatchers.IO) {
            runWithinTransaction(db, token, block)
        }
    }

    @Trace(async = true)
    private fun <T> runWithinTransaction(db: Database, token: Token, block: () -> T): T {
        token.link()
        try {
            return transaction(
                    transactionIsolation = TransactionManager.manager.defaultIsolationLevel,
                    repetitionAttempts = 0,
                    db = db
            ) {
                addLogger(Slf4jSqlDebugLogger)
                warnLongQueriesDuration = 2000
                connection.prepareStatement("SET LOCAL statement_timeout TO 60000").use {
                    it.execute()
                }
                block()
            }
        } catch (e: SQLException) {
            val exception: SQLException = when {
                e is ExposedSQLException && e.cause != null && e.cause is SQLException -> e.cause as SQLException
                else -> e
            }

            when {
                exception.message != null && exception.message!!.contains("canceling statement due to statement timeout") ->
                    throw QueryTimeout()
                else -> throw e
            }
        }
    }
```

**Comment by Tapac** [comment]
Could you try to use `transaction` from `org.jetbrains.exposed.sql.transactions.experimental` package?

**Comment by spolnik** [comment]
Would you mind explain please the difference, and how secure it is to use the experimental feature?

**Comment by Tapac** [comment]
It's experimental because we plan to support Coroutine aware transaction manager, but now you can use this `experimental` transaction to execute transaction at the same thread as a coroutine goes.  

An I just ask you to test will it help with connection leak. If so then the problem not in the Hikary or Exposed, but in how you use share transaction between different threads/

**Comment by spolnik** [comment]
Ok switched to coroutines (experimental transaction), and so far I do not observe same behaviour - so I'm happy to close this part of issue.

Additionally, I switched to use `exec("SET LOCAL statement_timeout TO 10000")` - but ideally we should just have queryTimeout which is passed down to PreparedStatement and set directly on it - any chance to expose it within this experimental transaction?

**Comment by Tapac** [comment]
As it's possible that Exposed become multi-platform we try don't rely on jdbc implementation (PreparedStatement) too much.

**Comment by spolnik** [comment]
queryTimeout concept is I would say more general than jdbc, and how you implement depends on the driver, in case of jdbc that would be PreparedStatement, but in terms of other can be anything - so what's wrong with supporting it on transaction level as generic query timeout ?

**Comment by Tapac** [comment]
From my point of view `queryTimeout` property should be defined on connection/pool level not a statement level

**Comment by spolnik** [comment]
then it would require to manage connection pools per type of query/use case you have, if I have different query cases which I handle with same connection pool, and just one case requires restricting queryTimeout per transactions that doesn't work
