### ISSUE TITLE
Auto Increment with H2 Database doesn't work.

### ISSUE THREAD

**Issue by Toshimichi0915** [JetBrains/Exposed#494]
An exception occurs when I try to use "autoIncrement."
The same happens when I use "IntTable" instead of "Table"
```
package net.toshimichi.domination

import org.bukkit.plugin.java.JavaPlugin
import org.jetbrains.exposed.dao.IntIdTable
import org.jetbrains.exposed.sql.*
import org.jetbrains.exposed.sql.transactions.transaction
import java.io.File
import java.net.ConnectException

class DominationPlugin : JavaPlugin() {
    object TestTable : IntIdTable("test_table") {
//        val id = integer("id").primaryKey().autoIncrement()
        val value = varchar("value", 15)
    }

    override fun onEnable() {
        logger.info("データベースを用意中")
        Database.connect("jdbc:h2:file:${File(dataFolder, "domination").absolutePath}", "org.h2.Driver")
        logger.info("テスト接続中")
        transaction {
            SchemaUtils.create(TestTable)
            TestTable.insert {
                it[value] = "Hello"
            }
            TestTable.insert {
                it[value] = "World!"
            }
            if (!TestTable.select { TestTable.id eq 0 }.all { it[TestTable.value] == "Hello" } ||
                !TestTable.select { TestTable.id eq 1 }.all { it[TestTable.value] == "World!" }) {
                getLogger().severe("テスト接続に失敗しました")
                throw DatabaseTestException()
            }
        }
    }
}

class DatabaseTestException : ConnectException()
```

```
[00:35:50 ERROR]: Error occurred while enabling Domination v3.0 (Is it up to date?)
java.util.ServiceConfigurationError: kotlin.reflect.jvm.internal.impl.builtins.BuiltInsLoader: Error reading configuration file
        at java.util.ServiceLoader.fail(ServiceLoader.java:232) ~[?:1.8.0_171]
        at java.util.ServiceLoader.parse(ServiceLoader.java:309) ~[?:1.8.0_171]
        at java.util.ServiceLoader.access$200(ServiceLoader.java:185) ~[?:1.8.0_171]
        at java.util.ServiceLoader$LazyIterator.hasNextService(ServiceLoader.java:357) ~[?:1.8.0_171]
        at java.util.ServiceLoader$LazyIterator.hasNext(ServiceLoader.java:393) ~[?:1.8.0_171]
        at java.util.ServiceLoader$1.hasNext(ServiceLoader.java:474) ~[?:1.8.0_171]
        at kotlin.collections.CollectionsKt___CollectionsKt.firstOrNull(_Collections.kt:220) ~[?:?]
        at kotlin.reflect.jvm.internal.impl.builtins.BuiltInsLoader$Companion$Instance$2.invoke(BuiltInsLoader.kt:39) ~[?:?]
        at kotlin.reflect.jvm.internal.impl.builtins.BuiltInsLoader$Companion$Instance$2.invoke(BuiltInsLoader.kt:36) ~[?:?]
        at kotlin.SafePublicationLazyImpl.getValue(LazyJVM.kt:107) ~[?:?]
        at kotlin.reflect.jvm.internal.impl.builtins.BuiltInsLoader$Companion.getInstance(BuiltInsLoader.kt) ~[?:?]
        at kotlin.reflect.jvm.internal.impl.builtins.KotlinBuiltIns.createBuiltInsModule(KotlinBuiltIns.java:127) ~[?:?]
        at kotlin.reflect.jvm.internal.impl.builtins.jvm.JvmBuiltIns.<init>(JvmBuiltIns.kt:43) ~[?:?]
        at kotlin.reflect.jvm.internal.impl.builtins.jvm.JvmBuiltIns.<init>(JvmBuiltIns.kt:18) ~[?:?]
        at kotlin.reflect.jvm.internal.components.RuntimeModuleData$Companion.create(RuntimeModuleData.kt:58) ~[?:?]
        at kotlin.reflect.jvm.internal.ModuleByClassLoaderKt.getOrCreateModule(moduleByClassLoader.kt:58) ~[?:?]
        at kotlin.reflect.jvm.internal.KDeclarationContainerImpl$Data$moduleData$2.invoke(KDeclarationContainerImpl.kt:37) ~[?:?]
        at kotlin.reflect.jvm.internal.KDeclarationContainerImpl$Data$moduleData$2.invoke(KDeclarationContainerImpl.kt:34) ~[?:?]
        at kotlin.reflect.jvm.internal.ReflectProperties$LazySoftVal.invoke(ReflectProperties.java:92) ~[?:?]
        at kotlin.reflect.jvm.internal.ReflectProperties$Val.getValue(ReflectProperties.java:31) ~[?:?]
        at kotlin.reflect.jvm.internal.KDeclarationContainerImpl$Data.getModuleData(KDeclarationContainerImpl.kt) ~[?:?]
        at kotlin.reflect.jvm.internal.KClassImpl$Data$descriptor$2.invoke(KClassImpl.kt:47) ~[?:?]
        at kotlin.reflect.jvm.internal.KClassImpl$Data$descriptor$2.invoke(KClassImpl.kt:44) ~[?:?]
        at kotlin.reflect.jvm.internal.ReflectProperties$LazySoftVal.invoke(ReflectProperties.java:92) ~[?:?]
        at kotlin.reflect.jvm.internal.ReflectProperties$Val.getValue(ReflectProperties.java:31) ~[?:?]
        at kotlin.reflect.jvm.internal.KClassImpl$Data.getDescriptor(KClassImpl.kt) ~[?:?]
        at kotlin.reflect.jvm.internal.KClassImpl.getDescriptor(KClassImpl.kt:179) ~[?:?]
        at kotlin.reflect.jvm.internal.KClassImpl.getConstructorDescriptors(KClassImpl.kt:196) ~[?:?]
        at kotlin.reflect.jvm.internal.KClassImpl$Data$constructors$2.invoke(KClassImpl.kt:91) ~[?:?]
        at kotlin.reflect.jvm.internal.KClassImpl$Data$constructors$2.invoke(KClassImpl.kt:44) ~[?:?]
        at kotlin.reflect.jvm.internal.ReflectProperties$LazySoftVal.invoke(ReflectProperties.java:92) ~[?:?]
        at kotlin.reflect.jvm.internal.ReflectProperties$Val.getValue(ReflectProperties.java:31) ~[?:?]
        at kotlin.reflect.jvm.internal.KClassImpl$Data.getConstructors(KClassImpl.kt) ~[?:?]
        at kotlin.reflect.jvm.internal.KClassImpl.getConstructors(KClassImpl.kt:235) ~[?:?]
        at kotlin.reflect.full.KClasses.getPrimaryConstructor(KClasses.kt:40) ~[?:?]
        at org.jetbrains.exposed.sql.Table.clone(Table.kt:209) ~[?:?]
        at org.jetbrains.exposed.sql.Table.cloneWithAutoInc(Table.kt:361) ~[?:?]
        at org.jetbrains.exposed.sql.Table.autoIncrement(Table.kt:365) ~[?:?]
        at org.jetbrains.exposed.sql.Table.autoIncrement$default(Table.kt:365) ~[?:?]
        at net.toshimichi.domination.DominationPlugin$TestTable.<clinit>(DominationPlugin.kt:11) ~[?:?]
        at net.toshimichi.domination.DominationPlugin$onEnable$1.invoke(DominationPlugin.kt:20) ~[?:?]
        at net.toshimichi.domination.DominationPlugin$onEnable$1.invoke(DominationPlugin.kt:9) ~[?:?]
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction(ThreadLocalTransactionManager.kt:104) ~[?:?]
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:75) ~[?:?]
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:58) ~[?:?]
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction$default(ThreadLocalTransactionManager.kt:58) ~[?:?]
        at net.toshimichi.domination.DominationPlugin.onEnable(DominationPlugin.kt:19) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:381) [spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:330) [spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.reload(CraftServer.java:752) [spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]
        at org.bukkit.Bukkit.reload(Bukkit.java:525) [spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]
        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:27) [spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648) [spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchServerCommand(CraftServer.java:634) [spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]
        at net.minecraft.server.v1_12_R1.DedicatedServer.aP(DedicatedServer.java:444) [spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:407) [spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [spigot-1.12.2.jar:git-Spigot-eb3d921-2b93d83]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: java.io.FileNotFoundException: JAR entry META-INF/services/kotlin.reflect.jvm.internal.impl.builtins.BuiltInsLoader not found in /home/toshimichi/Desktop/minecraft/small/plugins/domination-all.jar
        at sun.net.www.protocol.jar.JarURLConnection.connect(JarURLConnection.java:144) ~[?:1.8.0_171]
        at sun.net.www.protocol.jar.JarURLConnection.getInputStream(JarURLConnection.java:152) ~[?:1.8.0_171]
        at java.net.URL.openStream(URL.java:1045) ~[?:1.8.0_171]
        at java.util.ServiceLoader.parse(ServiceLoader.java:304) ~[?:1.8.0_171]
        ... 61 more

```

**Comment by Toshimichi0915** [comment]
Wait. That's my problem.
Shadow jar caused that.
