### ISSUE TITLE
SSLException closing inbound before receiving peer's close_notify

### ISSUE THREAD

**Issue by DeepanRajV** [JetBrains/Exposed#533]
just trying to list out tables and it hits me with this SSLException error
```
transaction {
    val tables = db.dialect.allTablesNames()
}
```
```
Mon Mar 25 15:40:05 IST 2019 WARN: Caught while disconnecting...

EXCEPTION STACK TRACE:

** BEGIN NESTED EXCEPTION ** 

javax.net.ssl.SSLException
MESSAGE: closing inbound before receiving peer's close_notify

STACKTRACE:

javax.net.ssl.SSLException: closing inbound before receiving peer's close_notify
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:129)
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:117)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:308)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:264)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:255)
	at java.base/sun.security.ssl.SSLSocketImpl.shutdownInput(SSLSocketImpl.java:645)
	at java.base/sun.security.ssl.SSLSocketImpl.shutdownInput(SSLSocketImpl.java:624)
	at com.mysql.cj.protocol.a.NativeProtocol.quit(NativeProtocol.java:1319)
	at com.mysql.cj.NativeSession.quit(NativeSession.java:182)
	at com.mysql.cj.jdbc.ConnectionImpl.realClose(ConnectionImpl.java:1750)
	at com.mysql.cj.jdbc.ConnectionImpl.close(ConnectionImpl.java:720)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManager$ThreadLocalTransaction.close(ThreadLocalTransactionManager.kt:49)
	at org.jetbrains.exposed.sql.Transaction.close(Transaction.kt)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction(ThreadLocalTransactionManager.kt:146)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:75)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:58)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction$default(ThreadLocalTransactionManager.kt:58)
	at test.HelloKt.main(Hello.kt:21)
	at test.HelloKt.main(Hello.kt)

** END NESTED EXCEPTION **
```
is there a work around? Am I missing something? or is there a fix?
specs: win 10, Intellij IDEA Comm., Maven, JDK 11, Kotlin 1.3.21, exposed 0.13.3, mysql connector 8.0.15, slf4j-simple 1.7.26

**Comment by Tapac** [comment]
Please try to change (one at the time): 
- Exposed 0.13.3 -> 0.13.5
- JDK 11 -> JDK 8
- Mysql Connector  8.0.15 -> 5.1.46

**Comment by DeepanRajV** [comment]
yep Thanks @Tapac changing JDK to 8 worked. I wonder why

**Comment by Auronake** [comment]
Hello

I can open a new issue if need it

I meet a similar problem with my Javalin project in Kotlin : 
javax.net.ssl.SSLException
MESSAGE: closing inbound before receiving peer's close_notify

I use : 
implementation 'org.jetbrains.kotlin:kotlin-stdlib-jdk8'
compile 'io.javalin:javalin:2.8.0'
compile 'org.jetbrains.exposed:exposed:0.13.7'
compile 'mysql:mysql-connector-java:5.1.46'

It seems pretty close that the Tapac's advise... Any idea ? Need more information ?

Thank you!

**Comment by Tapac** [comment]
Try to look for https://stackoverflow.com/a/53136942/813981

**Comment by Auronake** [comment]
That's it! Thks!
