### ISSUE TITLE
Null characters in Postgres

### ISSUE THREAD

**Issue by listvin** [JetBrains/Exposed#536]
Postgres doesn't support null-characters in strings (text, char, varchar). Though Postrgres is advertised to support UTF-8 where zero code point is a valid one. H2, sqlite, mysql support nulls, by the way.
Postgres driver just throws `PSQLException: ERROR: invalid byte sequence for encoding "UTF8": 0x00` in this case. Exposed is one level above above the abstraction of driver hence it seems reasonable to protect the user from such fail for example with help of [MUTF-8](https://en.wikipedia.org/wiki/UTF-8#Modified_UTF-8), just by replacing all output null characters with `0xC0, 0x80`. The practice of implicit use of slight mods of UTF-8 like MUTF-8 and WTF-8 is pretty common.
It's a kind of enhancement, I guess. Is it even possible? May relate to #264 and also depend on splitting into per-dialect modules.

Minified example if needed:
```kotlin
object Tests: IntIdTable("test") {
    val str = text("str")
}

fun main(args: Array<String>) {
    val dbPort = 5432
    val dbName = "testdb"
    val db = Database.connect("jdbc:postgresql://localhost:$dbPort/$dbName", driver = "org.postgresql.Driver",
            user = "test", password = "test")

    transaction(db) {
        SchemaUtils.create(Tests)

        Tests.insert {
            it[str] = "\u0000"
        }
   }
}
```

**Comment by efilippov** [comment]
Hi @Tapac. Could you please check my problem. I have the same exception, but in a different case. I tried to store the hashed password in a text column when I got the following exception. 

```kotlin
Caused by: java.sql.BatchUpdateException:
Batch entry 0 INSERT INTO users (email, hash, is_email_confirmed, "name", "role", salt, surname)
              VALUES ('test@test.ru', '$2a$16$5..jGMcHh4CFxOdWuPpZm.iTpcIQAxHUT40..........

RETURNING * was aborted: ERROR: invalid byte sequence for encoding "UTF8": 0x00

Где: unnamed portal parameter $6 Call getNextException to see other errors in the batch.
at org.postgresql.jdbc.BatchResultHandler.handleError(BatchResultHandler.java:165)
at org.postgresql.core.ResultHandlerDelegate.handleError(ResultHandlerDelegate.java:52)
at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2367)
at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java: 560)
at org.postgresql.jdbc.PgStatement.internalExecuteBatch(PgStatement.java:893)
at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:916)
at org.postgresql. jdbc. PgPreparedStatement.executeBatch(PgPreparedStatement.java:1684)
at com.zaxxer.hikari.pool.ProxyStatement.executeBatch(ProxyStatement.java:127)
at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeBatch(HikariProxyPreparedStatement.java)
at org.jetbrains.exposed.sql.statements.jdbc.JdbcPreparedStatementImpl.executeBatch(JdbcPreparedStatementImpl.kt:48)
at org.jetbrains.exposed.sql.statements.InsertStatement .execInsertFunction(InsertStatement.kt:123)
at org.jetbrains.exposed.sql.statements.InsertStatement.executeInternal(InsertStatement.kt:131)
at org.jetbrains.exposed.sql.statements.InsertStatement.executeInternal(InsertStatement.kt:12)
at org.jetbrains.exposed.sql.statements.Statement. executeIn$exposed_core(Statement.kt:62)
... 100 common frames omitted
Caused by: org.postgresql.util.PSQLException: ERROR: invalid byte sequence for encoding "UTF8": @x00
Где: unnamed portal parameter $6
at org.postgresql.core.v3.QueryExecutor Impl.receiveErrorResponse(QueryExecutorImpl.java:2676)
at org.postgresql.core.v3.QueryExecutorImpl.processResults (QueryExecutorImpl.java:2366)
... 111 common frames omitted
``` 
Exposed thinks that the string with the hashed password has some parameters. The string was not Base64 encoded.
