### ISSUE TITLE
Sqlite requires each transation to set transactionIsolation

### ISSUE THREAD

**Issue by octplane** [JetBrains/Exposed#545]
With `exposed:0.13.2`, I have to setup a transaction isolation every time I use a transaction:

```kotlin
    fun init() {
        Database.connect(connectionString, "org.sqlite.JDBC", "", "", {
            it.transactionIsolation = java.sql.Connection.TRANSACTION_SERIALIZABLE

        })
    }

    suspend fun <T> dbQuery(
        block: () -> T): T =
        withContext(Dispatchers.IO) {
            transaction() { block() }
        }
```

This fails at first `dbQuery` call with:
```
2019-04-13 14:15:44.952 [DefaultDispatcher-worker-2] WARN  Exposed - Transaction attempt #0 failed: SQLite supports only TRANSACTION_SERIALIZABLE and TRANSACTION_READ_UNCOMMITTED.. Statement(s): null
java.sql.SQLException: SQLite supports only TRANSACTION_SERIALIZABLE and TRANSACTION_READ_UNCOMMITTED.
	at org.sqlite.jdbc3.JDBC3Connection.setTransactionIsolation(JDBC3Connection.java:81)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManager$ThreadLocalTransaction$connectionLazy$1.invoke(ThreadLocalTransactionManager.kt:28)
	at org.jetbrains.exposed.sql.transactions.ThreadLocal
...
```

Updating the code like this:
```kotlin
    fun init() {
        Database.connect(connectionString, "org.sqlite.JDBC")
    }

    suspend fun <T> dbQuery(
        block: () -> T): T =
        withContext(Dispatchers.IO) {
            transaction(Connection.TRANSACTION_SERIALIZABLE, 1) { block() }
        }
```

Fixes the issue. Is this expected?

**Comment by Tapac** [comment]
https://github.com/JetBrains/Exposed/wiki/FAQ#q-sqlite3-fails-with-the-error-transaction-attempt-0-failed-sqlite-supports-only-transaction_serializable-and-transaction_read_uncommitted

**Comment by octplane** [comment]
Indeed. How did I miss that? Thanks!
