### ISSUE TITLE
"No BuiltInsLoader implementation was found." when relocating Kotlin packages

### ISSUE THREAD

**Issue by hazae41** [JetBrains/Exposed#573]
Exposed throws an error when using Gradle and [Shadow](https://imperceptiblethoughts.com/shadow/configuration/relocation/) to relocate Kotlin packages.

    java.lang.IllegalStateException: No BuiltInsLoader implementation was found.
    Please ensure that the META-INF/services/ is not stripped from your application and that the Java virtual machine is not running under a security manager

     at org.jetbrains.exposed.sql.Table.clone(Table.kt:206) ~[?:?]
        at org.jetbrains.exposed.sql.Table.cloneWithAutoInc(Table.kt:354) ~[?:?]
        at org.jetbrains.exposed.sql.Table.autoIncrement(Table.kt:358) ~[?:?]
        at org.jetbrains.exposed.sql.Table.autoIncrement$default(Table.kt:358) ~[?:?]
        at org.jetbrains.exposed.dao.IntIdTable.<init>(IntEntity.kt:6) ~[?:?]
        at org.jetbrains.exposed.dao.IntIdTable.<init>(IntEntity.kt:5) ~[?:?]

**Comment by Tapac** [comment]
Do you relocate kotlin-reflect too?
Looks similar to https://github.com/square/moshi/issues/637#issuecomment-422838363

**Comment by hazae41** [comment]
Yes I do

**Comment by Proximyst** [comment]
I'm also running into this problem; any updates on the issue? @hazae41

**Comment by hazae41** [comment]
No

**Comment by Proximyst** [comment]
@hazae41 I managed to solve this issue by doing as such:
```kotlin
    compile(kotlin("reflect"))

    compile("org.jetbrains.exposed:exposed:0.17.1") {
        exclude("org.jetbrains.kotlin")
    }
```
