### ISSUE TITLE
users.username is not in record set

### ISSUE THREAD

**Issue by PHELAT** [JetBrains/Exposed#592]
This is my table object:
```kotlin
object UserTable : IdTable<String>("users") {
    override val id: Column<EntityID<String>>
        get() = username.primaryKey().entityId()
    val username = varchar("username", 20).primaryKey()
    val password = varchar("password", 127)
    val email = varchar("email", 256)
}
```
This is my DAO class:
```kotlin
class User(id: EntityID<String>) : Entity<String>(id) {
    companion object : EntityClass<String, User>(UserTable)

    var username by UserTable.id
    var password by UserTable.password
    var email by UserTable.email
}
```
This is my transaction:
```kotlin
transaction {
    User.new(request.username) {
        password = request.password!!
        email = request.email!!
    }
}
```
And this is the error that I'm getting:
```
java.lang.IllegalStateException: users.username is not in record set
	at org.jetbrains.exposed.sql.ResultRow.set(Query.kt:35)
	at org.jetbrains.exposed.dao.Entity.storeWrittenValues(Entity.kt:353)
	at org.jetbrains.exposed.dao.EntityCache.flushInserts$exposed(Entity.kt:469)
	at org.jetbrains.exposed.dao.EntityCache.flush(Entity.kt:407)
	at org.jetbrains.exposed.dao.EntityCache.flush(Entity.kt:400)
	at org.jetbrains.exposed.sql.Transaction.flushCache(Transaction.kt:82)
	at org.jetbrains.exposed.sql.Transaction.commit(Transaction.kt:59)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction(ThreadLocalTransactionManager.kt:105)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:75)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:58)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction$default(ThreadLocalTransactionManager.kt:58)
	at io.myapp.user.register.path.UserRegisterPath.registerUser(UserRegisterPath.kt:67)
	at io.myapp.user.register.path.UserRegisterPath.validateRequest(UserRegisterPath.kt:63)
	at io.myapp.user.register.path.UserRegisterPath$getPath$1.invokeSuspend(UserRegisterPath.kt:29)
	at io.myapp.user.register.path.UserRegisterPath$getPath$1.invoke(UserRegisterPath.kt)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:282)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(PipelineContext.kt:67)
	at io.ktor.util.pipeline.SuspendFunctionGun.proceed(PipelineContext.kt:141)
	at io.ktor.util.pipeline.SuspendFunctionGun.execute(PipelineContext.kt:161)
	at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:27)
	at io.ktor.routing.Routing.executeResult(Routing.kt:147)
	at io.ktor.routing.Routing.interceptor(Routing.kt:34)
	at io.ktor.routing.Routing$Feature$install$1.invokeSuspend(Routing.kt:99)
	at io.ktor.routing.Routing$Feature$install$1.invoke(Routing.kt)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:282)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(PipelineContext.kt:67)
	at io.ktor.util.pipeline.SuspendFunctionGun.proceed(PipelineContext.kt:141)
	at io.ktor.features.ContentNegotiation$Feature$install$1.invokeSuspend(ContentNegotiation.kt:106)
	at io.ktor.features.ContentNegotiation$Feature$install$1.invoke(ContentNegotiation.kt)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:282)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(PipelineContext.kt:67)
	at io.ktor.util.pipeline.SuspendFunctionGun.proceed(PipelineContext.kt:141)
	at io.ktor.util.pipeline.SuspendFunctionGun.execute(PipelineContext.kt:161)
	at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:27)
	at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$2.invokeSuspend(DefaultEnginePipeline.kt:118)
	at io.ktor.server.engine.DefaultEnginePipelineKt$defaultEnginePipeline$2.invoke(DefaultEnginePipeline.kt)
	at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:282)
	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(PipelineContext.kt:67)
	at io.ktor.util.pipeline.SuspendFunctionGun.proceed(PipelineContext.kt:141)
	at io.ktor.util.pipeline.SuspendFunctionGun.execute(PipelineContext.kt:161)
	at io.ktor.util.pipeline.Pipeline.execute(Pipeline.kt:27)
	at io.ktor.server.jetty.JettyKtorHandler$handle$2.invokeSuspend(JettyKtorHandler.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:238)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
Buy as you can see, I already have the `username` column in my `users` table
<img width="305" alt="Screen Shot 2019-06-28 at 10 26 58 PM" src="https://user-images.githubusercontent.com/12965058/60361594-e46d9400-99f3-11e9-947f-34503848b5ff.png">

Connection URL: `"jdbc:h2:${databaseFile.path};DATABASE_TO_UPPER=false;"`
h2 version: `1.4.199`
Exposed version: `0.15.1`

**Comment by Tapac** [comment]
I'm not sure, but maybe the problem is here:
```kotlin
override val id: Column<EntityID<String>>
        get() = username.primaryKey().entityId() <!-- you should not declare primaryKey twice
    val username = varchar("username", 20).primaryKey()
```

try to replace it with simple: `username.entityId()`

**Comment by PHELAT** [comment]
@Tapac 
I've tried it but still it doesn't work

**Comment by Tapac** [comment]
Please remove `get()` from `val id` declaration as it will create different instances of id column, I guess that's why you've got an exception.
