### ISSUE TITLE
java.lang.IllegalStateException when creating new object with DAO (only with reference to different table)

### ISSUE THREAD

**Issue by MaxWipfli** [JetBrains/Exposed#645]
When inserting a new entry into a table with a reference on another table, i get the following exception:

```
Exception in thread "main" java.lang.IllegalStateException: No transaction in context.
	at org.jetbrains.exposed.sql.transactions.TransactionManager$Companion.current(TransactionApi.kt:89)
	at org.jetbrains.exposed.dao.EntityClass.warmCache(Entity.kt:501)
	at org.jetbrains.exposed.dao.EntityClass.testCache(Entity.kt:538)
	at org.jetbrains.exposed.dao.EntityClass.findById(Entity.kt:519)
	at org.jetbrains.exposed.dao.EntityClass.findById(Entity.kt:510)
	at org.jetbrains.exposed.dao.Entity.getValue(Entity.kt:240)
	at com.casharer.app.api.AuthToken.getUser(AuthToken.kt)
	at com.casharer.app.api.AuthToken.toString(AuthToken.kt:16)
	at java.base/java.lang.String.valueOf(String.java:2951)
	at java.base/java.io.PrintStream.println(PrintStream.java:897)
	at api.ServerKt.main(Server.kt:40)
	at api.ServerKt.main(Server.kt)
```

Actually, the exception only triggers when I try to access the `AuthUser` object I created (e.g. try to print it). If I put the `println()` into the `transaction` module, everything works as expected. I assume that I must somehow "commit" the insert, but I haven't found out how. As I already mentioned, the exception only occurs when I insert an object which relates to a different table.

Here is the full program:
Server.kt
```kotlin
package api

import org.jetbrains.exposed.sql.Database
import org.jetbrains.exposed.sql.SchemaUtils
import org.jetbrains.exposed.sql.transactions.TransactionManager
import org.jetbrains.exposed.sql.transactions.transaction
import java.time.Instant

val sqlHost = "172.17.0.2"
val sqlPort = 3306
val sqlDatabase = "test"
val sqlUser = "root"
val sqlPassword = "12345678"

fun main() {
    Database.connect("jdbc:mysql://$sqlHost:$sqlPort/$sqlDatabase", driver="com.mysql.cj.jdbc.Driver",
        user = sqlUser, password = sqlPassword)

    transaction {
        SchemaUtils.create(Users, AuthTokens)
    }

    val newUser = transaction {
        User.new {
            email = "mail@example.com"
            firstName = "Peter"
            lastName = "Miller"
        }
    }

    val token = transaction {
        AuthToken.new {
            token = "123456"
            creationTime = Instant.now().epochSecond
            lifetime = 60 * 60 * 24 * 30
            user = newUser
        }
    }

    println(token)
}
```

Users.kt
```kotlin
package api

import org.jetbrains.exposed.dao.IntIdTable

object Users : IntIdTable("users") {
    val email = varchar("email", 128).uniqueIndex()
    val firstName = varchar("first_name", 128)
    val lastName = varchar("last_name", 128)
}
```

User.kt
```kotlin
package api

import org.jetbrains.exposed.dao.EntityID
import org.jetbrains.exposed.dao.IntEntity
import org.jetbrains.exposed.dao.IntEntityClass

class User(id: EntityID<Int>) : IntEntity(id) {
    companion object : IntEntityClass<User>(Users)

    var email by Users.email
    var firstName by Users.firstName
    var lastName by Users.lastName

    val token by AuthToken referrersOn AuthTokens.user
}
```

AuthTokens.kt
```kotlin
package api

import org.jetbrains.exposed.dao.IntIdTable

object AuthTokens : IntIdTable("auth_tokens") {
    val token = varchar("token", 256)
    val creationTime = long("creation_time")
    val lifetime = long("lifetime")
    val user = reference("user_id", Users)
}
```

AuthToken.kt
```kotlin
package api

import org.jetbrains.exposed.dao.EntityID
import org.jetbrains.exposed.dao.IntEntity
import org.jetbrains.exposed.dao.IntEntityClass

class AuthToken(id: EntityID<Int>) : IntEntity(id) {
    companion object : IntEntityClass<AuthToken>(AuthTokens)

    var token by AuthTokens.token
    var creationTime by AuthTokens.creationTime
    var lifetime by AuthTokens.lifetime
    var user by User referencedOn AuthTokens.user
}
```

**Comment by Tapac** [comment]
The problem is that all references are kept in transaction scope EntityCache which are not accessible outside `transaction` block.

**Comment by MaxWipfli** [comment]
Okey. Thanks!
I just assumed that objects can be reused outside transaction scope, but that clears it up.
