### ISSUE TITLE
Querying for Char Columns throws illegalStateException

### ISSUE THREAD

**Issue by donpaul120** [JetBrains/Exposed#660]
```
object Users : IntIdTable() {
    val gender = char("gender")
    val mobileNo = varchar("mobile_no", 19)
    val createdAt = datetime("created_at")
    val updatedAt = datetime("updated_at")
    val deletedBy = integer("deleted_by")
    val deletedAt = datetime("deleted_at")
}

```

This is where the error happens!
```
fun ResultRow.toUser(): User {
    val builder = User.newBuilder()
    val descriptor = User.getDescriptor()
    val columns = Users.columns
    println(this[Users.gender]) // This Line Throws Error
    columns.forEach { col ->
        if (this.hasValue(col)) {
            mapToGrpcMessage(col, this, descriptor) { desc, value -> builder.setField(desc, value) }
        }
    }
    return builder.build()
}
```

```
Caused by: java.lang.IllegalArgumentException: Char sequence has more than one element.
	at kotlin.text.StringsKt___StringsKt.single(_Strings.kt:204)
	at org.jetbrains.exposed.sql.CharacterColumnType.valueFromDB(ColumnType.kt:116)
	at org.jetbrains.exposed.sql.ResultRow.rawToColumnValue(Query.kt:52)
	at org.jetbrains.exposed.sql.ResultRow.get(Query.kt:31)
	at core.extensions.SelectKt.toUser(select.kt:83)
	at services.users.repository.UserRepository$getAll$1$1.invoke(UserRepository.kt:59)
	at services.users.repository.UserRepository$getAll$1$1.invoke(UserRepository.kt:14)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$inTopLevelTransaction$1.invoke(ThreadLocalTransactionManager.kt:154)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$inTopLevelTransaction$2.invoke(ThreadLocalTransactionManager.kt:195)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:202)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction(ThreadLocalTransactionManager.kt:194)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$transaction$1.invoke(ThreadLocalTransactionManager.kt:132)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:202)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:105)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:103)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction$default(ThreadLocalTransactionManager.kt:102)
	at services.users.repository.UserRepository$getAll$1.get(UserRepository.kt:35)
	at services.users.repository.UserRepository$getAll$1.get(UserRepository.kt:14)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1771)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1763)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```

**Comment by Tapac** [comment]
@donpaul120 , could you please specify :
1. What database do you use?
2. Is `Users` table created with `SchemaUtils.create` or it mapped to and existing table in a database?

I created a test for a simple read/write case and it passed fine. (see 8ba465a commit).

**Comment by donpaul120** [comment]
@Tapac 
1. Postgres 11.5
2. Mapped to an existing database.

**Comment by donpaul120** [comment]
<img width="1325" alt="Screenshot 2019-10-28 at 4 53 47 PM" src="https://user-images.githubusercontent.com/6430195/67694421-94074280-f9a3-11e9-9200-1856ef3644e4.png">

I've commented out the gender column to bypass the error for now.

**Comment by donpaul120** [comment]
@Tapac I think I have been able to debug the problem..

So when I modify the `gender` column from char(2) to char(1) it works perfectly.

I don't know what that could really mean, but those are my findings...

**Comment by Tapac** [comment]
`char` column in Exposed maps to a single character column while you have two chars column. 
You may replace it with `vatchar("", 2)` column
