### ISSUE TITLE
Select from sub query

### ISSUE THREAD

**Issue by KennethWussmann** [JetBrains/Exposed#686]
Hey, I'd like to know whether and how a 
```sql
SELECT subQuery.something FROM (..) subQuery
```
can be written with exposed.
The only thing I found is `inSubQuery` which doesn't work for my use-case.
Thanks,
~ Kenneth

**Comment by Tapac** [comment]
https://github.com/JetBrains/Exposed/wiki/DSL#alias

**Comment by KennethWussmann** [comment]
Hey again, 
yes I already looked at that, but it's not working. At least not like I expected it to work.

For example:
```kotlin
val adminGroup = Group.new(UUID.randomUUID().toString()) {
    name = "Admin"
}
User.new(UUID.randomUUID().toString()) {
    firstname = "John"
    lastname = "Doe"
    group = adminGroup
}
User.new(UUID.randomUUID().toString()) {
    firstname = "Alice"
    lastname = null
    group = adminGroup
}

val name: ExpressionAlias<String> = Coalesce(Users.lastname, Users.firstname).alias("name")

val subQuery = Users
    .slice(name)
    .select {
        Users.lastname.isNull()
    }
    .alias("subQuery")

val select = Users
    .slice(subQuery[name])
    .selectAll()
    .toList()
```

The expected SQL would be something like this:
```SQL
SELECT subQuery.name FROM (
	SELECT COALESCE(lastname, firstname) name
	FROM user
	WHERE lastname IS NULL
) subQuery;
```

The actual SQL generated is:
```SQL
SELECT name FROM "USER"
```
Which doesn't make sense to me. `name` is not even a column of the `user` table.

I also tried to generate the `subQuery`'s SQL on it's own, which looked correct:
```SQL
SELECT COALESCE("USER".LASTNAME, "USER".FIRSTNAME) name FROM "USER" WHERE "USER".LASTNAME IS NULL
```

Additionally, I'd like to supply conditions to the outer SQL's `WHERE` (otherwise I could use the `subQuery` as it is), but that didn't work either:
```Kotlin
val select = Users
    .slice(subQuery[name])
    .select {
        subQuery[name].eq("Alice")
    }
    .toList()
```
The infix `eq(..)` doesn't except `String` in this case, but it is a valid condition in SQL.

I uploaded [an example project](https://github.com/KennethWussmann/exposed-subquery) containing [above scenario](https://github.com/KennethWussmann/exposed-subquery/blob/master/src/test/kotlin/me/test/exposednested/ExposedApplicationTest.kt).

Thank you.

**Comment by Tapac** [comment]
First of all, if you want to call:
```sql
select coalesce(Users.lastName, Users.firstName) as name from Users where Users.lastName is null
```
You don't need to use subquery. A simple query with expression alias will be enough:
```kotlin
val name: ExpressionAlias<String> = Coalesce(Users.lastname, Users.firstname).alias("name")

val subQuery = Users
    .slice(name)
    .select {
        Users.lastname.isNull() and name eq stringLiteral("Alice")
    }
```

`eq` function with `Expression` receiver requires Expression as a parameter. There are `*Literal  ` functions in Exposed to wrap different values.

**Comment by KennethWussmann** [comment]
Sure, it's just an example.
Okay the `*Literal` wrappers worked fine. 

Is there a way to `wrapRows` of a `SELECT` with a sub-query?

For example:
```Kotlin
val select = subQuery
    .select {
        subQuery[name].eq(stringLiteral("Alice"))
    }
    .let(User.Companion::wrapRows)
    .toList()
```
The generated `SELECT` looks fine:
```SQL
SELECT subQuery.ID, subQuery.GROUP_ID, subQuery.FIRSTNAME, subQuery.LASTNAME
FROM (SELECT COALESCE("USER".LASTNAME, "USER".FIRSTNAME) name,
             "USER".ID,
             "USER".GROUP_ID,
             "USER".FIRSTNAME,
             "USER".LASTNAME
      FROM "USER"
      WHERE "USER".LASTNAME IS NULL) subQuery
WHERE name = 'Alice'
```
But it failed to wrap it to the table `User`:
<details>
  <summary>java.lang.IllegalStateException: me.test.exposednested.Users.id is not in record set</summary>
  
```
    at org.jetbrains.exposed.sql.ResultRow.getRaw(Query.kt:59)
	at org.jetbrains.exposed.sql.ResultRow.get(Query.kt:24)
	at org.jetbrains.exposed.dao.EntityClass.wrapRow(Entity.kt:575)
	at org.jetbrains.exposed.dao.EntityClass$wrapRows$1.invoke(Entity.kt:562)
	at org.jetbrains.exposed.dao.EntityClass$wrapRows$1.invoke(Entity.kt:490)
	at org.jetbrains.exposed.sql.IterableExKt$mapLazy$1$iterator$1.next(IterableEx.kt:128)
	at kotlin.collections.CollectionsKt___CollectionsKt.toCollection(_Collections.kt:1155)
	at kotlin.collections.CollectionsKt___CollectionsKt.toMutableList(_Collections.kt:1188)
	at kotlin.collections.CollectionsKt___CollectionsKt.toList(_Collections.kt:1179)
	at me.test.exposednested.ExposedApplicationTest$test$1.invoke(ExposedApplicationTest.kt:48)
	at me.test.exposednested.ExposedApplicationTest$test$1.invoke(ExposedApplicationTest.kt:9)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$inTopLevelTransaction$1.invoke(ThreadLocalTransactionManager.kt:156)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$inTopLevelTransaction$2.invoke(ThreadLocalTransactionManager.kt:197)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:205)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction(ThreadLocalTransactionManager.kt:196)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$transaction$1.invoke(ThreadLocalTransactionManager.kt:134)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:205)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:106)
	at me.test.exposednested.ExposedApplicationKt.dbTransaction(ExposedApplication.kt:19)
	at me.test.exposednested.ExposedApplicationTest.test(ExposedApplicationTest.kt:13)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:532)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:171)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:167)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:114)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:59)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$4(NodeTestTask.java:108)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:98)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:74)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$4(NodeTestTask.java:112)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:98)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:74)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$4(NodeTestTask.java:112)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:98)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:74)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:220)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:188)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:202)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:181)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:69)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

```
</details>

**Comment by jassielcastro** [comment]
I have found this other way, using the abstract Function class and creating an internal Query. You can check this post where it is better explained:

https://medium.com/@jassielcastro/exposed-in-action-customizing-results-with-subqueries-in-ktor-e0eda69a7b31

**Comment by sadiqueWiseboxs** [comment]
@jassielcastro Do you also know a way to eager load with condition, like if I want to eager load all the team members but the members age must be less than 30, I will we query this
