### ISSUE TITLE
Getting NoClassDefFoundError on Database.connect()

### ISSUE THREAD

**Issue by rikusen0335** [JetBrains/Exposed#697]
### What's happened
According to title, I'm getting error on Database.connect().
Looks like no errors on compile.

### Expected Behavior
Connect to database (file)

### Environment
* IntelliJ IDEA 2019.2.2 CE
* Windows 10 Pro
* Exposed 0.18.1

### Sources
<details>
  <summary>Error contents</summary>

```
java.lang.NoClassDefFoundError: org/jetbrains/exposed/sql/Database
        at net.rikusen.sample.SamplePlugin.onEnable(SamplePlugin.kt:53) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[spigot-1.14.4.jar:git-Spigot-56f8471-ccd47a5]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:352) [spigot-1.14.4.jar:git-Spigot-56f8471-ccd47a5]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:417) [spigot-1.14.4.jar:git-Spigot-56f8471-ccd47a5]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:461) [spigot-1.14.4.jar:git-Spigot-56f8471-ccd47a5]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:375) [spigot-1.14.4.jar:git-Spigot-56f8471-ccd47a5]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:449) [spigot-1.14.4.jar:git-Spigot-56f8471-ccd47a5]
        at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:266) [spigot-1.14.4.jar:git-Spigot-56f8471-ccd47a5]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:775) [spigot-1.14.4.jar:git-Spigot-56f8471-ccd47a5]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_221]
Caused by: java.lang.ClassNotFoundException: org.jetbrains.exposed.sql.Database
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_221]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:135) ~[spigot-1.14.4.jar:git-Spigot-56f8471-ccd47a5]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:81) ~[spigot-1.14.4.jar:git-Spigot-56f8471-ccd47a5]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_221]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_221]
        ... 10 more
```
</details>

<details>
  <summary>Code</summary>

```kotlin
import org.jetbrains.exposed.sql.*
import org.jetbrains.exposed.sql.transactions.transaction

class SamplePlugin : JavaPlugin(), Listener, CommandExecutor {
    override fun onEnable() {
        server.pluginManager.registerEvents(this, this)

        Database.connect("jdbc:sqlite:file:test?mode=memory&cache=shared", "org.sqlite.JDBC")
    }
}
```

</details>

<details>
  <summary>Gradle</summary>

```gradle
buildscript {
    ext {
        junit_version = '4.12'
        kotlin_version = '1.3.21'
        spigot_version = '1.13.2-R0.1-SNAPSHOT'
    }
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.21"
    }
}

apply plugin: 'java'
apply plugin: 'kotlin'

group = pluginGroup
version = pluginVersion

sourceCompatibility = 1.8
targetCompatibility = 1.8

repositories {
    mavenCentral()
    jcenter()
    maven {
        name = 'spigotmc-repo'
        url = 'https://hub.spigotmc.org/nexus/content/groups/public/'
    }
    maven {
        name = 'sonatype'
        url = 'https://oss.sonatype.org/content/groups/public/'
    }
}

dependencies {
    testImplementation group: 'junit', name: 'junit', version: junit_version
    testRuntimeOnly group: 'junit', name: 'junit', version: junit_version
    compile "org.spigotmc:spigot-api:$spigot_version"
    compile "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"

    compile "org.jetbrains.exposed:exposed-core:0.18.1"
    compile "org.jetbrains.exposed:exposed-dao:0.18.1"
    compile "org.jetbrains.exposed:exposed-jdbc:0.18.1"
    compile "org.xerial:sqlite-jdbc:3.21.0.1"
}

import org.apache.tools.ant.filters.ReplaceTokens

processResources {
    from(sourceSets.main.resources.srcDirs) {
        filter ReplaceTokens, tokens: [version: version]
    }
}

jar {
    from {
        configurations.compile.collect {
            it.isDirectory() ? it : zipTree(it)
        }
    }
}
```

</details>

**Comment by Tapac** [comment]
Could you locate a `org/jetbrains/exposed/sql/Database` file inside your jar? As I understand you pack all dependencies inside a single jar.

**Comment by rikusen0335** [comment]
Thank you for answering! Fortunately, I figured it out. Sorry.
The cause was as you say, I didn't include the exposed in my jar.

**Comment by AdityaAnand1** [comment]
Hey @rikusen0335 

> I didn't include the exposed in my jar.

Can you please elaborate how you included exposed in my jar, I'm facing the same problem currently. 

![image](https://user-images.githubusercontent.com/13274079/71777985-b766f300-2fcd-11ea-8f5d-6d5729ac663a.png)


Marking it as exported under Module settings dialog in Intellij doesn't seem to do anything.

**Comment by AdityaAnand1** [comment]
Also, when I open up the JAR (by renaming as a zip), exposed is in fact included:

![image](https://user-images.githubusercontent.com/13274079/71778019-2b090000-2fce-11ea-88d4-87d1b6b76fb3.png)

**Comment by rikusen0335** [comment]
I wrote codes on `build.gradle` for it.

```gradle
jar {
    exclude 'META-INF/*.SF', 'META-INF/*.DSA', 'META-INF/*.RSA', 'META-INF/*.MF'
    manifest {
        attributes(
                'Class-Path': configurations.compile.collect { it.getName() }.join(' ')
        )
    }
    from {
        configurations.compile.collect { it.isDirectory() ? it : zipTree(it) }
    }
}
```

I'm not sure if this helps, but feel free to ask anything.

Btw, there is differnet way to figure out this I think.
