### ISSUE TITLE
Cryptic error during deployment

### ISSUE THREAD

**Issue by AdityaAnand1** [JetBrains/Exposed#756]
```
Exception in thread "main" java.util.ServiceConfigurationError: org.jetbrains.exposed.sql.DatabaseConnectionAutoRegistration: Provider org.jetbrains.exposed.jdbc.ExposedConnectionImpl not found
        at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:590)
        at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.nextProviderClass(ServiceLoader.java:1212)
        at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1221)
        at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1265)
        at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1300)
        at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1385)
        at kotlin.collections.CollectionsKt___CollectionsKt.firstOrNull(_Collections.kt:222)
        at org.jetbrains.exposed.sql.Database.<clinit>(Database.kt:64)
        at db.DB.init(DB.kt:20)
        at ApplicationKt.module(Application.kt:52)
        at ApplicationKt$main$1.invoke(Application.kt:33)
        at ApplicationKt$main$1.invoke(Application.kt)
        at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.instantiateAndConfigureApplication(ApplicationEngineEnvironmentReloading.kt:293)
        at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.createApplication(ApplicationEngineEnvironmentReloading.kt:137)
        at io.ktor.server.engine.ApplicationEngineEnvironmentReloading.start(ApplicationEngineEnvironmentReloading.kt:257)
        at io.ktor.server.netty.NettyApplicationEngine.start(NettyApplicationEngine.kt:126)
        at ApplicationKt.main(Application.kt:34)

```

Any ideas what could be causing this?

I'm starting the database connecting via environment variables:

```
        Database.connect(
            url = env[CoreEnvVariables.SQL_URL]!!,
            driver = "com.mysql.cj.jdbc.Driver",
            user = env[CoreEnvVariables.SQL_USER]!!,
            password = env[CoreEnvVariables.SQL_PASSWORD]!!
        )
```

The .env looks like 

```
SQL_URL=jdbc:mysql://localhost:3306/testdb
SQL_USER=root
SQL_PASSWORD=password
```

The above error occurs when running a JAR via shadowJar.

**Comment by Tapac** [comment]
Do you include `exposed-jdbc` module into your dependencies?

**Comment by AdityaAnand1** [comment]
Indeed it turned out to be an exporting issue.

For future googlers, here's a working example of exporting a runnable jar:

```
jar {
    archiveName "core.jar"
    manifest {
        attributes(
                'Main-Class': "ApplicationKt",
                'Class-Path': configurations.compile.collect { it.getName() }.join(' ')
        )
    }
    from sourceSets.main.output
    dependsOn configurations.runtimeClasspath
    from {
        configurations.runtimeClasspath.findAll { it.name.endsWith('jar') }.collect { zipTree(it) }
    }
}
```
