### ISSUE TITLE
Transaction.exec(stmt: String) does not support INSERT operation

### ISSUE THREAD

**Issue by Zhambul** [JetBrains/Exposed#76]
```
transaction {
    exec("insert into foo values ('bar', 1)")
}
```
Given above code throws **java.util.NoSuchElementException** exception

```
Exception in thread "main" java.util.NoSuchElementException: List is empty.
	at kotlin.collections.CollectionsKt___CollectionsKt.first(_Collections.kt:180)
	at org.jetbrains.exposed.sql.statements.Statement.executeIn$exposed_compileKotlin(Statement.kt:28)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:102)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:96)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:81)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:77)
```
This line in Statement class seems to be the problem

`
val autoInc = if (type == StatementType.INSERT) targets.first().columns.filter { it.columnType.autoinc } else null`

If insert is not supported by design, at least make the exception explicitly tell that

**Comment by Tapac** [comment]
Fixed in master. But i guess it's better to use `foo.insert { it[col1] = 'bar'; it[col2] = 1) } ` instead. It's more type-safe, easy to refactor and sql-injection safe.
