### ISSUE TITLE
Please call Database.connect() before using this code. Even when this command was called. 

### ISSUE THREAD

**Issue by CrownlessX** [JetBrains/Exposed#768]
I got strange issue when trying to put some data to DB.
I'm using Exposed 0.17.3 and spring boot 2.2.0
Got configured db thru Database bean with HikariDataSource 
`return Database.connect(dataSource())`
And trying to save some data to DB from main after app initialization.
But got error that i have to run Database.connect before.
And this command manual rerun have no any imppact on issue.

````
[DEBUG] [main] ResponseProcessorApplicationKt - Running with Spring Boot v2.2.0.RELEASE, Spring v5.2.0.RELEASE
[INFO ] [main] ResponseProcessorApplicationKt - No active profile set, falling back to default profiles: default
[DEBUG] [main] HikariConfig - Driver class oracle.jdbc.OracleDriver found in Thread context class loader jdk.internal.loader.ClassLoaders$AppClassLoader@2626b418
[INFO ] [main] ResponseProcessorApplicationKt - Started ResponseProcessorApplicationKt in 4.851 seconds (JVM running for 10.057)

[DEBUG] [main] HikariConfig - HikariPool-1 - configuration:
[DEBUG] [main] HikariConfig - allowPoolSuspension.............false
[DEBUG] [main] HikariConfig - autoCommit......................true
[DEBUG] [main] HikariConfig - catalog.........................none
[DEBUG] [main] HikariConfig - connectionInitSql...............none
[DEBUG] [main] HikariConfig - connectionTestQuery.............none
[DEBUG] [main] HikariConfig - connectionTimeout...............30000
[DEBUG] [main] HikariConfig - dataSource......................none
[DEBUG] [main] HikariConfig - dataSourceClassName.............none
[DEBUG] [main] HikariConfig - dataSourceJNDI..................none
[DEBUG] [main] HikariConfig - dataSourceProperties............{password=<masked>}
[DEBUG] [main] HikariConfig - driverClassName................."oracle.jdbc.OracleDriver"
[DEBUG] [main] HikariConfig - healthCheckProperties...........{}
[DEBUG] [main] HikariConfig - healthCheckRegistry.............none
[DEBUG] [main] HikariConfig - idleTimeout.....................600000
[DEBUG] [main] HikariConfig - initializationFailTimeout.......1
[DEBUG] [main] HikariConfig - isolateInternalQueries..........false
[DEBUG] [main] HikariConfig - jdbcUrl.........................jdbc:oracle:thin:@localhost:1521:XE
[DEBUG] [main] HikariConfig - leakDetectionThreshold..........0
[DEBUG] [main] HikariConfig - maxLifetime.....................1800000
[DEBUG] [main] HikariConfig - maximumPoolSize.................10
[DEBUG] [main] HikariConfig - metricRegistry..................none
[DEBUG] [main] HikariConfig - metricsTrackerFactory...........com.zaxxer.hikari.metrics.micrometer.MicrometerMetricsTrackerFactory@6fc28e5b
[DEBUG] [main] HikariConfig - minimumIdle.....................10
[DEBUG] [main] HikariConfig - password........................<masked>
[DEBUG] [main] HikariConfig - poolName........................"HikariPool-1"
[DEBUG] [main] HikariConfig - readOnly........................false
[DEBUG] [main] HikariConfig - registerMbeans..................false
[DEBUG] [main] HikariConfig - scheduledExecutor...............none
[DEBUG] [main] HikariConfig - schema..........................none
[DEBUG] [main] HikariConfig - threadFactory...................internal
[DEBUG] [main] HikariConfig - transactionIsolation............default
[DEBUG] [main] HikariConfig - username........................"system"
[DEBUG] [main] HikariConfig - validationTimeout...............5000
[INFO ] [main] HikariDataSource - HikariPool-1 - Starting...
[DEBUG] [main] HikariPool - HikariPool-1 - Added connection oracle.jdbc.driver.T4CConnection@703cb756
[INFO ] [main] HikariDataSource - HikariPool-1 - Start completed.
[DEBUG] [HikariPool-1 housekeeper] HikariPool - HikariPool-1 - Pool stats (total=1, active=0, idle=1, waiting=0)

Exception in thread "main" java.lang.IllegalStateException: Please call Database.connect() before using this code
	at org.jetbrains.exposed.sql.transactions.NotInitializedManager.currentOrNull(TransactionApi.kt:37)
	at org.jetbrains.exposed.sql.transactions.TransactionManager$Companion.currentOrNull(TransactionApi.kt:89)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$transaction$1.invoke(ThreadLocalTransactionManager.kt:107)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:204)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:106)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:104)
	at Repository.save(UsageChargeRepository.kt:17)
	at ResponseProcessorApplicationKt.main(ResponseProcessorApplication.kt:33)
[DEBUG] [HikariPool-1 connection adder] HikariPool - HikariPool-1 - Added connection oracle.jdbc.driver.T4CConnection@1c8ee4b7
...
[DEBUG] [HikariPool-1 connection adder] HikariPool - HikariPool-1 - After adding stats (total=10, active=0, idle=10, waiting=0)
```

**Comment by CrownlessX** [comment]
Ah.. i found issue:
I got during configuration
```
    init {
        TransactionManager.manager.defaultIsolationLevel = Connection.TRANSACTION_READ_COMMITTED
    }
```
And this part caused that.
