### ISSUE TITLE
Syntax error in SQL statement

### ISSUE THREAD

**Issue by MGlolenstine** [JetBrains/Exposed#780]
I get the following error when executing next piece of code:

```
fun main() {
        Database.connect("jdbc:h2:~/testdb;DB_CLOSE_DELAY=-1", driver = "org.h2.Driver", user = "root", password = "")
        transaction {
            val create = measureTimeMillis { SchemaUtils.createMissingTablesAndColumns(RandomText) }
        }
}
```
ERROR:
```
Exception in thread "main" org.jetbrains.exposed.exceptions.ExposedSQLException: org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "ALTER TABLE RANDOMTEXT MODIFY[*] COLUMN TEXT VARCHAR(15) NOT NULL"; expected "., ADD, SET, RENAME, DROP, ALTER"; SQL statement:
ALTER TABLE RANDOMTEXT MODIFY COLUMN TEXT VARCHAR(15) NOT NULL [42001-200]
SQL: [ALTER TABLE RANDOMTEXT MODIFY COLUMN TEXT VARCHAR(15) NOT NULL]
	at org.jetbrains.exposed.sql.statements.Statement.executeIn$exposed_core(Statement.kt:50)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:126)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:112)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:88)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:79)
	at org.jetbrains.exposed.sql.SchemaUtils.execStatements(SchemaUtils.kt:158)
	at org.jetbrains.exposed.sql.SchemaUtils.createMissingTablesAndColumns(SchemaUtils.kt:201)
	at org.jetbrains.exposed.sql.SchemaUtils.createMissingTablesAndColumns$default(SchemaUtils.kt:186)
	at mree.DBLoader$connectToDb$1.invoke(DBLoader.kt:25)
	at mree.DBLoader$connectToDb$1.invoke(DBLoader.kt:10)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$inTopLevelTransaction$1.invoke(ThreadLocalTransactionManager.kt:156)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$inTopLevelTransaction$2.invoke(ThreadLocalTransactionManager.kt:197)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:205)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction(ThreadLocalTransactionManager.kt:196)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$transaction$1.invoke(ThreadLocalTransactionManager.kt:134)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:205)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:106)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:104)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction$default(ThreadLocalTransactionManager.kt:103)
	at mree.DBLoader.connectToDb(DBLoader.kt:24)
	at mree.DBLoader.<init>(DBLoader.kt:16)
	at mree.MainKt.main(main.kt:5)
	at mree.MainKt.main(main.kt)
```
and it crashes when reaching this line:
```
SchemaUtils.createMissingTablesAndColumns(RandomText)
```
but It's weird, as this one works without problems
```
SchemaUtils.create(RandomText)
```
My table:
```
    object RandomText : Table() {
        val id = integer("id").autoIncrement()
        val text = varchar("text", length = 15)
        override val primaryKey = PrimaryKey(id)
    }
```
Minimal runnable example [here](https://github.com/MGlolenstine/minimalRunnableExampleExposed)

**Comment by MGlolenstine** [comment]
My bad... I've been using the same database for multiple projects :sweat_smile:, after removing them, error went away.
But it's weird, as other project had the same table structure.
