### ISSUE TITLE
AbstractMethodError: SpringTransaction.getConnection

### ISSUE THREAD

**Issue by harjis** [JetBrains/Exposed#783]
This might not be a bug but more of a limitation on my understanding in Spring and all that.

I'm trying to use most recent Exposed version with Spring-transaction but when I try to execute a query the application fails with:

```
java.lang.AbstractMethodError: org.jetbrains.exposed.spring.SpringTransactionManager$SpringTransaction.getConnection()Lorg/jetbrains/exposed/sql/statements/api/ExposedConnection;
	at org.jetbrains.exposed.sql.Transaction.getConnection(Transaction.kt) ~[exposed-core-0.20.3.jar:na]
	at org.jetbrains.exposed.sql.Database.metadata$exposed_core(Database.kt:31) ~[exposed-core-0.20.3.jar:na]
	at org.jetbrains.exposed.sql.Database$identifierManager$2.invoke(Database.kt:50) ~[exposed-core-0.20.3.jar:na]
	at org.jetbrains.exposed.sql.Database$identifierManager$2.invoke(Database.kt:17) ~[exposed-core-0.20.3.jar:na]
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74) ~[kotlin-stdlib-1.3.61.jar:1.3.61-release-180 (1.3.61)]
	at org.jetbrains.exposed.sql.Database.getIdentifierManager(Database.kt) ~[exposed-core-0.20.3.jar:na]
	at org.jetbrains.exposed.sql.Transaction$fullIdentity$2.invoke(Transaction.kt:161) ~[exposed-core-0.20.3.jar:na]
	at org.jetbrains.exposed.sql.Transaction$fullIdentity$2.invoke(Transaction.kt:30) ~[exposed-core-0.20.3.jar:na]
	at org.jetbrains.exposed.sql.QueryBuilder.invoke(Expression.kt:34) ~[exposed-core-0.20.3.jar:na]
	at org.jetbrains.exposed.sql.Transaction.fullIdentity$exposed_core(Transaction.kt:157) ~[exposed-core-0.20.3.jar:na]
	at org.jetbrains.exposed.sql.Column.toQueryBuilder(Column.kt:33) ~[exposed-core-0.20.3.jar:na]
```
My build.gradle.kts is as follows:

```kotlin
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
	id("org.springframework.boot") version "2.2.4.RELEASE"
	id("io.spring.dependency-management") version "1.0.9.RELEASE"
	kotlin("jvm") version "1.3.61"
	kotlin("plugin.spring") version "1.3.61"
}

group = "com.example"
version = "0.0.1-SNAPSHOT"
java.sourceCompatibility = JavaVersion.VERSION_1_8

val developmentOnly by configurations.creating
configurations {
	runtimeClasspath {
		extendsFrom(developmentOnly)
	}
}

repositories {
	mavenCentral()
	jcenter()
}

dependencies {
	implementation("org.springframework.boot:spring-boot-starter-web")
	implementation("com.fasterxml.jackson.module:jackson-module-kotlin")
	implementation("org.jetbrains.kotlin:kotlin-reflect")
	implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")
	developmentOnly("org.springframework.boot:spring-boot-devtools")
	runtimeOnly("com.h2database:h2")
	testImplementation("org.springframework.boot:spring-boot-starter-test") {
		exclude(group = "org.junit.vintage", module = "junit-vintage-engine")
	}

	implementation("org.jetbrains.exposed", "exposed-core", "0.20.3")
	implementation("org.jetbrains.exposed", "exposed-dao", "0.20.3")
	implementation("org.jetbrains.exposed", "exposed-jdbc", "0.20.3")
	implementation("org.jetbrains.exposed", "spring-transaction", "0.11.2")
	implementation("org.springframework.boot:spring-boot-starter-data-jdbc")
}

tasks.withType<Test> {
	useJUnitPlatform()
}

tasks.withType<KotlinCompile> {
	kotlinOptions {
		freeCompilerArgs = listOf("-Xjsr305=strict")
		jvmTarget = "1.8"
	}
}
```
SpringTransactionManager is enabled by:
```kotlin
package com.example.exposedspringtransaction.config

import org.jetbrains.exposed.spring.SpringTransactionManager
import org.springframework.boot.autoconfigure.AutoConfigureAfter
import org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
import org.springframework.context.annotation.Bean
import org.springframework.context.annotation.Configuration
import org.springframework.transaction.annotation.EnableTransactionManagement
import javax.sql.DataSource

@Configuration
@AutoConfigureAfter(DataSourceAutoConfiguration::class)
@EnableTransactionManagement
class DatabaseConfig {
    @Bean
    fun springTransactionManager (dataSource: DataSource) = SpringTransactionManager(dataSource)
}

```
Minimal reproducable code can be found [here](https://github.com/harjis/exposed-spring-transaction)

I have tried to look guidance in `exposed-spring-boot-starter` project and to me the implementation looks very similar. The funny thing is that when I use that project my application works as intended. The code difference can be found [here](https://github.com/harjis/exposed-spring-transaction/commit/6b5e46fb7126a4eb1e2210988512b49f4c77b90e)

**Comment by Tapac** [comment]
Why do you use `spring-transaction` '0.11.2' instead of '0.20.3'?

**Comment by harjis** [comment]
I actually thought it is the latest release. So I guess the problem here is that I read mvnrepository releases wrong. I’ll try out with more recent version later today

**Comment by harjis** [comment]
Right so the problem was that I was confused on what actually is the newest version of spring-transaction and ended up using a older version. Bumping up the version to 0.20.3 fixed the issue.

Thanks for the help!
