### ISSUE TITLE
Unexpected value of type Char

### ISSUE THREAD

**Issue by Zhambul** [JetBrains/Exposed#79]
My table

```
object SportTable : BaseTable("sport") {
    val pos = integer("pos").index()
    val name = hstore("name")
    val icon = char("icon").nullable()
    val color = varchar("color", length = 255).nullable()
    val img = varchar("img", length = 255).nullable()
}
```
It created a table in my postgress database table. icon has CHAR type 

```
class CharacterColumnType() : ColumnType() {
    override fun sqlType(): String  = "CHAR"

    override fun valueFromDB(value: Any): Any {
        return when(value) {
            is Char -> value
            is Number -> value.toChar()
            else -> error("Unexpected value of type Char: $value")
        }
    }
}
```

When I read a record value came as type String, and therefore it fails, hence is only parses Char or Number. I don't know why it didn't read value as Char

```
 Unexpected value of type Char: (
java.lang.IllegalStateException: Unexpected value of type Char: (
	at org.jetbrains.exposed.sql.CharacterColumnType.valueFromDB(ColumnType.kt:97)
	at org.jetbrains.exposed.sql.ResultRow.get(Query.kt:23)
	at org.jetbrains.exposed.dao.Entity.lookup(Entity.kt:243)
	at org.jetbrains.exposed.dao.Entity.getValue(Entity.kt:228)
```

**Comment by Tapac** [comment]
Thank you for report. Fixed in master.
