### ISSUE TITLE
Selectув EnumsType Error (H2)

### ISSUE THREAD

**Issue by SchweinchenFuntik** [JetBrains/Exposed#801]
the table is created and insertion occurs, the error is only on the selection

```
enum class TypesTariffs{
    FOO, BAR
}

object Tariffs: Table() {
    val type = enumeration("TYPE", TypesTariffsDelta::class)
}



class DataBaseTest : StringSpec({
    val db = Database.connect(
        "jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;",
        "org.h2.Driver",
        user = "sa"
    )

    "DATA_BASE" {
        transaction(db) {
            SchemaUtils.createDatabase()
            SchemaUtils.create(Tariffs)

            TariffsDelta.insert {
                it[type] = TypesTariffs.FOO
            }

            val selectAll = Tariffs.selectAll()
            val rs = selectAll.execute(this)
            Tariffs.selectAll().toList().size shouldBe 1
        }
    }
```

```
00:22:51.126 [pool-2-thread-1 @coroutine#4] WARN Exposed - Transaction attempt #1 failed: org.h2.jdbc.JdbcSQLNonTransientException: General error: "java.lang.NullPointerException" [50000-200]. Statement(s): SELECT TARIFFSDELTA."TYPE" FROM TARIFFSDELTA
org.jetbrains.exposed.exceptions.ExposedSQLException: org.h2.jdbc.JdbcSQLNonTransientException: General error: "java.lang.NullPointerException" [50000-200]
	at org.jetbrains.exposed.sql.statements.Statement.executeIn$exposed_core(Statement.kt:63)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:126)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:112)
	at org.jetbrains.exposed.sql.statements.Statement.execute(Statement.kt:29)
	at test.DataBaseTest$1$1$1.invoke(tests.kt:49)
	at test.DataBaseTest$1$1$1.invoke(tests.kt:17)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$inTopLevelTransaction$1.invoke(ThreadLocalTransactionManager.kt:156)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$inTopLevelTransaction$2.invoke(ThreadLocalTransactionManager.kt:197)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:205)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction(ThreadLocalTransactionManager.kt:196)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$transaction$1.invoke(ThreadLocalTransactionManager.kt:134)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:205)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:106)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:104)
	at test.DataBaseTest$1$1.invokeSuspend(tests.kt:26)
	at test.DataBaseTest$1$1.invoke(tests.kt)
	at io.kotlintest.runner.jvm.TestCaseExecutor$executeTest$supervisorJob$1$invokeSuspend$$inlined$map$lambda$1.invokeSuspend(TestCaseExecutor.kt:121)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.h2.jdbc.JdbcSQLNonTransientException: General error: "java.lang.NullPointerException" [50000-200]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:505)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)
	at org.h2.message.DbException.get(DbException.java:194)
	at org.h2.message.DbException.convert(DbException.java:347)
	at org.h2.message.DbException.toSQLException(DbException.java:319)
	at org.h2.message.TraceObject.logAndConvert(TraceObject.java:366)
	at org.h2.jdbc.JdbcPreparedStatement.executeQuery(JdbcPreparedStatement.java:126)
	at org.jetbrains.exposed.sql.statements.jdbc.JdbcPreparedStatementImpl.executeQuery(JdbcPreparedStatementImpl.kt:21)
	at org.jetbrains.exposed.sql.Query.executeInternal(Query.kt:80)
	at org.jetbrains.exposed.sql.Query.executeInternal(Query.kt:15)
	at org.jetbrains.exposed.sql.statements.Statement.executeIn$exposed_core(Statement.kt:61)
	... 21 common frames omitted
Caused by: java.lang.NullPointerException: null
	at org.h2.engine.Session.addTableToDependencies(Session.java:1874)
	at org.h2.engine.Session.startStatementWithinTransaction(Session.java:1832)
	at org.h2.command.Command.executeQuery(Command.java:190)
	at org.h2.jdbc.JdbcPreparedStatement.executeQuery(JdbcPreparedStatement.java:114)
	... 25 common frames omitted
```

**Comment by raharrison** [comment]
Had this issue with latest version of H2 (1.4.200). Don't think this is an Exposed problem - rolling back to 1.4.199 fixes it. Believe it happens in cases where you table has no primary key.

**Comment by Tapac** [comment]
Yes, repeatable read isolation was broken in 1.4.200, see https://github.com/h2database/h2database/issues/2191 issue.

**Comment by SchweinchenFuntik** [comment]
thanks, check tonight
