### ISSUE TITLE
MySQL: JdbcDatabaseMetadataImpl does not define ...  getCurrentScheme()

### ISSUE THREAD

**Issue by MichaelKofler** [JetBrains/Exposed#868]
I try to create a MySQL table with `SchemaUtils.create(...)`. However, this fails:

Kotlin code:

```
Database.connect("jdbc:mysql://localhost/test1",
        driver = "com.mysql.cj.jdbc.Driver",
        user = "test1",
        password = "geheim")

transaction {
        SchemaUtils.create(RunLogs)
}

object RunLogs: IntIdTable() {
    val status = varchar("status", 50)
    val ts = datetime("ts").defaultExpression(CurrentDateTime())
}

```

dependencies in build.gradle file:

```
dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8"

    compile "org.jetbrains.exposed:exposed-core:0.23.1"
    compile "org.jetbrains.exposed:exposed-dao:0.23.1"
    compile "org.jetbrains.exposed:exposed-jdbc:0.23.1"
    compile "org.jetbrains.exposed:exposed-java-time:0.23.1"
    compile "mysql:mysql-connector-java:8.0.19"
}
```

Error message:

```
Exception in thread "main" java.lang.AbstractMethodError: Receiver class org.jetbrains.exposed.sql.statements.jdbc.JdbcDatabaseMetadataImpl does not define or inherit an implementation of the resolved method 'abstract java.lang.String getCurrentScheme()' of abstract class org.jetbrains.exposed.sql.statements.api.ExposedDatabaseMetadata.
	at org.jetbrains.exposed.sql.vendors.VendorDialect$tableExists$scheme$1.invoke(Default.kt:600)
	at org.jetbrains.exposed.sql.vendors.VendorDialect$tableExists$scheme$1.invoke(Default.kt:562)
	at org.jetbrains.exposed.sql.statements.jdbc.JdbcConnectionImpl.metadata(JdbcConnectionImpl.kt:47)
	at org.jetbrains.exposed.sql.vendors.VendorDialect.tableExists(Default.kt:600)
	at org.jetbrains.exposed.sql.QueriesKt.exists(Queries.kt:186)
	at org.jetbrains.exposed.sql.SchemaUtils.createStatements(SchemaUtils.kt:79)
	at org.jetbrains.exposed.sql.SchemaUtils.create(SchemaUtils.kt:181)
	at org.jetbrains.exposed.sql.SchemaUtils.create$default(SchemaUtils.kt:179)
	at AppKt$main$1.invoke(App.kt:44)
	at AppKt$main$1.invoke(App.kt)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$inTopLevelTransaction$1.invoke(ThreadLocalTransactionManager.kt:156)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$inTopLevelTransaction$2.invoke(ThreadLocalTransactionManager.kt:197)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:205)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction(ThreadLocalTransactionManager.kt:196)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$transaction$1.invoke(ThreadLocalTransactionManager.kt:134)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:205)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:106)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:104)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction$default(ThreadLocalTransactionManager.kt:103)
	at AppKt.main(App.kt:38)
	at AppKt.main(App.kt)
```

Any ideas?

**Comment by MichaelKofler** [comment]
It has to do with version 0.23.1. It works with 0.21.1 and 0.22.1.

**Comment by Tapac** [comment]
It's strange as there are tests which run with the same dependencies. Is it possible that you have different versions of Exposed in your classpath? Or could you share a sample project to reproduce?

**Comment by MichaelKofler** [comment]
Tested for an hour now, cannot reproduce, strange. I have no explanation, perhaps IJ 2020, or Kotlin 1.3.72 (updated yesterday). Sorry for the noise.
