### ISSUE TITLE
Database.connect not called properly

### ISSUE THREAD

**Issue by martmists** [JetBrains/Exposed#896]
After running the code
```kotlin
val db = Database.connect(
    "jdbc:sqlite:$path/mydb.db",
    "org.sqlite.JDBC")
``` 
and later running
```kotlin
transaction(db) {
    // Stuff
}
``` 

We get the following error:
```java
 java.lang.IllegalStateException: Please call Database.connect() before using this code
	at org.jetbrains.exposed.sql.transactions.NotInitializedManager.currentOrNull(TransactionApi.kt:37) ~[exposed-0.17.7.jar:?]
	at org.jetbrains.exposed.sql.transactions.TransactionManager$Companion.currentOrNull(TransactionApi.kt:89) ~[exposed-0.17.7.jar:?]
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$transaction$1.invoke(ThreadLocalTransactionManager.kt:107) ~[exposed-0.17.7.jar:?]
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:205) ~[exposed-0.17.7.jar:?]
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:106) ~[exposed-0.17.7.jar:?]
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:104) ~[exposed-0.17.7.jar:?]
    ...
```

We have verified the path is valid, however the file is not always created.

**Comment by martmists** [comment]
Solved; The line `TransactionManager.manager.defaultIsolationLevel = Connection.TRANSACTION_SERIALIZABLE` was used before the Database.connect rather than after. Is there a possibility to make this error easier to identify?

**Comment by Tapac** [comment]
There should be another exception before that showing the initial problem.
Also, there is a [section in a FAQ](https://github.com/JetBrains/Exposed/wiki/FAQ#q-sqlite3-fails-with-the-error-transaction-attempt-0-failed-sqlite-supports-only-transaction_serializable-and-transaction_read_uncommitted)

**Comment by martmists** [comment]
That section should probably explicitly specify it should be set AFTER the connect call, and that it will silently fail otherwise.

**Comment by Tapac** [comment]
I had fixed it in the master -  you don't need to override defaultIsolationLevel for SQLite anymore.
Willbne released on the week
