### ISSUE TITLE
In Memory Databases across Transactions

### ISSUE THREAD

**Issue by geertijewski** [JetBrains/Exposed#904]
I would expect that if two `transcations{}` follow each other, I can read the data from the first transaction in the second.

However for in memory databases (I want to use sqlite, but have also tested it with H2 to rule out errors on sqlites part) this does not seem to work. Given the code below, in the second transaction block the Table itself does not exist anymore.

```kotlin
package test

import org.jetbrains.exposed.sql.*
import org.jetbrains.exposed.sql.transactions.transaction
import java.sql.Connection

object TestTable : Table() {
    val a = integer("a")
    val b = integer("b")
}

fun main() {
    //val db = Database.connect("jdbc:sqlite:file:concurrent-customer?mode=memory&cache=shared", "org.sqlite.JDBC")
    val db = Database.connect("jdbc:h2:mem:test", driver = "org.h2.Driver")

    transaction(Connection.TRANSACTION_SERIALIZABLE, 1, db) {
        addLogger(StdOutSqlLogger)
        SchemaUtils.create(TestTable)
    }
    transaction(Connection.TRANSACTION_SERIALIZABLE, 1, db) {
        addLogger(StdOutSqlLogger)
        TestTable.insert {
            it[a] = 1
            it[b] = 1
        }
    }
}
```

```
$ gradle run

> Task :run FAILED
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
SQL: CREATE TABLE IF NOT EXISTS TEST ("A" INT NOT NULL, B INT NOT NULL)
SQL: INSERT INTO TEST ("A", B) VALUES (1, 1)
next transaction; data of previous step should exist
SQL: INSERT INTO TEST ("A", B) VALUES (1, 2)
Exception in thread "main" org.jetbrains.exposed.exceptions.ExposedSQLException: org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "TEST" not found; SQL statement:
INSERT INTO TEST ("A", B) VALUES (?, ?) [42102-199]
SQL: [INSERT INTO Test ("A", B) VALUES (?, ?)]
        at org.jetbrains.exposed.sql.statements.Statement.executeIn$exposed_core(Statement.kt:50)
        at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:126)
        at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:112)
        at org.jetbrains.exposed.sql.statements.Statement.execute(Statement.kt:29)
        at org.jetbrains.exposed.sql.QueriesKt.insert(Queries.kt:73)
        at test.MainKt$main$2.invoke(Main.kt:27)
        at test.MainKt$main$2.invoke(Main.kt)
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$inTopLevelTransaction$1.invoke(ThreadLocalTransactionManager.kt:156)
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$inTopLevelTransaction$2.invoke(ThreadLocalTransactionManager.kt:197)
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:205)
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction(ThreadLocalTransactionManager.kt:196)
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$transaction$1.invoke(ThreadLocalTransactionManager.kt:134)
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:205)
        at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:106)
        at test.MainKt.main(Main.kt:25)
        at test.MainKt.main(Main.kt)
Caused by: org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "TEST" not found; SQL statement:
INSERT INTO TEST ("A", B) VALUES (?, ?) [42102-199]
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:451)
        at org.h2.message.DbException.getJdbcSQLException(DbException.java:427)
        at org.h2.message.DbException.get(DbException.java:205)
        at org.h2.message.DbException.get(DbException.java:181)
        at org.h2.command.Parser.readTableOrView(Parser.java:7146)
        at org.h2.command.Parser.readTableOrView(Parser.java:7117)
        at org.h2.command.Parser.parseInsert(Parser.java:1682)
        at org.h2.command.Parser.parsePrepared(Parser.java:891)
        at org.h2.command.Parser.parse(Parser.java:788)
        at org.h2.command.Parser.parse(Parser.java:760)
        at org.h2.command.Parser.prepareCommand(Parser.java:683)
        at org.h2.engine.Session.prepareLocal(Session.java:627)
        at org.h2.engine.Session.prepareCommand(Session.java:565)
        at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1292)
        at org.h2.jdbc.JdbcPreparedStatement.<init>(JdbcPreparedStatement.java:77)
        at org.h2.jdbc.JdbcConnection.prepareStatement(JdbcConnection.java:1211)
        at org.jetbrains.exposed.sql.statements.jdbc.JdbcConnectionImpl.prepareStatement(JdbcConnectionImpl.kt:54)
        at org.jetbrains.exposed.sql.statements.InsertStatement.prepared(InsertStatement.kt:136)
        at org.jetbrains.exposed.sql.statements.Statement.executeIn$exposed_core(Statement.kt:48)
        ... 15 more

FAILURE: Build failed with an exception.

**Comment by Tapac** [comment]
Please check https://github.com/JetBrains/Exposed/wiki/DataBase-and-DataSource H2 part. By default h2 keep alive only for a single connection
