### ISSUE TITLE
Using blocking transactions after a suspending transaction causes a "Connection is closed" exception

### ISSUE THREAD

**Issue by MrPowerGamerBR** [JetBrains/Exposed#910]
I'm not sure if it is intentional, I tried searching about it on the Wiki, FAQ and in the issues and I couldn't find anything about it. The only similar issues that I've found was #680 and #601

Of course, you *shouldn't* mix blocking and suspending methods, after all, why would you do that? The reason I found out about it is that I only recently found out that Exposed does have coroutine-aware methods (whoops) and I started migrating away from the blocking transactions to the suspended transactions, so I changed a few of my transactions to suspended transactions... then I found out that you can't mix them, oops.

```kotlin
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.GlobalScope
import kotlinx.coroutines.launch
import org.jetbrains.exposed.dao.id.LongIdTable
import org.jetbrains.exposed.sql.Database
import org.jetbrains.exposed.sql.SchemaUtils
import org.jetbrains.exposed.sql.selectAll
import org.jetbrains.exposed.sql.transactions.experimental.newSuspendedTransaction
import org.jetbrains.exposed.sql.transactions.transaction
import kotlin.concurrent.thread

fun main() {
	val database = Database.connect("jdbc:postgresql://127.0.0.1:5432/teste", driver = "org.postgresql.Driver",
			user = "postgres", password = "postgres")

	transaction(database) {
		SchemaUtils.createMissingTablesAndColumns(
				OriginalTable
		)
	}

	GlobalScope.launch {
		println("Starting...")

		val transaction1 = newSuspendedTransaction(Dispatchers.IO, database) {
			OriginalTable.selectAll()
					.toList()
		}

		println("Coroutine finished")

		val transaction2 = transaction(database) {
			OriginalTable.selectAll()
					.toList()
		}

		println("Done!")
	}

	thread {
		while (true) {
			Thread.sleep(1_000)
		}
	}
}

object OriginalTable : LongIdTable() {
	val testNumber = integer("test_number")
}
```

```
10:32:30.445 [main] INFO Exposed - Preparing create tables statements took 403ms
10:32:30.463 [main] INFO Exposed - Executing create tables statements took 14ms
10:32:30.609 [main] INFO Exposed - Extracting table columns took 146ms
10:32:31.210 [main] INFO Exposed - Extracting column constraints took 600ms
10:32:31.210 [main] INFO Exposed - Preparing alter table statements took 747ms
10:32:31.211 [main] INFO Exposed - Executing alter table statements took 1ms
10:32:31.229 [main] INFO Exposed - Checking mapping consistence took 18ms
Starting...
10:32:31.386 [DefaultDispatcher-worker-1] DEBUG Exposed - SELECT original.id, original.test_number FROM original
Coroutine finished
Exception in thread "DefaultDispatcher-worker-2" org.jetbrains.exposed.exceptions.ExposedSQLException: org.postgresql.util.PSQLException: This connection has been closed.
SQL: [SELECT original.id, original.test_number FROM original]
	at org.jetbrains.exposed.sql.statements.Statement.executeIn$exposed_core(Statement.kt:50)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:126)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:112)
	at org.jetbrains.exposed.sql.Query.iterator(Query.kt:212)
	at kotlin.collections.CollectionsKt___CollectionsKt.toCollection(_Collections.kt:1200)
	at kotlin.collections.CollectionsKt___CollectionsKt.toMutableList(_Collections.kt:1233)
	at kotlin.collections.CollectionsKt___CollectionsKt.toList(_Collections.kt:1224)
	at com.mrpowergamerbr.loritta.listeners.TestKt$main$2$transaction2$1.invoke(Test.kt:36)
	at com.mrpowergamerbr.loritta.listeners.TestKt$main$2$transaction2$1.invoke(Test.kt)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$transaction$1.invoke(ThreadLocalTransactionManager.kt:121)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:212)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:113)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:111)
	at com.mrpowergamerbr.loritta.listeners.TestKt$main$2.invokeSuspend(Test.kt:34)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
Caused by: org.postgresql.util.PSQLException: This connection has been closed.
	at org.postgresql.jdbc.PgConnection.checkClosed(PgConnection.java:857)
	at org.postgresql.jdbc.PgConnection.prepareStatement(PgConnection.java:1763)
	at org.postgresql.jdbc.PgConnection.prepareStatement(PgConnection.java:410)
	at org.postgresql.jdbc.PgConnection.prepareStatement(PgConnection.java:1777)
	at org.jetbrains.exposed.sql.statements.jdbc.JdbcConnectionImpl.prepareStatement(JdbcConnectionImpl.kt:58)
	at org.jetbrains.exposed.sql.statements.Statement.prepared(Statement.kt:25)
	at org.jetbrains.exposed.sql.statements.Statement.executeIn$exposed_core(Statement.kt:48)
	... 19 more
```

The code works fine if:
1. They are both blocking transactions
2. They are both coroutine-aware transactions

**Comment by MrPowerGamerBR** [comment]
What is happening is `TransactionManager.currentOrNull()` is returing an closed connection, if you add a debug println right after the `newSuspendedTransaction` check, it shows there is a transaction (but it is closed)

**Comment by MrPowerGamerBR** [comment]
This seems to happen when a coroutine shares the same thread as another thread that had an connection before.

If you create your own coroutine dispatcher based on a fixed thread pool of 16 threads, this bug happens only *sometimes*.

If you change your thread pool to only 1 thread, this bug happens every time.

**Comment by ivseb** [comment]
@MrPowerGamerBR have you found a way to solve this "problem"? 
thanks

**Comment by MrPowerGamerBR** [comment]
@ivseb sadly, not yet. The only solution is changing everything to a suspended transaction.

I was trying to debug the issue in Exposed, but couldn't find any issues in Exposed's code 😢

**Comment by ivseb** [comment]
@MrPowerGamerBR I 'm using only suspended transaction in my project. But consequently everything must be a suspended function or must be surrounded by run blocking.  It is not too funny, but it is not blocking.

**Comment by Tapac** [comment]
@MrPowerGamerBR , could you please check the fix from master?

**Comment by MrPowerGamerBR** [comment]
I've done some small and quick tests so I'm not sure if it is 100% fixed, but looks like it was fixed! Thanks @Tapac :3
