### ISSUE TITLE
No dialect available while inserting into a table to postgre db

### ISSUE THREAD

**Issue by trnchawla** [JetBrains/Exposed#916]
I have installed postgre on mac using postgre app. It is running fine on terminal but when I try connect with exposed it is crashing with below stack trace.

> SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" java.lang.IllegalStateException: No dialect registered for pgsql. URL=jdbc:pgsql://localhost/tarun
	at org.jetbrains.exposed.sql.Database$dialect$2.invoke(Database.kt:38)
	at org.jetbrains.exposed.sql.Database$dialect$2.invoke(Database.kt:17)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at org.jetbrains.exposed.sql.Database.getDialect(Database.kt)
	at org.jetbrains.exposed.sql.vendors.DefaultKt.getCurrentDialect(Default.kt:677)
	at org.jetbrains.exposed.sql.QueriesKt.exists(Queries.kt:186)
	at org.jetbrains.exposed.sql.SchemaUtils.createStatements(SchemaUtils.kt:79)
	at org.jetbrains.exposed.sql.SchemaUtils.create(SchemaUtils.kt:176)
	at org.jetbrains.exposed.sql.SchemaUtils.create$default(SchemaUtils.kt:174)
	at MainKt$main$1.invoke(Main.kt:13)
	at MainKt$main$1.invoke(Main.kt)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$inTopLevelTransaction$1.invoke(ThreadLocalTransactionManager.kt:156)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$inTopLevelTransaction$2.invoke(ThreadLocalTransactionManager.kt:197)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:205)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction(ThreadLocalTransactionManager.kt:196)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$transaction$1.invoke(ThreadLocalTransactionManager.kt:134)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:205)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:106)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:104)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction$default(ThreadLocalTransactionManager.kt:103)
	at MainKt.main(Main.kt:12)
	at MainKt.main(Main.kt)

Process finished with exit code 1

Am trying to connect using this code:

`import db.Address
import db.Owner
import db.Restaurant
import org.jetbrains.exposed.sql.Database
import org.jetbrains.exposed.sql.SchemaUtils
import org.jetbrains.exposed.sql.insert
import org.jetbrains.exposed.sql.transactions.transaction

fun main(){
    Database.connect("jdbc:pgsql://localhost:5432/tarun", driver = "com.impossibl.postgres.jdbc.PGDriver",
            user = "tarun", password = "")
    transaction {
        SchemaUtils.create(Address, Owner, Restaurant)
        Address.insert {
            it[street] = "FA"
            it[area] = "GFF"
            it[district] = "F"
            it[state] = "F"
            it[pincode] = "F234"
            it[country] = "India"
        }
    }
    println("hello world")
}`

can you please help what is the issue?

**Comment by Tapac** [comment]
What Exposed version do you use?

**Comment by trnchawla** [comment]
version : 0.21.1
This issue only occures while PostgreSQL using the pgjdbc-ng JDBC driver.

**Comment by Tapac** [comment]
`pgjdbc-ng` driver supported since 0.22.1

**Comment by trnchawla** [comment]
But latest version in releases I can see is 0.21.1.

**Comment by Tapac** [comment]
Please refer to [Change Log](https://github.com/JetBrains/Exposed/blob/master/docs/ChangeLog.md) or find the link on the front page. The release section is outdated at the moment. 
![изображение](https://user-images.githubusercontent.com/194469/82216931-53145280-9922-11ea-9a18-40d18e62dab9.png)

**Comment by trnchawla** [comment]
ok I will check and close the issue. Thanks!

**Comment by trnchawla** [comment]
It is working after upgrade of exposed version in gradle.
