### ISSUE TITLE
Enable use of Exposed with Quarkus / GraalVM Native Image

### ISSUE THREAD

**Issue by tmohme** [JetBrains/Exposed#919]
The possibility to use Exposed with Quarkus / in a GraalVM Native Image would be great.

Unfortunately with Exposed 0.24.1 and GraalVM 20.0.0.r11 I'm unable to build a native image (without questionable intervention), getting the following Error in a project using only PostgreSQL, _not_ H2:

```
Error: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved type during parsing: org.h2.jdbc.JdbcConnection. To diagnose the issue you can use the --allow-incomplete-classpath option. The missing type is then reported at run time when it is accessed the first time.
Detailed message:
Trace: 
        at parsing org.jetbrains.exposed.sql.vendors.H2Kt.isMySQLMode(H2.kt:14)
Call path from entry point to org.jetbrains.exposed.sql.vendors.H2Kt.isMySQLMode(Transaction): 
        at org.jetbrains.exposed.sql.vendors.H2Kt.isMySQLMode(H2.kt:14)
        at org.jetbrains.exposed.sql.vendors.H2Kt.access$isMySQLMode$p(H2.kt:1)
        at org.jetbrains.exposed.sql.vendors.H2FunctionProvider.insert(H2.kt:50)
        at org.jetbrains.exposed.sql.statements.InsertStatement.prepareSQL(InsertStatement.kt:105)
        at org.jetbrains.exposed.sql.statements.StatementContext.sql(Statement.kt:75)
        at org.jetbrains.exposed.exceptions.ExposedSQLException.causedByQueries(Exceptions.kt:18)
        at org.jetbrains.exposed.exceptions.ExposedSQLException.toString(Exceptions.kt:35)
        at java.lang.String.valueOf(String.java:2951)
        at java.io.PrintStream.print(PrintStream.java:745)
        at java.io.PrintStream.println(PrintStream.java:882)
        at com.oracle.svm.jni.functions.JNIFunctions.ExceptionDescribe(JNIFunctions.java:759)
        at com.oracle.svm.core.code.IsolateEnterStub.JNIFunctions_ExceptionDescribe_b5412f7570bccae90b000bc37855f00408b2ad73(generated:0)
```

When I follow the above suggestion (add the `--allow-incomplete-classpath` option), the build succeeds but I can't be sure that I won't run into trouble at runtime.  
It is a wild guess, but I think it shouldn't be too difficult to avoid touching H2 during the initialization.

**Comment by Benjozork** [comment]
I have successfully used Exposed + PostgreSQL in graalvm using those arguments, if that can help :

`--initialize-at-build-time=ch.qos.logback,org.slf4j,org.postgresql --allow-incomplete-classpath`

I used graalvm 20.1 though. You might want to try that.

**Comment by tmohme** [comment]
Thanks for your feedback.
I was also able to get my app up and running with the option `--allow-incomplete-classpath`.

It's just that I have the impression that this option suppresses symptoms and it would be better to fix the underlying cause instead: 
Why do we end up in a piece of H2-specific code when the project has no dependency at all to H2?

If this happens once (during build-time), how can I be sure that something similar won't happen again during run-time and causes the app to crash?

**Comment by DanielEverling** [comment]
Hi @Benjozork 

Which command line do you used or you configured in arguments of gradle / maven project ?
Do you have a example?
