### ISSUE TITLE
Dao new{ } with no values problem "NoSuchElementException: List is empty"

### ISSUE THREAD

**Issue by Aileron1410** [JetBrains/Exposed#95]
`object Users : IdTable<Int>("user") {
	override val id: Column<EntityID<Int>> = Users.integer("id").autoIncrement().primaryKey().entityId()
}
class User(id: EntityID<Int>) : IntEntity(id) {
	companion object : IntEntityClass<User>(Users)
}

fun main(args: Array<String>) {
	Database.connect("jdbc:h2:mem:test", driver = "org.h2.Driver")

	transaction {
		logger.addLogger(SqlLogger())
		SchemaUtils.create(Users)

		User.new {  }
	}
}`
output:
INFO: CREATE TABLE IF NOT EXISTS "USER" (ID INT AUTO_INCREMENT PRIMARY KEY)
Exception in thread "main" java.util.NoSuchElementException: List is empty.
	at kotlin.collections.CollectionsKt___CollectionsKt.first(_Collections.kt:180)
	at org.jetbrains.exposed.sql.statements.BatchInsertStatement.prepareSQL(BatchInsertStatement.kt:47)
	at org.jetbrains.exposed.sql.statements.Statement.executeIn$exposed_main(Statement.kt:43)

**Comment by Synytsia** [comment]
An exception occurred: java.util.NoSuchElementException: List is empty.
	at kotlin.collections.CollectionsKt___CollectionsKt.first(_Collections.kt:184)

I have this problem for my project. Is solution for it?

**Comment by Tapac** [comment]
@Synytsia , Please provide a sample code and Exposed version which you use
