### ISSUE TITLE
Full join doesn't work for MySql

### ISSUE THREAD

**Issue by vloginova** [JetBrains/Exposed#961]
The following select leads to `SQLSyntaxErrorException`. At the same time, it works for me when using postgresql.
```
TableA
    .fullJoin(TableB)
    .slice(TableA.id)
    .select { TableB.id.isNull() }
    .map { it[TableA.id] }
    .toList()
```

Exception:
```
java.sql.SQLSyntaxErrorException Unknown column 'TableA.id' in 'field list'
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1003)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
	at org.jetbrains.exposed.sql.Query.executeInternal(Query.kt:171)
	at org.jetbrains.exposed.sql.Query.executeInternal(Query.kt:106)
	at org.jetbrains.exposed.sql.statements.Statement.executeIn$exposed(Statement.kt:59)
	... 57 more
```

**Comment by Benjozork** [comment]
Can you set logging level to TRACE and provide the query being executed, as well as the DDL of your table in the database ? I could take a look

**Comment by bog-walk** [comment]
If the problem persists with current version 0.41.1, please consider reopening this issue on [YouTrack](https://youtrack.jetbrains.com/newIssue?project=EXPOSED&draftId=25-4442763) with more details about table creation, so we can attempt to investigate further.
