### ISSUE TITLE
createMissingTablesAndColumns() fails with unique constraint

### ISSUE THREAD

**Issue by jschmid** [JetBrains/Exposed#989]
This is related to #952, but not the same bug.

Schema

```kotlin
object Connections : IntIdTable() {
    val fromStation = reference("fromStation", Stations)
    val toStation = reference("toStation", Stations)
    val minDuration = integer("minDuration")

    init {
        uniqueIndex(fromStation, toStation)
    }
}

object Stations : IdTable<String>() {
    override val id = varchar("id", 9).uniqueIndex().entityId()
    val name = varchar("name", 100)

    override val primaryKey = PrimaryKey(id)
}
```

My call: 

```kotlin

val config = HikariConfig().apply {
    // .... using Postgresql
}

val dataSource = HikariDataSource(config)

Database.connect(dataSource)

transaction {
    SchemaUtils.createMissingTablesAndColumns(Connections, Stations)
}
``` 

When I run `createMissingTablesAndColumns()` the first time (with an empty database) it works fine, but when I re-run it, I get this exception:

Log:

```
SQL: ALTER TABLE stations ADD CONSTRAINT stations_id_unique UNIQUE (id)
SQL: ALTER TABLE stations ADD CONSTRAINT stations_id_unique UNIQUE (id)
SQL: ALTER TABLE stations ADD CONSTRAINT stations_id_unique UNIQUE (id)
Exception in thread "main" org.jetbrains.exposed.exceptions.ExposedSQLException: org.postgresql.util.PSQLException: ERROR: relation "stations_id_unique" already exists
SQL: [ALTER TABLE stations ADD CONSTRAINT stations_id_unique UNIQUE (id)]
	at org.jetbrains.exposed.sql.statements.Statement.executeIn$exposed_core(Statement.kt:63)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:129)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:115)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:91)
	at org.jetbrains.exposed.sql.Transaction.exec(Transaction.kt:82)
	at org.jetbrains.exposed.sql.Transaction.exec$default(Transaction.kt:82)
	at org.jetbrains.exposed.sql.SchemaUtils.execStatements(SchemaUtils.kt:174)
	at org.jetbrains.exposed.sql.SchemaUtils.createMissingTablesAndColumns(SchemaUtils.kt:249)
	at org.jetbrains.exposed.sql.SchemaUtils.createMissingTablesAndColumns$default(SchemaUtils.kt:228)
```

**Comment by jschmid** [comment]
Maybe it is because I am using `.uniqueIndex().entityId()` ?

**Comment by Tapac** [comment]
@jschmid, could you please check your code against the latest (0.26.2) version?
