### ISSUE TITLE
Reading a date from DB on Android fails

### ISSUE THREAD

**Issue by Namnodorel** [JetBrains/Exposed#991]
When attempting to read from a table with a `LocalDate`/`LocalDateTime` (using `exposed-java-time`) on Android, Exposed will fail with the following exception:

````
Caused by: java.lang.NoSuchMethodError: No virtual method toLocalDate()Ljava/time/LocalDate; in class Ljava/sql/Date; or its super classes (declaration of 'java.sql.Date' appears in /apex/com.android.runtime/javalib/core-oj.jar)
        at org.jetbrains.exposed.sql.java-time.JavaLocalDateColumnType.valueFromDB(JavaDateColumnType.kt:49)
        at org.jetbrains.exposed.sql.ResultRow.rawToColumnValue(ResultRow.kt:46)
        at org.jetbrains.exposed.sql.ResultRow.get(ResultRow.kt:25)
````

As far as I can tell, this is because [Android doesn't provide this method in its implementation of java.sql.Date](https://developer.android.com/reference/kotlin/java/sql/Date). I think this could be easily worked around by replicating the methods functionality within Exposed.

Note that inserting dates into the DB appears to work fine.

**Comment by Tapac** [comment]
@Namnodorel , thank you for a report. Will be fixed within next release.

**Comment by Namnodorel** [comment]
Unfortunately, I appear to have missed an aspect of this before - the same problem exists with `JavaLocalDateTimeColumnType.notNullValueToDB`. Since I don't have a local Exposed development instance set up I can't really test for more potential places of it (and I just recently had the idea of testing the fix before the next release via JitPack)
